// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
@immutable final class ChatCompletionStreamResponseDeltaFunctionCall {const ChatCompletionStreamResponseDeltaFunctionCall({this.arguments, this.name, });

factory ChatCompletionStreamResponseDeltaFunctionCall.fromJson(Map<String, dynamic> json) { return ChatCompletionStreamResponseDeltaFunctionCall(
  arguments: json['arguments'] as String?,
  name: json['name'] as String?,
); }

/// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
final String? arguments;

/// The name of the function to call.
final String? name;

Map<String, dynamic> toJson() { return {
  'arguments': ?arguments,
  'name': ?name,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'arguments', 'name'}.contains(key)); } 
ChatCompletionStreamResponseDeltaFunctionCall copyWith({String Function()? arguments, String Function()? name, }) { return ChatCompletionStreamResponseDeltaFunctionCall(
  arguments: arguments != null ? arguments() : this.arguments,
  name: name != null ? name() : this.name,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ChatCompletionStreamResponseDeltaFunctionCall &&
          arguments == other.arguments &&
          name == other.name; } 
@override int get hashCode { return Object.hash(arguments, name); } 
@override String toString() { return 'ChatCompletionStreamResponseDeltaFunctionCall(arguments: $arguments, name: $name)'; } 
 }
