// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/ErrorUnionDiscriminatedPostRequest

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_speakeasy/models/error_union_discriminated_post_request/error_union_discriminated_post_request_variant1.dart';import 'package:pub_speakeasy/models/error_union_discriminated_post_request/error_union_discriminated_post_request_variant2.dart';typedef ErrorUnionDiscriminatedPostRequest = OneOf2<ErrorUnionDiscriminatedPostRequestVariant1,ErrorUnionDiscriminatedPostRequestVariant2>;
