// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/CreateMessageRequest (inline: Role)

import 'package:degenerate_runtime/degenerate_runtime.dart';/// The role of the entity that is creating the message. Allowed values include:
/// - `user`: Indicates the message is sent by an actual user and should be used in most cases to represent user-generated messages.
/// - `assistant`: Indicates the message is generated by the assistant. Use this value to insert messages from the assistant into the conversation.
/// 
sealed class CreateMessageRequestRole {const CreateMessageRequestRole();

factory CreateMessageRequestRole.fromJson(String json) { return switch (json) {
  'user' => user,
  'assistant' => assistant,
  _ => CreateMessageRequestRole$Unknown(json),
}; }

static const CreateMessageRequestRole user = CreateMessageRequestRole$user._();

static const CreateMessageRequestRole assistant = CreateMessageRequestRole$assistant._();

static const List<CreateMessageRequestRole> values = [user, assistant];

String get value;
String toJson() { return value; } 
/// The Dart identifier name for this value, or the raw value if unknown.
String get name { return switch (value) {
  'user' => 'user',
  'assistant' => 'assistant',
  _ => value,
}; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return this is CreateMessageRequestRole$Unknown; } 
/// Exhaustive match on the enum value.
W when<W>({required W Function() user, required W Function() assistant, required W Function(String value) $unknown, }) { return switch (this) {
      CreateMessageRequestRole$user() => user(),
      CreateMessageRequestRole$assistant() => assistant(),
      CreateMessageRequestRole$Unknown(:final value) => $unknown(value),
    }; } 
/// Partial match with a required fallback for unhandled variants.
W maybeWhen<W>({required W Function(String value) orElse, W Function()? user, W Function()? assistant, W Function(String value)? $unknown, }) { return switch (this) {
      CreateMessageRequestRole$user() => user != null ? user() : orElse(value),
      CreateMessageRequestRole$assistant() => assistant != null ? assistant() : orElse(value),
      CreateMessageRequestRole$Unknown(:final value) => $unknown != null ? $unknown(value) : orElse(value),
    }; } 
@override String toString() => 'CreateMessageRequestRole($value)';

 }
@immutable final class CreateMessageRequestRole$user extends CreateMessageRequestRole {const CreateMessageRequestRole$user._();

@override String get value => 'user';

@override bool operator ==(Object other) => identical(this, other) || other is CreateMessageRequestRole$user;

@override int get hashCode => 'user'.hashCode;

 }
@immutable final class CreateMessageRequestRole$assistant extends CreateMessageRequestRole {const CreateMessageRequestRole$assistant._();

@override String get value => 'assistant';

@override bool operator ==(Object other) => identical(this, other) || other is CreateMessageRequestRole$assistant;

@override int get hashCode => 'assistant'.hashCode;

 }
@immutable final class CreateMessageRequestRole$Unknown extends CreateMessageRequestRole {const CreateMessageRequestRole$Unknown(this.value);

@override final String value;

@override bool operator ==(Object other) => identical(this, other) ||
    other is CreateMessageRequestRole$Unknown && other.value == value;

@override int get hashCode => value.hashCode;

 }
