// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// The role of the entity that is creating the message. Allowed values include:
/// - `user`: Indicates the message is sent by an actual user and should be used in most cases to represent user-generated messages.
/// - `assistant`: Indicates the message is generated by the assistant. Use this value to insert messages from the assistant into the conversation.
/// 
@immutable final class CreateMessageRequestRole {const CreateMessageRequestRole._(this.value);

factory CreateMessageRequestRole.fromJson(String json) { return switch (json) {
  'user' => user,
  'assistant' => assistant,
  _ => CreateMessageRequestRole._(json),
}; }

static const CreateMessageRequestRole user = CreateMessageRequestRole._('user');

static const CreateMessageRequestRole assistant = CreateMessageRequestRole._('assistant');

static const List<CreateMessageRequestRole> values = [user, assistant];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) => identical(this, other) ||
    other is CreateMessageRequestRole && other.value == value;

@override int get hashCode => value.hashCode;

@override String toString() => 'CreateMessageRequestRole($value)';

 }
