// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// The settings for your integration with Weights and Biases. This payload specifies the project that
/// metrics will be sent to. Optionally, you can set an explicit display name for your run, add tags
/// to your run, and set a default entity (team, username, etc) to be associated with your run.
/// 
@immutable final class Wandb {const Wandb({required this.project, this.name, this.entity, this.tags, });

factory Wandb.fromJson(Map<String, dynamic> json) { return Wandb(
  project: json['project'] as String,
  name: json['name'] as String?,
  entity: json['entity'] as String?,
  tags: (json['tags'] as List<dynamic>?)?.map((e) => e as String).toList(),
); }

/// The name of the project that the new run will be created under.
/// 
/// 
/// Example: `'my-wandb-project'`
final String project;

/// A display name to set for the run. If not set, we will use the Job ID as the name.
/// 
final String? name;

/// The entity to use for the run. This allows you to set the team or username of the WandB user that you would
/// like associated with the run. If not set, the default entity for the registered WandB API key is used.
/// 
final String? entity;

/// A list of tags to be attached to the newly created run. These tags are passed through directly to WandB. Some
/// default tags are generated by OpenAI: "openai/finetune", "openai/{base-model}", "openai/{ftjob-abcdef}".
/// 
final List<String>? tags;

Map<String, dynamic> toJson() { return {
  'project': project,
  'name': ?name,
  'entity': ?entity,
  'tags': ?tags,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('project') && json['project'] is String; } 
Wandb copyWith({String? project, String? Function()? name, String? Function()? entity, List<String>? Function()? tags, }) { return Wandb(
  project: project ?? this.project,
  name: name != null ? name() : this.name,
  entity: entity != null ? entity() : this.entity,
  tags: tags != null ? tags() : this.tags,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is Wandb &&
          project == other.project &&
          name == other.name &&
          entity == other.entity &&
          listEquals(tags, other.tags);

@override int get hashCode => Object.hash(project, name, entity, Object.hashAll(tags ?? const []));

@override String toString() => 'Wandb(project: $project, name: $name, entity: $entity, tags: $tags)';

 }
