// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/SetupIntent (inline: SingleUseMandate)

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/mandate.dart';/// ID of the single_use Mandate generated by the SetupIntent.
///
/// Variants:
/// - `.a` → [String]
/// - `.b` → [Mandate]
typedef SingleUseMandate = OneOf2<String,Mandate>;
