// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// If the audio output modality is requested, this object contains data
/// about the audio response from the model. [Learn more](/docs/guides/audio).
/// 
@immutable final class ChatCompletionResponseMessageAudio {const ChatCompletionResponseMessageAudio({required this.id, required this.expiresAt, required this.data, required this.transcript, });

factory ChatCompletionResponseMessageAudio.fromJson(Map<String, dynamic> json) { return ChatCompletionResponseMessageAudio(
  id: json['id'] as String,
  expiresAt: (json['expires_at'] as num).toInt(),
  data: json['data'] as String,
  transcript: json['transcript'] as String,
); }

/// Unique identifier for this audio response.
final String id;

/// The Unix timestamp (in seconds) for when this audio response will
/// no longer be accessible on the server for use in multi-turn
/// conversations.
/// 
final int expiresAt;

/// Base64 encoded audio bytes generated by the model, in the format
/// specified in the request.
/// 
final String data;

/// Transcript of the audio generated by the model.
final String transcript;

Map<String, dynamic> toJson() { return {
  'id': id,
  'expires_at': expiresAt,
  'data': data,
  'transcript': transcript,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('id') && json['id'] is String &&
      json.containsKey('expires_at') && json['expires_at'] is num &&
      json.containsKey('data') && json['data'] is String &&
      json.containsKey('transcript') && json['transcript'] is String; } 
ChatCompletionResponseMessageAudio copyWith({String? id, int? expiresAt, String? data, String? transcript, }) { return ChatCompletionResponseMessageAudio(
  id: id ?? this.id,
  expiresAt: expiresAt ?? this.expiresAt,
  data: data ?? this.data,
  transcript: transcript ?? this.transcript,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ChatCompletionResponseMessageAudio &&
          id == other.id &&
          expiresAt == other.expiresAt &&
          data == other.data &&
          transcript == other.transcript; } 
@override int get hashCode { return Object.hash(id, expiresAt, data, transcript); } 
@override String toString() { return 'ChatCompletionResponseMessageAudio(id: $id, expiresAt: $expiresAt, data: $data, transcript: $transcript)'; } 
 }
