// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// The custom tool that the model called.
@immutable final class ChatCompletionMessageCustomToolCallCustom {const ChatCompletionMessageCustomToolCallCustom({required this.name, required this.input, });

factory ChatCompletionMessageCustomToolCallCustom.fromJson(Map<String, dynamic> json) { return ChatCompletionMessageCustomToolCallCustom(
  name: json['name'] as String,
  input: json['input'] as String,
); }

/// The name of the custom tool to call.
final String name;

/// The input for the custom tool call generated by the model.
final String input;

Map<String, dynamic> toJson() { return {
  'name': name,
  'input': input,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('name') && json['name'] is String &&
      json.containsKey('input') && json['input'] is String; } 
ChatCompletionMessageCustomToolCallCustom copyWith({String? name, String? input, }) { return ChatCompletionMessageCustomToolCallCustom(
  name: name ?? this.name,
  input: input ?? this.input,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ChatCompletionMessageCustomToolCallCustom &&
          name == other.name &&
          input == other.input; } 
@override int get hashCode { return Object.hash(name, input); } 
@override String toString() { return 'ChatCompletionMessageCustomToolCallCustom(name: $name, input: $input)'; } 
 }
