// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';import 'package:pub_stripe_spec3/models/payment_method_options_param105.dart';typedef PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsAmazonPay = OneOf2<PaymentMethodOptionsParam105,GetPaymentMethodConfigurationsApplicationVariant2>;
