// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/PostPaymentIntentsIntentConfirmRequest (inline: PaymentMethodOptions > UsBankAccount)

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';import 'package:pub_stripe_spec3/models/payment_intent_payment_method_options_param14.dart';typedef PostPaymentIntentsIntentConfirmRequestPaymentMethodOptionsUsBankAccount = OneOf2<PaymentIntentPaymentMethodOptionsParam14,GetPaymentMethodConfigurationsApplicationVariant2>;
