// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';import 'package:pub_stripe_spec3/models/invoice_payment_method_options_param12.dart';typedef PaymentSettingsPaymentMethodOptionsPayto = OneOf2<InvoicePaymentMethodOptionsParam12,GetPaymentMethodConfigurationsApplicationVariant2>;
