// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/ApplyPatchToolCallOutput

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/apply_patch_call_output_status.dart';/// The output emitted by an apply patch tool call.
@immutable final class ApplyPatchToolCallOutput {const ApplyPatchToolCallOutput({required this.id, required this.callId, required this.status, this.type = 'apply_patch_call_output', this.output, this.createdBy, });

factory ApplyPatchToolCallOutput.fromJson(Map<String, dynamic> json) { return ApplyPatchToolCallOutput(
  type: json['type'] as String,
  id: json['id'] as String,
  callId: json['call_id'] as String,
  status: ApplyPatchCallOutputStatus.fromJson(json['status'] as String),
  output: json['output'] as String?,
  createdBy: json['created_by'] as String?,
); }

/// The type of the item. Always `apply_patch_call_output`.
final String type;

/// The unique ID of the apply patch tool call output. Populated when this item is returned via API.
final String id;

/// The unique ID of the apply patch tool call generated by the model.
final String callId;

/// The status of the apply patch tool call output. One of `completed` or `failed`.
final ApplyPatchCallOutputStatus status;

/// Optional textual output returned by the apply patch tool.
final String? output;

/// The ID of the entity that created this tool call output.
final String? createdBy;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'call_id': callId,
  'status': status.toJson(),
  'output': ?output,
  'created_by': ?createdBy,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('status'); } 
ApplyPatchToolCallOutput copyWith({String? type, String? id, String? callId, ApplyPatchCallOutputStatus? status, String? Function()? output, String? Function()? createdBy, }) { return ApplyPatchToolCallOutput(
  type: type ?? this.type,
  id: id ?? this.id,
  callId: callId ?? this.callId,
  status: status ?? this.status,
  output: output != null ? output() : this.output,
  createdBy: createdBy != null ? createdBy() : this.createdBy,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is ApplyPatchToolCallOutput &&
          type == other.type &&
          id == other.id &&
          callId == other.callId &&
          status == other.status &&
          output == other.output &&
          createdBy == other.createdBy;

@override int get hashCode => Object.hash(type, id, callId, status, output, createdBy);

@override String toString() => 'ApplyPatchToolCallOutput(type: $type, id: $id, callId: $callId, status: $status, output: $output, createdBy: $createdBy)';

 }
