// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/apply_patch_call_status.dart';import 'package:pub_openai/models/apply_patch_operation_param.dart';/// A tool call representing a request to create, delete, or update files using diff patches.
@immutable final class ApplyPatchToolCallItemParam {const ApplyPatchToolCallItemParam({required this.callId, required this.status, required this.operation, this.type = 'apply_patch_call', this.id, });

factory ApplyPatchToolCallItemParam.fromJson(Map<String, dynamic> json) { return ApplyPatchToolCallItemParam(
  type: json['type'] as String,
  id: json['id'] as String?,
  callId: json['call_id'] as String,
  status: ApplyPatchCallStatus.fromJson(json['status'] as String),
  operation: ApplyPatchOperationParam.fromJson(json['operation'] as Map<String, dynamic>),
); }

/// The type of the item. Always `apply_patch_call`.
final String type;

/// The unique ID of the apply patch tool call. Populated when this item is returned via API.
final String? id;

/// The unique ID of the apply patch tool call generated by the model.
final String callId;

/// The status of the apply patch tool call. One of `in_progress` or `completed`.
final ApplyPatchCallStatus status;

/// The specific create, delete, or update instruction for the apply_patch tool call.
final ApplyPatchOperationParam operation;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': ?id,
  'call_id': callId,
  'status': status.toJson(),
  'operation': operation.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('status') &&
      json.containsKey('operation'); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
if (callId.isEmpty) { errors.add('callId: length must be >= 1'); }
if (callId.length > 64) { errors.add('callId: length must be <= 64'); }
return errors; } 
ApplyPatchToolCallItemParam copyWith({String? type, String? Function()? id, String? callId, ApplyPatchCallStatus? status, ApplyPatchOperationParam? operation, }) { return ApplyPatchToolCallItemParam(
  type: type ?? this.type,
  id: id != null ? id() : this.id,
  callId: callId ?? this.callId,
  status: status ?? this.status,
  operation: operation ?? this.operation,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is ApplyPatchToolCallItemParam &&
          type == other.type &&
          id == other.id &&
          callId == other.callId &&
          status == other.status &&
          operation == other.operation;

@override int get hashCode => Object.hash(type, id, callId, status, operation);

@override String toString() => 'ApplyPatchToolCallItemParam(type: $type, id: $id, callId: $callId, status: $status, operation: $operation)';

 }
