// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/apply_patch_call_status.dart';import 'package:pub_openai/models/apply_patch_tool_call/apply_patch_tool_call_operation.dart';/// A tool call that applies file diffs by creating, deleting, or updating files.
@immutable final class ApplyPatchToolCall {const ApplyPatchToolCall({required this.id, required this.callId, required this.status, required this.operation, this.type = 'apply_patch_call', this.createdBy, });

factory ApplyPatchToolCall.fromJson(Map<String, dynamic> json) { return ApplyPatchToolCall(
  type: json['type'] as String,
  id: json['id'] as String,
  callId: json['call_id'] as String,
  status: ApplyPatchCallStatus.fromJson(json['status'] as String),
  operation: ApplyPatchToolCallOperation.fromJson(json['operation'] as Map<String, dynamic>),
  createdBy: json['created_by'] as String?,
); }

/// The type of the item. Always `apply_patch_call`.
final String type;

/// The unique ID of the apply patch tool call. Populated when this item is returned via API.
final String id;

/// The unique ID of the apply patch tool call generated by the model.
final String callId;

/// The status of the apply patch tool call. One of `in_progress` or `completed`.
final ApplyPatchCallStatus status;

/// One of the create_file, delete_file, or update_file operations applied via apply_patch.
final ApplyPatchToolCallOperation operation;

/// The ID of the entity that created this tool call.
final String? createdBy;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'call_id': callId,
  'status': status.toJson(),
  'operation': operation.toJson(),
  'created_by': ?createdBy,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('status') &&
      json.containsKey('operation'); } 
ApplyPatchToolCall copyWith({String? type, String? id, String? callId, ApplyPatchCallStatus? status, ApplyPatchToolCallOperation? operation, String? Function()? createdBy, }) { return ApplyPatchToolCall(
  type: type ?? this.type,
  id: id ?? this.id,
  callId: callId ?? this.callId,
  status: status ?? this.status,
  operation: operation ?? this.operation,
  createdBy: createdBy != null ? createdBy() : this.createdBy,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ApplyPatchToolCall &&
          type == other.type &&
          id == other.id &&
          callId == other.callId &&
          status == other.status &&
          operation == other.operation &&
          createdBy == other.createdBy; } 
@override int get hashCode { return Object.hash(type, id, callId, status, operation, createdBy); } 
@override String toString() { return 'ApplyPatchToolCall(type: $type, id: $id, callId: $callId, status: $status, operation: $operation, createdBy: $createdBy)'; } 
 }
