// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/ChatCompletionStreamResponseDelta

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/chat_completion_message_tool_call_chunk.dart';import 'package:pub_openai/models/chat_completion_stream_response_delta/chat_completion_stream_response_delta_function_call.dart';/// The role of the author of this message.
@immutable final class ChatCompletionStreamResponseDeltaRole {const ChatCompletionStreamResponseDeltaRole._(this.value);

factory ChatCompletionStreamResponseDeltaRole.fromJson(String json) { return switch (json) {
  'developer' => developer,
  'system' => system,
  'user' => user,
  'assistant' => assistant,
  'tool' => tool,
  _ => ChatCompletionStreamResponseDeltaRole._(json),
}; }

static const ChatCompletionStreamResponseDeltaRole developer = ChatCompletionStreamResponseDeltaRole._('developer');

static const ChatCompletionStreamResponseDeltaRole system = ChatCompletionStreamResponseDeltaRole._('system');

static const ChatCompletionStreamResponseDeltaRole user = ChatCompletionStreamResponseDeltaRole._('user');

static const ChatCompletionStreamResponseDeltaRole assistant = ChatCompletionStreamResponseDeltaRole._('assistant');

static const ChatCompletionStreamResponseDeltaRole tool = ChatCompletionStreamResponseDeltaRole._('tool');

static const List<ChatCompletionStreamResponseDeltaRole> values = [developer, system, user, assistant, tool];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) => identical(this, other) ||
    other is ChatCompletionStreamResponseDeltaRole && other.value == value;

@override int get hashCode => value.hashCode;

@override String toString() => 'ChatCompletionStreamResponseDeltaRole($value)';

 }
/// A chat completion delta generated by streamed model responses.
@immutable final class ChatCompletionStreamResponseDelta {const ChatCompletionStreamResponseDelta({this.content, this.functionCall, this.toolCalls, this.role, this.refusal, });

factory ChatCompletionStreamResponseDelta.fromJson(Map<String, dynamic> json) { return ChatCompletionStreamResponseDelta(
  content: json['content'] as String?,
  functionCall: json['function_call'] != null ? ChatCompletionStreamResponseDeltaFunctionCall.fromJson(json['function_call'] as Map<String, dynamic>) : null,
  toolCalls: (json['tool_calls'] as List<dynamic>?)?.map((e) => ChatCompletionMessageToolCallChunk.fromJson(e as Map<String, dynamic>)).toList(),
  role: json['role'] != null ? ChatCompletionStreamResponseDeltaRole.fromJson(json['role'] as String) : null,
  refusal: json['refusal'] as String?,
); }

/// The contents of the chunk message.
final String? content;

/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
final ChatCompletionStreamResponseDeltaFunctionCall? functionCall;

final List<ChatCompletionMessageToolCallChunk>? toolCalls;

/// The role of the author of this message.
final ChatCompletionStreamResponseDeltaRole? role;

/// The refusal message generated by the model.
final String? refusal;

Map<String, dynamic> toJson() { return {
  'content': ?content,
  if (functionCall != null) 'function_call': functionCall?.toJson(),
  if (toolCalls != null) 'tool_calls': toolCalls?.map((e) => e.toJson()).toList(),
  if (role != null) 'role': role?.toJson(),
  'refusal': ?refusal,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'content', 'function_call', 'tool_calls', 'role', 'refusal'}.contains(key)); } 
ChatCompletionStreamResponseDelta copyWith({String? Function()? content, ChatCompletionStreamResponseDeltaFunctionCall? Function()? functionCall, List<ChatCompletionMessageToolCallChunk>? Function()? toolCalls, ChatCompletionStreamResponseDeltaRole? Function()? role, String? Function()? refusal, }) { return ChatCompletionStreamResponseDelta(
  content: content != null ? content() : this.content,
  functionCall: functionCall != null ? functionCall() : this.functionCall,
  toolCalls: toolCalls != null ? toolCalls() : this.toolCalls,
  role: role != null ? role() : this.role,
  refusal: refusal != null ? refusal() : this.refusal,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is ChatCompletionStreamResponseDelta &&
          content == other.content &&
          functionCall == other.functionCall &&
          listEquals(toolCalls, other.toolCalls) &&
          role == other.role &&
          refusal == other.refusal;

@override int get hashCode => Object.hash(content, functionCall, Object.hashAll(toolCalls ?? const []), role, refusal);

@override String toString() => 'ChatCompletionStreamResponseDelta(content: $content, functionCall: $functionCall, toolCalls: $toolCalls, role: $role, refusal: $refusal)';

 }
