// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/chat_completion_message_tool_calls2.dart';import 'package:pub_openai/models/chat_completion_request_assistant_message/chat_completion_request_assistant_message_audio.dart';import 'package:pub_openai/models/chat_completion_request_assistant_message/chat_completion_request_assistant_message_content.dart';import 'package:pub_openai/models/chat_completion_request_assistant_message/chat_completion_request_assistant_message_function_call.dart';import 'package:pub_openai/models/chat_completion_request_assistant_message_content_part.dart';/// Messages sent by the model in response to user messages.
/// 
@immutable final class ChatCompletionRequestAssistantMessage {const ChatCompletionRequestAssistantMessage({required this.role, this.content, this.refusal, this.name, this.audio, this.toolCalls, this.functionCall, });

factory ChatCompletionRequestAssistantMessage.fromJson(Map<String, dynamic> json) { return ChatCompletionRequestAssistantMessage(
  content: json['content'] != null ? OneOf2.parse(json['content'], fromA: (v) => v as String, fromB: (v) => (v as List<dynamic>).map((e) => ChatCompletionRequestAssistantMessageContentPart.fromJson(e as Map<String, dynamic>)).toList(),) : null,
  refusal: json['refusal'] as String?,
  role: json['role'] as String,
  name: json['name'] as String?,
  audio: json['audio'] != null ? ChatCompletionRequestAssistantMessageAudio.fromJson(json['audio'] as Map<String, dynamic>) : null,
  toolCalls: (json['tool_calls'] as List<dynamic>?)?.map((e) => ChatCompletionMessageToolCalls2.fromJson(e as Map<String, dynamic>)).toList(),
  functionCall: json['function_call'] != null ? ChatCompletionRequestAssistantMessageFunctionCall.fromJson(json['function_call'] as Map<String, dynamic>) : null,
); }

/// The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
/// 
final ChatCompletionRequestAssistantMessageContent? content;

/// The refusal message by the assistant.
final String? refusal;

/// The role of the messages author, in this case `assistant`.
final String role;

/// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
final String? name;

/// Data about a previous audio response from the model.
/// [Learn more](/docs/guides/audio).
/// 
final ChatCompletionRequestAssistantMessageAudio? audio;

/// The tool calls generated by the model, such as function calls.
final List<ChatCompletionMessageToolCalls2>? toolCalls;

/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
final ChatCompletionRequestAssistantMessageFunctionCall? functionCall;

Map<String, dynamic> toJson() { return {
  if (content != null) 'content': content?.toJson(),
  'refusal': ?refusal,
  'role': role,
  'name': ?name,
  if (audio != null) 'audio': audio?.toJson(),
  if (toolCalls != null) 'tool_calls': toolCalls?.map((e) => e.toJson()).toList(),
  if (functionCall != null) 'function_call': functionCall?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('role') && json['role'] is String; } 
ChatCompletionRequestAssistantMessage copyWith({ChatCompletionRequestAssistantMessageContent? Function()? content, String? Function()? refusal, String? role, String Function()? name, ChatCompletionRequestAssistantMessageAudio? Function()? audio, List<ChatCompletionMessageToolCalls2> Function()? toolCalls, ChatCompletionRequestAssistantMessageFunctionCall? Function()? functionCall, }) { return ChatCompletionRequestAssistantMessage(
  content: content != null ? content() : this.content,
  refusal: refusal != null ? refusal() : this.refusal,
  role: role ?? this.role,
  name: name != null ? name() : this.name,
  audio: audio != null ? audio() : this.audio,
  toolCalls: toolCalls != null ? toolCalls() : this.toolCalls,
  functionCall: functionCall != null ? functionCall() : this.functionCall,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ChatCompletionRequestAssistantMessage &&
          content == other.content &&
          refusal == other.refusal &&
          role == other.role &&
          name == other.name &&
          audio == other.audio &&
          listEquals(toolCalls, other.toolCalls) &&
          functionCall == other.functionCall; } 
@override int get hashCode { return Object.hash(content, refusal, role, name, audio, Object.hashAll(toolCalls ?? const []), functionCall); } 
@override String toString() { return 'ChatCompletionRequestAssistantMessage(content: $content, refusal: $refusal, role: $role, name: $name, audio: $audio, toolCalls: $toolCalls, functionCall: $functionCall)'; } 
 }
