// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/chat_completion_message_tool_calls2.dart';import 'package:pub_openai/models/chat_completion_response_message/chat_completion_response_message_annotations.dart';import 'package:pub_openai/models/chat_completion_response_message/chat_completion_response_message_audio.dart';import 'package:pub_openai/models/chat_completion_response_message/chat_completion_response_message_function_call.dart';import 'package:pub_openai/models/chat_completion_response_message/chat_completion_response_message_role.dart';/// A chat completion message generated by the model.
@immutable final class ChatCompletionResponseMessage {const ChatCompletionResponseMessage({required this.content, required this.refusal, required this.role, this.toolCalls, this.annotations, this.functionCall, this.audio, });

factory ChatCompletionResponseMessage.fromJson(Map<String, dynamic> json) { return ChatCompletionResponseMessage(
  content: json['content'] as String?,
  refusal: json['refusal'] as String?,
  toolCalls: (json['tool_calls'] as List<dynamic>?)?.map((e) => ChatCompletionMessageToolCalls2.fromJson(e as Map<String, dynamic>)).toList(),
  annotations: (json['annotations'] as List<dynamic>?)?.map((e) => ChatCompletionResponseMessageAnnotations.fromJson(e as Map<String, dynamic>)).toList(),
  role: ChatCompletionResponseMessageRole.fromJson(json['role'] as String),
  functionCall: json['function_call'] != null ? ChatCompletionResponseMessageFunctionCall.fromJson(json['function_call'] as Map<String, dynamic>) : null,
  audio: json['audio'] != null ? ChatCompletionResponseMessageAudio.fromJson(json['audio'] as Map<String, dynamic>) : null,
); }

/// The contents of the message.
final String? content;

/// The refusal message generated by the model.
final String? refusal;

/// The tool calls generated by the model, such as function calls.
final List<ChatCompletionMessageToolCalls2>? toolCalls;

/// Annotations for the message, when applicable, as when using the
/// [web search tool](/docs/guides/tools-web-search?api-mode=chat).
/// 
final List<ChatCompletionResponseMessageAnnotations>? annotations;

/// The role of the author of this message.
final ChatCompletionResponseMessageRole role;

/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
final ChatCompletionResponseMessageFunctionCall? functionCall;

/// If the audio output modality is requested, this object contains data
/// about the audio response from the model. [Learn more](/docs/guides/audio).
/// 
final ChatCompletionResponseMessageAudio? audio;

Map<String, dynamic> toJson() { return {
  'content': ?content,
  'refusal': ?refusal,
  if (toolCalls != null) 'tool_calls': toolCalls?.map((e) => e.toJson()).toList(),
  if (annotations != null) 'annotations': annotations?.map((e) => e.toJson()).toList(),
  'role': role.toJson(),
  if (functionCall != null) 'function_call': functionCall?.toJson(),
  if (audio != null) 'audio': audio?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('content') && json['content'] is String &&
      json.containsKey('refusal') && json['refusal'] is String &&
      json.containsKey('role'); } 
ChatCompletionResponseMessage copyWith({String? Function()? content, String? Function()? refusal, List<ChatCompletionMessageToolCalls2> Function()? toolCalls, List<ChatCompletionResponseMessageAnnotations> Function()? annotations, ChatCompletionResponseMessageRole? role, ChatCompletionResponseMessageFunctionCall Function()? functionCall, ChatCompletionResponseMessageAudio? Function()? audio, }) { return ChatCompletionResponseMessage(
  content: content != null ? content() : this.content,
  refusal: refusal != null ? refusal() : this.refusal,
  toolCalls: toolCalls != null ? toolCalls() : this.toolCalls,
  annotations: annotations != null ? annotations() : this.annotations,
  role: role ?? this.role,
  functionCall: functionCall != null ? functionCall() : this.functionCall,
  audio: audio != null ? audio() : this.audio,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ChatCompletionResponseMessage &&
          content == other.content &&
          refusal == other.refusal &&
          listEquals(toolCalls, other.toolCalls) &&
          listEquals(annotations, other.annotations) &&
          role == other.role &&
          functionCall == other.functionCall &&
          audio == other.audio; } 
@override int get hashCode { return Object.hash(content, refusal, Object.hashAll(toolCalls ?? const []), Object.hashAll(annotations ?? const []), role, functionCall, audio); } 
@override String toString() { return 'ChatCompletionResponseMessage(content: $content, refusal: $refusal, toolCalls: $toolCalls, annotations: $annotations, role: $role, functionCall: $functionCall, audio: $audio)'; } 
 }
