// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/code_interpreter_tool_call/code_interpreter_tool_call_outputs.dart';/// The status of the code interpreter tool call. Valid values are `in_progress`, `completed`, `incomplete`, `interpreting`, and `failed`.
/// 
@immutable final class CodeInterpreterToolCallStatus {const CodeInterpreterToolCallStatus._(this.value);

factory CodeInterpreterToolCallStatus.fromJson(String json) { return switch (json) {
  'in_progress' => inProgress,
  'completed' => completed,
  'incomplete' => incomplete,
  'interpreting' => interpreting,
  'failed' => failed,
  _ => CodeInterpreterToolCallStatus._(json),
}; }

static const CodeInterpreterToolCallStatus inProgress = CodeInterpreterToolCallStatus._('in_progress');

static const CodeInterpreterToolCallStatus completed = CodeInterpreterToolCallStatus._('completed');

static const CodeInterpreterToolCallStatus incomplete = CodeInterpreterToolCallStatus._('incomplete');

static const CodeInterpreterToolCallStatus interpreting = CodeInterpreterToolCallStatus._('interpreting');

static const CodeInterpreterToolCallStatus failed = CodeInterpreterToolCallStatus._('failed');

static const List<CodeInterpreterToolCallStatus> values = [inProgress, completed, incomplete, interpreting, failed];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) => identical(this, other) ||
    other is CodeInterpreterToolCallStatus && other.value == value;

@override int get hashCode => value.hashCode;

@override String toString() => 'CodeInterpreterToolCallStatus($value)';

 }
/// A tool call to run code.
/// 
@immutable final class CodeInterpreterToolCall {const CodeInterpreterToolCall({required this.id, required this.status, required this.containerId, required this.code, required this.outputs, this.type = 'code_interpreter_call', });

factory CodeInterpreterToolCall.fromJson(Map<String, dynamic> json) { return CodeInterpreterToolCall(
  type: json['type'] as String,
  id: json['id'] as String,
  status: CodeInterpreterToolCallStatus.fromJson(json['status'] as String),
  containerId: json['container_id'] as String,
  code: json['code'] as String?,
  outputs: (json['outputs'] as List<dynamic>?)?.map((e) => CodeInterpreterToolCallOutputs.fromJson(e as Map<String, dynamic>)).toList(),
); }

/// The type of the code interpreter tool call. Always `code_interpreter_call`.
/// 
final String type;

/// The unique ID of the code interpreter tool call.
/// 
final String id;

/// The status of the code interpreter tool call. Valid values are `in_progress`, `completed`, `incomplete`, `interpreting`, and `failed`.
/// 
final CodeInterpreterToolCallStatus status;

/// The ID of the container used to run the code.
/// 
final String containerId;

/// The code to run, or null if not available.
/// 
final String? code;

/// The outputs generated by the code interpreter, such as logs or images.
/// Can be null if no outputs are available.
/// 
final List<CodeInterpreterToolCallOutputs>? outputs;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'status': status.toJson(),
  'container_id': containerId,
  'code': code,
  'outputs': outputs?.map((e) => e.toJson()).toList(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('status') &&
      json.containsKey('container_id') && json['container_id'] is String &&
      json.containsKey('code') && json['code'] is String &&
      json.containsKey('outputs'); } 
CodeInterpreterToolCall copyWith({String? type, String? id, CodeInterpreterToolCallStatus? status, String? containerId, String? Function()? code, List<CodeInterpreterToolCallOutputs>? Function()? outputs, }) { return CodeInterpreterToolCall(
  type: type ?? this.type,
  id: id ?? this.id,
  status: status ?? this.status,
  containerId: containerId ?? this.containerId,
  code: code != null ? code() : this.code,
  outputs: outputs != null ? outputs() : this.outputs,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is CodeInterpreterToolCall &&
          type == other.type &&
          id == other.id &&
          status == other.status &&
          containerId == other.containerId &&
          code == other.code &&
          listEquals(outputs, other.outputs);

@override int get hashCode => Object.hash(type, id, status, containerId, code, Object.hashAll(outputs ?? const []));

@override String toString() => 'CodeInterpreterToolCall(type: $type, id: $id, status: $status, containerId: $containerId, code: $code, outputs: $outputs)';

 }
