// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/CompactionSummaryItemParam

import 'package:degenerate_runtime/degenerate_runtime.dart';/// A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
@immutable final class CompactionSummaryItemParam {const CompactionSummaryItemParam({required this.encryptedContent, this.id, this.type = 'compaction', });

factory CompactionSummaryItemParam.fromJson(Map<String, dynamic> json) { return CompactionSummaryItemParam(
  id: json['id'] as String?,
  type: json['type'] as String,
  encryptedContent: json['encrypted_content'] as String,
); }

/// The ID of the compaction item.
final String? id;

/// The type of the item. Always `compaction`.
final String type;

/// The encrypted content of the compaction summary.
final String encryptedContent;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  'type': type,
  'encrypted_content': encryptedContent,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('encrypted_content') && json['encrypted_content'] is String; } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
if (encryptedContent.length > 10485760) { errors.add('encryptedContent: length must be <= 10485760'); }
return errors; } 
CompactionSummaryItemParam copyWith({String? Function()? id, String? type, String? encryptedContent, }) { return CompactionSummaryItemParam(
  id: id != null ? id() : this.id,
  type: type ?? this.type,
  encryptedContent: encryptedContent ?? this.encryptedContent,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is CompactionSummaryItemParam &&
          id == other.id &&
          type == other.type &&
          encryptedContent == other.encryptedContent;

@override int get hashCode => Object.hash(id, type, encryptedContent);

@override String toString() => 'CompactionSummaryItemParam(id: $id, type: $type, encryptedContent: $encryptedContent)';

 }
