// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/CompactionBody

import 'package:degenerate_runtime/degenerate_runtime.dart';/// A compaction item generated by the [`v1/responses/compact` API](/docs/api-reference/responses/compact).
@immutable final class CompactionBody {const CompactionBody({required this.id, required this.encryptedContent, this.type = 'compaction', this.createdBy, });

factory CompactionBody.fromJson(Map<String, dynamic> json) { return CompactionBody(
  type: json['type'] as String,
  id: json['id'] as String,
  encryptedContent: json['encrypted_content'] as String,
  createdBy: json['created_by'] as String?,
); }

/// The type of the item. Always `compaction`.
final String type;

/// The unique ID of the compaction item.
final String id;

/// The encrypted content that was produced by compaction.
final String encryptedContent;

/// The identifier of the actor that created the item.
final String? createdBy;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'encrypted_content': encryptedContent,
  'created_by': ?createdBy,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('encrypted_content') && json['encrypted_content'] is String; } 
CompactionBody copyWith({String? type, String? id, String? encryptedContent, String? Function()? createdBy, }) { return CompactionBody(
  type: type ?? this.type,
  id: id ?? this.id,
  encryptedContent: encryptedContent ?? this.encryptedContent,
  createdBy: createdBy != null ? createdBy() : this.createdBy,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is CompactionBody &&
          type == other.type &&
          id == other.id &&
          encryptedContent == other.encryptedContent &&
          createdBy == other.createdBy;

@override int get hashCode => Object.hash(type, id, encryptedContent, createdBy);

@override String toString() => 'CompactionBody(type: $type, id: $id, encryptedContent: $encryptedContent, createdBy: $createdBy)';

 }
