// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/CreateEmbeddingResponse

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/chat_completion_list/chat_completion_list_object.dart';import 'package:pub_openai/models/create_embedding_response/create_embedding_response_usage.dart';import 'package:pub_openai/models/embedding.dart';@immutable final class CreateEmbeddingResponse {const CreateEmbeddingResponse({required this.data, required this.model, required this.object, required this.usage, });

factory CreateEmbeddingResponse.fromJson(Map<String, dynamic> json) { return CreateEmbeddingResponse(
  data: (json['data'] as List<dynamic>).map((e) => Embedding.fromJson(e as Map<String, dynamic>)).toList(),
  model: json['model'] as String,
  object: ChatCompletionListObject.fromJson(json['object'] as String),
  usage: CreateEmbeddingResponseUsage.fromJson(json['usage'] as Map<String, dynamic>),
); }

/// The list of embeddings generated by the model.
final List<Embedding> data;

/// The name of the model used to generate the embedding.
final String model;

/// The object type, which is always "list".
final ChatCompletionListObject object;

/// The usage information for the request.
final CreateEmbeddingResponseUsage usage;

Map<String, dynamic> toJson() { return {
  'data': data.map((e) => e.toJson()).toList(),
  'model': model,
  'object': object.toJson(),
  'usage': usage.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('data') &&
      json.containsKey('model') && json['model'] is String &&
      json.containsKey('object') &&
      json.containsKey('usage'); } 
CreateEmbeddingResponse copyWith({List<Embedding>? data, String? model, ChatCompletionListObject? object, CreateEmbeddingResponseUsage? usage, }) { return CreateEmbeddingResponse(
  data: data ?? this.data,
  model: model ?? this.model,
  object: object ?? this.object,
  usage: usage ?? this.usage,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is CreateEmbeddingResponse &&
          listEquals(data, other.data) &&
          model == other.model &&
          object == other.object &&
          usage == other.usage;

@override int get hashCode => Object.hash(Object.hashAll(data), model, object, usage);

@override String toString() => 'CreateEmbeddingResponse(data: $data, model: $model, object: $object, usage: $usage)';

 }
