// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/CreateMessageRequest

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/create_message_request/attachments.dart';import 'package:pub_openai/models/create_message_request/create_message_request_content.dart';import 'package:pub_openai/models/create_message_request/create_message_request_role.dart';import 'package:pub_openai/models/message_content_image_file_object.dart';import 'package:pub_openai/models/message_content_image_url_object.dart';import 'package:pub_openai/models/message_request_content_text_object.dart';@immutable final class CreateMessageRequest {const CreateMessageRequest({required this.role, required this.content, this.attachments, this.metadata, });

factory CreateMessageRequest.fromJson(Map<String, dynamic> json) { return CreateMessageRequest(
  role: CreateMessageRequestRole.fromJson(json['role'] as String),
  content: OneOf2.parse(json['content'], fromA: (v) => v as String, fromB: (v) => (v as List<dynamic>).map((e) => OneOf3.parse(e, fromA: (v) => MessageContentImageFileObject.fromJson(v as Map<String, dynamic>), fromB: (v) => MessageContentImageUrlObject.fromJson(v as Map<String, dynamic>), fromC: (v) => MessageRequestContentTextObject.fromJson(v as Map<String, dynamic>),)).toList(),),
  attachments: (json['attachments'] as List<dynamic>?)?.map((e) => Attachments.fromJson(e as Map<String, dynamic>)).toList(),
  metadata: (json['metadata'] as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, v as String)),
); }

/// The role of the entity that is creating the message. Allowed values include:
/// - `user`: Indicates the message is sent by an actual user and should be used in most cases to represent user-generated messages.
/// - `assistant`: Indicates the message is generated by the assistant. Use this value to insert messages from the assistant into the conversation.
/// 
final CreateMessageRequestRole role;

final CreateMessageRequestContent content;

/// A list of files attached to the message, and the tools they should be added to.
final List<Attachments>? attachments;

final Map<String,String>? metadata;

Map<String, dynamic> toJson() { return {
  'role': role.toJson(),
  'content': content.toJson(),
  if (attachments != null) 'attachments': attachments?.map((e) => e.toJson()).toList(),
  'metadata': ?metadata,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('role') &&
      json.containsKey('content'); } 
CreateMessageRequest copyWith({CreateMessageRequestRole? role, CreateMessageRequestContent? content, List<Attachments>? Function()? attachments, Map<String, String>? Function()? metadata, }) { return CreateMessageRequest(
  role: role ?? this.role,
  content: content ?? this.content,
  attachments: attachments != null ? attachments() : this.attachments,
  metadata: metadata != null ? metadata() : this.metadata,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is CreateMessageRequest &&
          role == other.role &&
          content == other.content &&
          listEquals(attachments, other.attachments) &&
          metadata == other.metadata;

@override int get hashCode => Object.hash(role, content, Object.hashAll(attachments ?? const []), metadata);

@override String toString() => 'CreateMessageRequest(role: $role, content: $content, attachments: $attachments, metadata: $metadata)';

 }
