// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/CustomToolCallOutput

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/custom_tool_call_output/custom_tool_call_output_output.dart';import 'package:pub_openai/models/function_and_custom_tool_call_output.dart';/// The output of a custom tool call from your code, being sent back to the model.
/// 
@immutable final class CustomToolCallOutput {const CustomToolCallOutput({required this.type, required this.callId, required this.output, this.id, });

factory CustomToolCallOutput.fromJson(Map<String, dynamic> json) { return CustomToolCallOutput(
  type: json['type'] as String,
  id: json['id'] as String?,
  callId: json['call_id'] as String,
  output: OneOf2.parse(json['output'], fromA: (v) => v as String, fromB: (v) => (v as List<dynamic>).map((e) => FunctionAndCustomToolCallOutput.fromJson(e as Map<String, dynamic>)).toList(),),
); }

/// The type of the custom tool call output. Always `custom_tool_call_output`.
/// 
final String type;

/// The unique ID of the custom tool call output in the OpenAI platform.
/// 
final String? id;

/// The call ID, used to map this custom tool call output to a custom tool call.
/// 
final String callId;

/// The output from the custom tool call generated by your code.
/// Can be a string or an list of output content.
/// 
final CustomToolCallOutputOutput output;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': ?id,
  'call_id': callId,
  'output': output.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('output'); } 
CustomToolCallOutput copyWith({String? type, String? Function()? id, String? callId, CustomToolCallOutputOutput? output, }) { return CustomToolCallOutput(
  type: type ?? this.type,
  id: id != null ? id() : this.id,
  callId: callId ?? this.callId,
  output: output ?? this.output,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is CustomToolCallOutput &&
          type == other.type &&
          id == other.id &&
          callId == other.callId &&
          output == other.output;

@override int get hashCode => Object.hash(type, id, callId, output);

@override String toString() => 'CustomToolCallOutput(type: $type, id: $id, callId: $callId, output: $output)';

 }
