// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/easy_input_message/easy_input_message_content.dart';import 'package:pub_openai/models/easy_input_message/easy_input_message_role.dart';import 'package:pub_openai/models/input_content.dart';import 'package:pub_openai/models/message_phase.dart';/// A message input to the model with a role indicating instruction following
/// hierarchy. Instructions given with the `developer` or `system` role take
/// precedence over instructions given with the `user` role. Messages with the
/// `assistant` role are presumed to have been generated by the model in previous
/// interactions.
/// 
@immutable final class EasyInputMessage {const EasyInputMessage({required this.role, required this.content, this.phase, this.type, });

factory EasyInputMessage.fromJson(Map<String, dynamic> json) { return EasyInputMessage(
  role: EasyInputMessageRole.fromJson(json['role'] as String),
  content: OneOf2.parse(json['content'], fromA: (v) => v as String, fromB: (v) => (v as List<dynamic>).map((e) => InputContent.fromJson(e as Map<String, dynamic>)).toList(),),
  phase: json['phase'] != null ? MessagePhase.fromJson(json['phase'] as String) : null,
  type: json['type'] as String?,
); }

/// The role of the message input. One of `user`, `assistant`, `system`, or
/// `developer`.
/// 
final EasyInputMessageRole role;

/// Text, image, or audio input to the model, used to generate a response.
/// Can also contain previous assistant responses.
/// 
final EasyInputMessageContent content;

final MessagePhase? phase;

/// The type of the message input. Always `message`.
/// 
final String? type;

Map<String, dynamic> toJson() { return {
  'role': role.toJson(),
  'content': content.toJson(),
  if (phase != null) 'phase': phase?.toJson(),
  'type': ?type,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('role') &&
      json.containsKey('content'); } 
EasyInputMessage copyWith({EasyInputMessageRole? role, EasyInputMessageContent? content, MessagePhase? Function()? phase, String? Function()? type, }) { return EasyInputMessage(
  role: role ?? this.role,
  content: content ?? this.content,
  phase: phase != null ? phase() : this.phase,
  type: type != null ? type() : this.type,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is EasyInputMessage &&
          role == other.role &&
          content == other.content &&
          phase == other.phase &&
          type == other.type;

@override int get hashCode => Object.hash(role, content, phase, type);

@override String toString() => 'EasyInputMessage(role: $role, content: $content, phase: $phase, type: $type)';

 }
