// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/chat_completion_message_tool_calls2.dart';import 'package:pub_openai/models/chat_completion_request_assistant_message/chat_completion_request_assistant_message_audio.dart';import 'package:pub_openai/models/chat_completion_request_assistant_message/chat_completion_request_assistant_message_content.dart';import 'package:pub_openai/models/chat_completion_request_assistant_message/chat_completion_request_assistant_message_function_call.dart';import 'package:pub_openai/models/chat_completion_request_assistant_message_content_part.dart';import 'package:pub_openai/models/chat_completion_response_message/chat_completion_response_message_role.dart';/// Controls whether the assistant message is trained against (0 or 1)
@immutable final class Weight {const Weight._(this.value);

factory Weight.fromJson(int json) { return switch (json) {
  0 => $0,
  1 => $1,
  _ => Weight._(json),
}; }

static const Weight $0 = Weight._(0);

static const Weight $1 = Weight._(1);

static const List<Weight> values = [$0, $1];

final int value;

int toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is Weight && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'Weight($value)'; } 
 }
@immutable final class FineTuneChatCompletionRequestAssistantMessage {const FineTuneChatCompletionRequestAssistantMessage({required this.role, this.content, this.refusal, this.name, this.audio, this.toolCalls, this.functionCall, this.weight, });

factory FineTuneChatCompletionRequestAssistantMessage.fromJson(Map<String, dynamic> json) { return FineTuneChatCompletionRequestAssistantMessage(
  content: json['content'] != null ? OneOf2.parse(json['content'], fromA: (v) => v as String, fromB: (v) => (v as List<dynamic>).map((e) => ChatCompletionRequestAssistantMessageContentPart.fromJson(e as Map<String, dynamic>)).toList(),) : null,
  refusal: json['refusal'] as String?,
  role: ChatCompletionResponseMessageRole.fromJson(json['role'] as String),
  name: json['name'] as String?,
  audio: json['audio'] != null ? ChatCompletionRequestAssistantMessageAudio.fromJson(json['audio'] as Map<String, dynamic>) : null,
  toolCalls: (json['tool_calls'] as List<dynamic>?)?.map((e) => ChatCompletionMessageToolCalls2.fromJson(e as Map<String, dynamic>)).toList(),
  functionCall: json['function_call'] != null ? ChatCompletionRequestAssistantMessageFunctionCall.fromJson(json['function_call'] as Map<String, dynamic>) : null,
  weight: json['weight'] != null ? Weight.fromJson((json['weight'] as num).toInt()) : null,
); }

/// The contents of the assistant message. Required unless `tool_calls` or `function_call` is specified.
/// 
final ChatCompletionRequestAssistantMessageContent? content;

/// The refusal message by the assistant.
final String? refusal;

/// The role of the messages author, in this case `assistant`.
final ChatCompletionResponseMessageRole role;

/// An optional name for the participant. Provides the model information to differentiate between participants of the same role.
final String? name;

/// Data about a previous audio response from the model.
/// [Learn more](/docs/guides/audio).
/// 
final ChatCompletionRequestAssistantMessageAudio? audio;

/// The tool calls generated by the model, such as function calls.
final List<ChatCompletionMessageToolCalls2>? toolCalls;

/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
final ChatCompletionRequestAssistantMessageFunctionCall? functionCall;

/// Controls whether the assistant message is trained against (0 or 1)
final Weight? weight;

Map<String, dynamic> toJson() { return {
  if (content != null) 'content': content?.toJson(),
  'refusal': ?refusal,
  'role': role.toJson(),
  'name': ?name,
  if (audio != null) 'audio': audio?.toJson(),
  if (toolCalls != null) 'tool_calls': toolCalls?.map((e) => e.toJson()).toList(),
  if (functionCall != null) 'function_call': functionCall?.toJson(),
  if (weight != null) 'weight': weight?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('role'); } 
FineTuneChatCompletionRequestAssistantMessage copyWith({ChatCompletionRequestAssistantMessageContent? Function()? content, String? Function()? refusal, ChatCompletionResponseMessageRole? role, String Function()? name, ChatCompletionRequestAssistantMessageAudio? Function()? audio, List<ChatCompletionMessageToolCalls2> Function()? toolCalls, ChatCompletionRequestAssistantMessageFunctionCall? Function()? functionCall, Weight Function()? weight, }) { return FineTuneChatCompletionRequestAssistantMessage(
  content: content != null ? content() : this.content,
  refusal: refusal != null ? refusal() : this.refusal,
  role: role ?? this.role,
  name: name != null ? name() : this.name,
  audio: audio != null ? audio() : this.audio,
  toolCalls: toolCalls != null ? toolCalls() : this.toolCalls,
  functionCall: functionCall != null ? functionCall() : this.functionCall,
  weight: weight != null ? weight() : this.weight,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is FineTuneChatCompletionRequestAssistantMessage &&
          content == other.content &&
          refusal == other.refusal &&
          role == other.role &&
          name == other.name &&
          audio == other.audio &&
          listEquals(toolCalls, other.toolCalls) &&
          functionCall == other.functionCall &&
          weight == other.weight; } 
@override int get hashCode { return Object.hash(content, refusal, role, name, audio, Object.hashAll(toolCalls ?? const []), functionCall, weight); } 
@override String toString() { return 'FineTuneChatCompletionRequestAssistantMessage(content: $content, refusal: $refusal, role: $role, name: $name, audio: $audio, toolCalls: $toolCalls, functionCall: $functionCall, weight: $weight)'; } 
 }
