// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/computer_tool_call_output/computer_tool_call_output_status.dart';/// A tool call to run a function. See the
/// [function calling guide](/docs/guides/function-calling) for more information.
/// 
@immutable final class FunctionToolCall {const FunctionToolCall({required this.type, required this.callId, required this.name, required this.arguments, this.id, this.namespace, this.status, });

factory FunctionToolCall.fromJson(Map<String, dynamic> json) { return FunctionToolCall(
  id: json['id'] as String?,
  type: json['type'] as String,
  callId: json['call_id'] as String,
  namespace: json['namespace'] as String?,
  name: json['name'] as String,
  arguments: json['arguments'] as String,
  status: json['status'] != null ? ComputerToolCallOutputStatus.fromJson(json['status'] as String) : null,
); }

/// The unique ID of the function tool call.
/// 
final String? id;

/// The type of the function tool call. Always `function_call`.
/// 
final String type;

/// The unique ID of the function tool call generated by the model.
/// 
final String callId;

/// The namespace of the function to run.
/// 
final String? namespace;

/// The name of the function to run.
/// 
final String name;

/// A JSON string of the arguments to pass to the function.
/// 
final String arguments;

/// The status of the item. One of `in_progress`, `completed`, or
/// `incomplete`. Populated when items are returned via API.
/// 
final ComputerToolCallOutputStatus? status;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  'type': type,
  'call_id': callId,
  'namespace': ?namespace,
  'name': name,
  'arguments': arguments,
  if (status != null) 'status': status?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('name') && json['name'] is String &&
      json.containsKey('arguments') && json['arguments'] is String; } 
FunctionToolCall copyWith({String Function()? id, String? type, String? callId, String Function()? namespace, String? name, String? arguments, ComputerToolCallOutputStatus Function()? status, }) { return FunctionToolCall(
  id: id != null ? id() : this.id,
  type: type ?? this.type,
  callId: callId ?? this.callId,
  namespace: namespace != null ? namespace() : this.namespace,
  name: name ?? this.name,
  arguments: arguments ?? this.arguments,
  status: status != null ? status() : this.status,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is FunctionToolCall &&
          id == other.id &&
          type == other.type &&
          callId == other.callId &&
          namespace == other.namespace &&
          name == other.name &&
          arguments == other.arguments &&
          status == other.status; } 
@override int get hashCode { return Object.hash(id, type, callId, namespace, name, arguments, status); } 
@override String toString() { return 'FunctionToolCall(id: $id, type: $type, callId: $callId, namespace: $namespace, name: $name, arguments: $arguments, status: $status)'; } 
 }
