// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/FunctionShellCallOutput

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/function_shell_call_output_content.dart';@immutable final class LocalShellCallOutputStatusEnum {const LocalShellCallOutputStatusEnum._(this.value);

factory LocalShellCallOutputStatusEnum.fromJson(String json) { return switch (json) {
  'in_progress' => inProgress,
  'completed' => completed,
  'incomplete' => incomplete,
  _ => LocalShellCallOutputStatusEnum._(json),
}; }

static const LocalShellCallOutputStatusEnum inProgress = LocalShellCallOutputStatusEnum._('in_progress');

static const LocalShellCallOutputStatusEnum completed = LocalShellCallOutputStatusEnum._('completed');

static const LocalShellCallOutputStatusEnum incomplete = LocalShellCallOutputStatusEnum._('incomplete');

static const List<LocalShellCallOutputStatusEnum> values = [inProgress, completed, incomplete];

final String value;

String toJson() { return value; } 
/// The Dart identifier name for this value, or the raw value if unknown.
String get name { return switch (value) {
  'in_progress' => 'inProgress',
  'completed' => 'completed',
  'incomplete' => 'incomplete',
  _ => value,
}; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) => identical(this, other) ||
    other is LocalShellCallOutputStatusEnum && other.value == value;

@override int get hashCode => value.hashCode;

@override String toString() => 'LocalShellCallOutputStatusEnum($value)';

 }
/// The output of a shell tool call that was emitted.
@immutable final class FunctionShellCallOutput {const FunctionShellCallOutput({required this.id, required this.callId, required this.status, required this.output, required this.maxOutputLength, this.type = 'shell_call_output', this.createdBy, });

factory FunctionShellCallOutput.fromJson(Map<String, dynamic> json) { return FunctionShellCallOutput(
  type: json['type'] as String,
  id: json['id'] as String,
  callId: json['call_id'] as String,
  status: LocalShellCallOutputStatusEnum.fromJson(json['status'] as String),
  output: (json['output'] as List<dynamic>).map((e) => FunctionShellCallOutputContent.fromJson(e as Map<String, dynamic>)).toList(),
  maxOutputLength: json['max_output_length'] != null ? (json['max_output_length'] as num).toInt() : null,
  createdBy: json['created_by'] as String?,
); }

/// The type of the shell call output. Always `shell_call_output`.
final String type;

/// The unique ID of the shell call output. Populated when this item is returned via API.
final String id;

/// The unique ID of the shell tool call generated by the model.
final String callId;

/// The status of the shell call output. One of `in_progress`, `completed`, or `incomplete`.
final LocalShellCallOutputStatusEnum status;

/// An array of shell call output contents
final List<FunctionShellCallOutputContent> output;

/// The maximum length of the shell command output. This is generated by the model and should be passed back with the raw output.
final int? maxOutputLength;

/// The identifier of the actor that created the item.
final String? createdBy;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'call_id': callId,
  'status': status.toJson(),
  'output': output.map((e) => e.toJson()).toList(),
  'max_output_length': maxOutputLength,
  'created_by': ?createdBy,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('status') &&
      json.containsKey('output') &&
      json.containsKey('max_output_length') && json['max_output_length'] is num; } 
FunctionShellCallOutput copyWith({String? type, String? id, String? callId, LocalShellCallOutputStatusEnum? status, List<FunctionShellCallOutputContent>? output, int? Function()? maxOutputLength, String? Function()? createdBy, }) { return FunctionShellCallOutput(
  type: type ?? this.type,
  id: id ?? this.id,
  callId: callId ?? this.callId,
  status: status ?? this.status,
  output: output ?? this.output,
  maxOutputLength: maxOutputLength != null ? maxOutputLength() : this.maxOutputLength,
  createdBy: createdBy != null ? createdBy() : this.createdBy,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is FunctionShellCallOutput &&
          type == other.type &&
          id == other.id &&
          callId == other.callId &&
          status == other.status &&
          listEquals(output, other.output) &&
          maxOutputLength == other.maxOutputLength &&
          createdBy == other.createdBy;

@override int get hashCode => Object.hash(type, id, callId, status, Object.hashAll(output), maxOutputLength, createdBy);

@override String toString() => 'FunctionShellCallOutput(type: $type, id: $id, callId: $callId, status: $status, output: $output, maxOutputLength: $maxOutputLength, createdBy: $createdBy)';

 }
