// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/function_shell_call_item_status.dart';import 'package:pub_openai/models/function_shell_call_output_content_param.dart';/// The streamed output items emitted by a shell tool call.
@immutable final class FunctionShellCallOutputItemParam {const FunctionShellCallOutputItemParam({required this.callId, required this.output, this.id, this.type = 'shell_call_output', this.status, this.maxOutputLength, });

factory FunctionShellCallOutputItemParam.fromJson(Map<String, dynamic> json) { return FunctionShellCallOutputItemParam(
  id: json['id'] as String?,
  callId: json['call_id'] as String,
  type: json['type'] as String,
  output: (json['output'] as List<dynamic>).map((e) => FunctionShellCallOutputContentParam.fromJson(e as Map<String, dynamic>)).toList(),
  status: json['status'] != null ? FunctionShellCallItemStatus.fromJson(json['status'] as String) : null,
  maxOutputLength: json['max_output_length'] != null ? (json['max_output_length'] as num).toInt() : null,
); }

/// The unique ID of the shell tool call output. Populated when this item is returned via API.
final String? id;

/// The unique ID of the shell tool call generated by the model.
final String callId;

/// The type of the item. Always `shell_call_output`.
final String type;

/// Captured chunks of stdout and stderr output, along with their associated outcomes.
final List<FunctionShellCallOutputContentParam> output;

/// Status values reported for shell tool calls.
final FunctionShellCallItemStatus? status;

/// The maximum number of UTF-8 characters captured for this shell call's combined output.
final int? maxOutputLength;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  'call_id': callId,
  'type': type,
  'output': output.map((e) => e.toJson()).toList(),
  if (status != null) 'status': status?.toJson(),
  'max_output_length': ?maxOutputLength,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('type') && json['type'] is String &&
      json.containsKey('output'); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
if (callId.isEmpty) { errors.add('callId: length must be >= 1'); }
if (callId.length > 64) { errors.add('callId: length must be <= 64'); }
return errors; } 
FunctionShellCallOutputItemParam copyWith({String? Function()? id, String? callId, String? type, List<FunctionShellCallOutputContentParam>? output, FunctionShellCallItemStatus? Function()? status, int? Function()? maxOutputLength, }) { return FunctionShellCallOutputItemParam(
  id: id != null ? id() : this.id,
  callId: callId ?? this.callId,
  type: type ?? this.type,
  output: output ?? this.output,
  status: status != null ? status() : this.status,
  maxOutputLength: maxOutputLength != null ? maxOutputLength() : this.maxOutputLength,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is FunctionShellCallOutputItemParam &&
          id == other.id &&
          callId == other.callId &&
          type == other.type &&
          listEquals(output, other.output) &&
          status == other.status &&
          maxOutputLength == other.maxOutputLength;

@override int get hashCode => Object.hash(id, callId, type, Object.hashAll(output), status, maxOutputLength);

@override String toString() => 'FunctionShellCallOutputItemParam(id: $id, callId: $callId, type: $type, output: $output, status: $status, maxOutputLength: $maxOutputLength)';

 }
