// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/FunctionShellCallItemParam

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/function_shell_action_param.dart';import 'package:pub_openai/models/function_shell_call_item_param/function_shell_call_item_param_environment.dart';import 'package:pub_openai/models/function_shell_call_item_status.dart';/// A tool representing a request to execute one or more shell commands.
@immutable final class FunctionShellCallItemParam {const FunctionShellCallItemParam({required this.callId, required this.action, this.id, this.type = 'shell_call', this.status, this.environment, });

factory FunctionShellCallItemParam.fromJson(Map<String, dynamic> json) { return FunctionShellCallItemParam(
  id: json['id'] as String?,
  callId: json['call_id'] as String,
  type: json['type'] as String,
  action: FunctionShellActionParam.fromJson(json['action'] as Map<String, dynamic>),
  status: json['status'] != null ? FunctionShellCallItemStatus.fromJson(json['status'] as String) : null,
  environment: json['environment'] != null ? FunctionShellCallItemParamEnvironment.fromJson(json['environment'] as Map<String, dynamic>) : null,
); }

/// The unique ID of the shell tool call. Populated when this item is returned via API.
final String? id;

/// The unique ID of the shell tool call generated by the model.
final String callId;

/// The type of the item. Always `shell_call`.
final String type;

/// The shell commands and limits that describe how to run the tool call.
final FunctionShellActionParam action;

/// Status values reported for shell tool calls.
final FunctionShellCallItemStatus? status;

/// The environment to execute the shell commands in.
final FunctionShellCallItemParamEnvironment? environment;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  'call_id': callId,
  'type': type,
  'action': action.toJson(),
  if (status != null) 'status': status?.toJson(),
  if (environment != null) 'environment': environment?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('type') && json['type'] is String &&
      json.containsKey('action'); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
if (callId.isEmpty) { errors.add('callId: length must be >= 1'); }
if (callId.length > 64) { errors.add('callId: length must be <= 64'); }
return errors; } 
FunctionShellCallItemParam copyWith({String? Function()? id, String? callId, String? type, FunctionShellActionParam? action, FunctionShellCallItemStatus? Function()? status, FunctionShellCallItemParamEnvironment? Function()? environment, }) { return FunctionShellCallItemParam(
  id: id != null ? id() : this.id,
  callId: callId ?? this.callId,
  type: type ?? this.type,
  action: action ?? this.action,
  status: status != null ? status() : this.status,
  environment: environment != null ? environment() : this.environment,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is FunctionShellCallItemParam &&
          id == other.id &&
          callId == other.callId &&
          type == other.type &&
          action == other.action &&
          status == other.status &&
          environment == other.environment;

@override int get hashCode => Object.hash(id, callId, type, action, status, environment);

@override String toString() => 'FunctionShellCallItemParam(id: $id, callId: $callId, type: $type, action: $action, status: $status, environment: $environment)';

 }
