// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/FunctionToolCallOutput

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/computer_tool_call_output/computer_tool_call_output_status.dart';import 'package:pub_openai/models/custom_tool_call_output/custom_tool_call_output_output.dart';import 'package:pub_openai/models/function_and_custom_tool_call_output.dart';/// The output of a function tool call.
/// 
@immutable final class FunctionToolCallOutput {const FunctionToolCallOutput({required this.type, required this.callId, required this.output, this.id, this.status, });

factory FunctionToolCallOutput.fromJson(Map<String, dynamic> json) { return FunctionToolCallOutput(
  id: json['id'] as String?,
  type: json['type'] as String,
  callId: json['call_id'] as String,
  output: OneOf2.parse(json['output'], fromA: (v) => v as String, fromB: (v) => (v as List<dynamic>).map((e) => FunctionAndCustomToolCallOutput.fromJson(e as Map<String, dynamic>)).toList(),),
  status: json['status'] != null ? ComputerToolCallOutputStatus.fromJson(json['status'] as String) : null,
); }

/// The unique ID of the function tool call output. Populated when this item
/// is returned via API.
/// 
final String? id;

/// The type of the function tool call output. Always `function_call_output`.
/// 
final String type;

/// The unique ID of the function tool call generated by the model.
/// 
final String callId;

/// The output from the function call generated by your code.
/// Can be a string or an list of output content.
/// 
final CustomToolCallOutputOutput output;

/// The status of the item. One of `in_progress`, `completed`, or
/// `incomplete`. Populated when items are returned via API.
/// 
final ComputerToolCallOutputStatus? status;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  'type': type,
  'call_id': callId,
  'output': output.toJson(),
  if (status != null) 'status': status?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('output'); } 
FunctionToolCallOutput copyWith({String? Function()? id, String? type, String? callId, CustomToolCallOutputOutput? output, ComputerToolCallOutputStatus? Function()? status, }) { return FunctionToolCallOutput(
  id: id != null ? id() : this.id,
  type: type ?? this.type,
  callId: callId ?? this.callId,
  output: output ?? this.output,
  status: status != null ? status() : this.status,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is FunctionToolCallOutput &&
          id == other.id &&
          type == other.type &&
          callId == other.callId &&
          output == other.output &&
          status == other.status;

@override int get hashCode => Object.hash(id, type, callId, output, status);

@override String toString() => 'FunctionToolCallOutput(id: $id, type: $type, callId: $callId, output: $output, status: $status)';

 }
