// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/function_shell_action.dart';import 'package:pub_openai/models/function_shell_call/function_shell_call_environment.dart';@immutable final class LocalShellCallStatus {const LocalShellCallStatus._(this.value);

factory LocalShellCallStatus.fromJson(String json) { return switch (json) {
  'in_progress' => inProgress,
  'completed' => completed,
  'incomplete' => incomplete,
  _ => LocalShellCallStatus._(json),
}; }

static const LocalShellCallStatus inProgress = LocalShellCallStatus._('in_progress');

static const LocalShellCallStatus completed = LocalShellCallStatus._('completed');

static const LocalShellCallStatus incomplete = LocalShellCallStatus._('incomplete');

static const List<LocalShellCallStatus> values = [inProgress, completed, incomplete];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is LocalShellCallStatus && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'LocalShellCallStatus($value)'; } 
 }
/// A tool call that executes one or more shell commands in a managed environment.
@immutable final class FunctionShellCall {const FunctionShellCall({required this.id, required this.callId, required this.action, required this.status, required this.environment, this.type = 'shell_call', this.createdBy, });

factory FunctionShellCall.fromJson(Map<String, dynamic> json) { return FunctionShellCall(
  type: json['type'] as String,
  id: json['id'] as String,
  callId: json['call_id'] as String,
  action: FunctionShellAction.fromJson(json['action'] as Map<String, dynamic>),
  status: LocalShellCallStatus.fromJson(json['status'] as String),
  environment: json['environment'] != null ? FunctionShellCallEnvironment.fromJson(json['environment'] as Map<String, dynamic>) : null,
  createdBy: json['created_by'] as String?,
); }

/// The type of the item. Always `shell_call`.
final String type;

/// The unique ID of the shell tool call. Populated when this item is returned via API.
final String id;

/// The unique ID of the shell tool call generated by the model.
final String callId;

/// The shell commands and limits that describe how to run the tool call.
final FunctionShellAction action;

/// The status of the shell call. One of `in_progress`, `completed`, or `incomplete`.
final LocalShellCallStatus status;

final FunctionShellCallEnvironment? environment;

/// The ID of the entity that created this tool call.
final String? createdBy;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'call_id': callId,
  'action': action.toJson(),
  'status': status.toJson(),
  'environment': environment != null ? environment?.toJson() : null,
  'created_by': ?createdBy,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('action') &&
      json.containsKey('status') &&
      json.containsKey('environment'); } 
FunctionShellCall copyWith({String? type, String? id, String? callId, FunctionShellAction? action, LocalShellCallStatus? status, FunctionShellCallEnvironment? Function()? environment, String? Function()? createdBy, }) { return FunctionShellCall(
  type: type ?? this.type,
  id: id ?? this.id,
  callId: callId ?? this.callId,
  action: action ?? this.action,
  status: status ?? this.status,
  environment: environment != null ? environment() : this.environment,
  createdBy: createdBy != null ? createdBy() : this.createdBy,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is FunctionShellCall &&
          type == other.type &&
          id == other.id &&
          callId == other.callId &&
          action == other.action &&
          status == other.status &&
          environment == other.environment &&
          createdBy == other.createdBy; } 
@override int get hashCode { return Object.hash(type, id, callId, action, status, environment, createdBy); } 
@override String toString() { return 'FunctionShellCall(type: $type, id: $id, callId: $callId, action: $action, status: $status, environment: $environment, createdBy: $createdBy)'; } 
 }
