// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// The output token details for the image generation.
@immutable final class ImageGenOutputTokensDetails {const ImageGenOutputTokensDetails({required this.imageTokens, required this.textTokens, });

factory ImageGenOutputTokensDetails.fromJson(Map<String, dynamic> json) { return ImageGenOutputTokensDetails(
  imageTokens: (json['image_tokens'] as num).toInt(),
  textTokens: (json['text_tokens'] as num).toInt(),
); }

/// The number of image output tokens generated by the model.
final int imageTokens;

/// The number of text output tokens generated by the model.
final int textTokens;

Map<String, dynamic> toJson() { return {
  'image_tokens': imageTokens,
  'text_tokens': textTokens,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('image_tokens') && json['image_tokens'] is num &&
      json.containsKey('text_tokens') && json['text_tokens'] is num; } 
ImageGenOutputTokensDetails copyWith({int? imageTokens, int? textTokens, }) { return ImageGenOutputTokensDetails(
  imageTokens: imageTokens ?? this.imageTokens,
  textTokens: textTokens ?? this.textTokens,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is ImageGenOutputTokensDetails &&
          imageTokens == other.imageTokens &&
          textTokens == other.textTokens;

@override int get hashCode => Object.hash(imageTokens, textTokens);

@override String toString() => 'ImageGenOutputTokensDetails(imageTokens: $imageTokens, textTokens: $textTokens)';

 }
