// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// Represents the content or the URL of an image generated by the OpenAI API.
@immutable final class Image {const Image({this.b64Json, this.url, this.revisedPrompt, });

factory Image.fromJson(Map<String, dynamic> json) { return Image(
  b64Json: json['b64_json'] as String?,
  url: json['url'] as String?,
  revisedPrompt: json['revised_prompt'] as String?,
); }

/// The base64-encoded JSON of the generated image. Returned by default for the GPT image models, and only present if `response_format` is set to `b64_json` for `dall-e-2` and `dall-e-3`.
final String? b64Json;

/// When using `dall-e-2` or `dall-e-3`, the URL of the generated image if `response_format` is set to `url` (default value). Unsupported for the GPT image models.
final String? url;

/// For `dall-e-3` only, the revised prompt that was used to generate the image.
final String? revisedPrompt;

Map<String, dynamic> toJson() { return {
  'b64_json': ?b64Json,
  'url': ?url,
  'revised_prompt': ?revisedPrompt,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'b64_json', 'url', 'revised_prompt'}.contains(key)); } 
Image copyWith({String? Function()? b64Json, String? Function()? url, String? Function()? revisedPrompt, }) { return Image(
  b64Json: b64Json != null ? b64Json() : this.b64Json,
  url: url != null ? url() : this.url,
  revisedPrompt: revisedPrompt != null ? revisedPrompt() : this.revisedPrompt,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is Image &&
          b64Json == other.b64Json &&
          url == other.url &&
          revisedPrompt == other.revisedPrompt; } 
@override int get hashCode { return Object.hash(b64Json, url, revisedPrompt); } 
@override String toString() { return 'Image(b64Json: $b64Json, url: $url, revisedPrompt: $revisedPrompt)'; } 
 }
