// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/LocalShellToolCallOutput

import 'package:degenerate_runtime/degenerate_runtime.dart';/// The status of the item. One of `in_progress`, `completed`, or `incomplete`.
/// 
sealed class LocalShellToolCallOutputStatus {const LocalShellToolCallOutputStatus();

factory LocalShellToolCallOutputStatus.fromJson(String json) { return switch (json) {
  'in_progress' => inProgress,
  'completed' => completed,
  'incomplete' => incomplete,
  _ => LocalShellToolCallOutputStatus$Unknown(json),
}; }

static const LocalShellToolCallOutputStatus inProgress = LocalShellToolCallOutputStatus$inProgress._();

static const LocalShellToolCallOutputStatus completed = LocalShellToolCallOutputStatus$completed._();

static const LocalShellToolCallOutputStatus incomplete = LocalShellToolCallOutputStatus$incomplete._();

static const List<LocalShellToolCallOutputStatus> values = [inProgress, completed, incomplete];

String get value;
String toJson() { return value; } 
/// The Dart identifier name for this value, or the raw value if unknown.
String get name { return switch (value) {
  'in_progress' => 'inProgress',
  'completed' => 'completed',
  'incomplete' => 'incomplete',
  _ => value,
}; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return this is LocalShellToolCallOutputStatus$Unknown; } 
@override String toString() => 'LocalShellToolCallOutputStatus($value)';

 }
@immutable final class LocalShellToolCallOutputStatus$inProgress extends LocalShellToolCallOutputStatus {const LocalShellToolCallOutputStatus$inProgress._();

@override String get value => 'in_progress';

@override bool operator ==(Object other) => identical(this, other) || other is LocalShellToolCallOutputStatus$inProgress;

@override int get hashCode => 'in_progress'.hashCode;

 }
@immutable final class LocalShellToolCallOutputStatus$completed extends LocalShellToolCallOutputStatus {const LocalShellToolCallOutputStatus$completed._();

@override String get value => 'completed';

@override bool operator ==(Object other) => identical(this, other) || other is LocalShellToolCallOutputStatus$completed;

@override int get hashCode => 'completed'.hashCode;

 }
@immutable final class LocalShellToolCallOutputStatus$incomplete extends LocalShellToolCallOutputStatus {const LocalShellToolCallOutputStatus$incomplete._();

@override String get value => 'incomplete';

@override bool operator ==(Object other) => identical(this, other) || other is LocalShellToolCallOutputStatus$incomplete;

@override int get hashCode => 'incomplete'.hashCode;

 }
@immutable final class LocalShellToolCallOutputStatus$Unknown extends LocalShellToolCallOutputStatus {const LocalShellToolCallOutputStatus$Unknown(this.value);

@override final String value;

@override bool operator ==(Object other) => identical(this, other) ||
    other is LocalShellToolCallOutputStatus$Unknown && other.value == value;

@override int get hashCode => value.hashCode;

 }
/// The output of a local shell tool call.
/// 
@immutable final class LocalShellToolCallOutput {const LocalShellToolCallOutput({required this.type, required this.id, required this.output, this.status, });

factory LocalShellToolCallOutput.fromJson(Map<String, dynamic> json) { return LocalShellToolCallOutput(
  type: json['type'] as String,
  id: json['id'] as String,
  output: json['output'] as String,
  status: json['status'] != null ? LocalShellToolCallOutputStatus.fromJson(json['status'] as String) : null,
); }

/// The type of the local shell tool call output. Always `local_shell_call_output`.
/// 
final String type;

/// The unique ID of the local shell tool call generated by the model.
/// 
final String id;

/// A JSON string of the output of the local shell tool call.
/// 
final String output;

/// The status of the item. One of `in_progress`, `completed`, or `incomplete`.
/// 
final LocalShellToolCallOutputStatus? status;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'output': output,
  if (status != null) 'status': status?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('output') && json['output'] is String; } 
LocalShellToolCallOutput copyWith({String? type, String? id, String? output, LocalShellToolCallOutputStatus? Function()? status, }) { return LocalShellToolCallOutput(
  type: type ?? this.type,
  id: id ?? this.id,
  output: output ?? this.output,
  status: status != null ? status() : this.status,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is LocalShellToolCallOutput &&
          type == other.type &&
          id == other.id &&
          output == other.output &&
          status == other.status;

@override int get hashCode => Object.hash(type, id, output, status);

@override String toString() => 'LocalShellToolCallOutput(type: $type, id: $id, output: $output, status: $status)';

 }
