// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/computer_tool_call_output/computer_tool_call_output_status.dart';import 'package:pub_openai/models/local_shell_exec_action.dart';/// A tool call to run a command on the local shell.
/// 
@immutable final class LocalShellToolCall {const LocalShellToolCall({required this.type, required this.id, required this.callId, required this.action, required this.status, });

factory LocalShellToolCall.fromJson(Map<String, dynamic> json) { return LocalShellToolCall(
  type: json['type'] as String,
  id: json['id'] as String,
  callId: json['call_id'] as String,
  action: LocalShellExecAction.fromJson(json['action'] as Map<String, dynamic>),
  status: ComputerToolCallOutputStatus.fromJson(json['status'] as String),
); }

/// The type of the local shell call. Always `local_shell_call`.
/// 
final String type;

/// The unique ID of the local shell call.
/// 
final String id;

/// The unique ID of the local shell tool call generated by the model.
/// 
final String callId;

final LocalShellExecAction action;

/// The status of the local shell call.
/// 
final ComputerToolCallOutputStatus status;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'call_id': callId,
  'action': action.toJson(),
  'status': status.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('action') &&
      json.containsKey('status'); } 
LocalShellToolCall copyWith({String? type, String? id, String? callId, LocalShellExecAction? action, ComputerToolCallOutputStatus? status, }) { return LocalShellToolCall(
  type: type ?? this.type,
  id: id ?? this.id,
  callId: callId ?? this.callId,
  action: action ?? this.action,
  status: status ?? this.status,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is LocalShellToolCall &&
          type == other.type &&
          id == other.id &&
          callId == other.callId &&
          action == other.action &&
          status == other.status;

@override int get hashCode => Object.hash(type, id, callId, action, status);

@override String toString() => 'LocalShellToolCall(type: $type, id: $id, callId: $callId, action: $action, status: $status)';

 }
