// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/MessageContentRefusalObject

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/message_content_refusal_object/message_content_refusal_object_type.dart';/// The refusal content generated by the assistant.
@immutable final class MessageContentRefusalObject {const MessageContentRefusalObject({required this.type, required this.refusal, });

factory MessageContentRefusalObject.fromJson(Map<String, dynamic> json) { return MessageContentRefusalObject(
  type: MessageContentRefusalObjectType.fromJson(json['type'] as String),
  refusal: json['refusal'] as String,
); }

/// Always `refusal`.
final MessageContentRefusalObjectType type;

final String refusal;

Map<String, dynamic> toJson() { return {
  'type': type.toJson(),
  'refusal': refusal,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') &&
      json.containsKey('refusal') && json['refusal'] is String; } 
MessageContentRefusalObject copyWith({MessageContentRefusalObjectType? type, String? refusal, }) { return MessageContentRefusalObject(
  type: type ?? this.type,
  refusal: refusal ?? this.refusal,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is MessageContentRefusalObject &&
          type == other.type &&
          refusal == other.refusal;

@override int get hashCode => Object.hash(type, refusal);

@override String toString() => 'MessageContentRefusalObject(type: $type, refusal: $refusal)';

 }
