// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/RealtimeConversationItemMessageUser

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/computer_tool_call_output/computer_tool_call_output_status.dart';import 'package:pub_openai/models/realtime_conversation_item_function_call/realtime_conversation_item_function_call_object.dart';import 'package:pub_openai/models/realtime_conversation_item_message_user/realtime_conversation_item_message_user_content.dart';/// The role of the message sender. Always `user`.
sealed class RealtimeConversationItemMessageUserRole {const RealtimeConversationItemMessageUserRole();

factory RealtimeConversationItemMessageUserRole.fromJson(String json) { return switch (json) {
  'user' => user,
  _ => RealtimeConversationItemMessageUserRole$Unknown(json),
}; }

static const RealtimeConversationItemMessageUserRole user = RealtimeConversationItemMessageUserRole$user._();

static const List<RealtimeConversationItemMessageUserRole> values = [user];

String get value;
String toJson() { return value; } 
/// The Dart identifier name for this value, or the raw value if unknown.
String get name { return switch (value) {
  'user' => 'user',
  _ => value,
}; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return this is RealtimeConversationItemMessageUserRole$Unknown; } 
/// Exhaustive match on the enum value.
W when<W>({required W Function() user, required W Function(String value) $unknown, }) { return switch (this) {
      RealtimeConversationItemMessageUserRole$user() => user(),
      RealtimeConversationItemMessageUserRole$Unknown(:final value) => $unknown(value),
    }; } 
/// Partial match with a required fallback for unhandled variants.
W maybeWhen<W>({required W Function(String value) orElse, W Function()? user, W Function(String value)? $unknown, }) { return switch (this) {
      RealtimeConversationItemMessageUserRole$user() => user != null ? user() : orElse(value),
      RealtimeConversationItemMessageUserRole$Unknown(:final value) => $unknown != null ? $unknown(value) : orElse(value),
    }; } 
@override String toString() => 'RealtimeConversationItemMessageUserRole($value)';

 }
@immutable final class RealtimeConversationItemMessageUserRole$user extends RealtimeConversationItemMessageUserRole {const RealtimeConversationItemMessageUserRole$user._();

@override String get value => 'user';

@override bool operator ==(Object other) => identical(this, other) || other is RealtimeConversationItemMessageUserRole$user;

@override int get hashCode => 'user'.hashCode;

 }
@immutable final class RealtimeConversationItemMessageUserRole$Unknown extends RealtimeConversationItemMessageUserRole {const RealtimeConversationItemMessageUserRole$Unknown(this.value);

@override final String value;

@override bool operator ==(Object other) => identical(this, other) ||
    other is RealtimeConversationItemMessageUserRole$Unknown && other.value == value;

@override int get hashCode => value.hashCode;

 }
/// A user message item in a Realtime conversation.
@immutable final class RealtimeConversationItemMessageUser {const RealtimeConversationItemMessageUser({required this.type, required this.role, required this.content, this.id, this.object, this.status, });

factory RealtimeConversationItemMessageUser.fromJson(Map<String, dynamic> json) { return RealtimeConversationItemMessageUser(
  id: json['id'] as String?,
  object: json['object'] != null ? RealtimeConversationItemFunctionCallObject.fromJson(json['object'] as String) : null,
  type: json['type'] as String,
  status: json['status'] != null ? ComputerToolCallOutputStatus.fromJson(json['status'] as String) : null,
  role: RealtimeConversationItemMessageUserRole.fromJson(json['role'] as String),
  content: (json['content'] as List<dynamic>).map((e) => RealtimeConversationItemMessageUserContent.fromJson(e as Map<String, dynamic>)).toList(),
); }

/// The unique ID of the item. This may be provided by the client or generated by the server.
final String? id;

/// Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item.
final RealtimeConversationItemFunctionCallObject? object;

/// The type of the item. Always `message`.
final String type;

/// The status of the item. Has no effect on the conversation.
final ComputerToolCallOutputStatus? status;

/// The role of the message sender. Always `user`.
final RealtimeConversationItemMessageUserRole role;

/// The content of the message.
final List<RealtimeConversationItemMessageUserContent> content;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  if (object != null) 'object': object?.toJson(),
  'type': type,
  if (status != null) 'status': status?.toJson(),
  'role': role.toJson(),
  'content': content.map((e) => e.toJson()).toList(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('role') &&
      json.containsKey('content'); } 
RealtimeConversationItemMessageUser copyWith({String? Function()? id, RealtimeConversationItemFunctionCallObject? Function()? object, String? type, ComputerToolCallOutputStatus? Function()? status, RealtimeConversationItemMessageUserRole? role, List<RealtimeConversationItemMessageUserContent>? content, }) { return RealtimeConversationItemMessageUser(
  id: id != null ? id() : this.id,
  object: object != null ? object() : this.object,
  type: type ?? this.type,
  status: status != null ? status() : this.status,
  role: role ?? this.role,
  content: content ?? this.content,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is RealtimeConversationItemMessageUser &&
          id == other.id &&
          object == other.object &&
          type == other.type &&
          status == other.status &&
          role == other.role &&
          listEquals(content, other.content);

@override int get hashCode => Object.hash(id, object, type, status, role, Object.hashAll(content));

@override String toString() => 'RealtimeConversationItemMessageUser(id: $id, object: $object, type: $type, status: $status, role: $role, content: $content)';

 }
