// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/realtime_beta_response/realtime_beta_response_object.dart';import 'package:pub_openai/models/realtime_beta_response/realtime_beta_response_status.dart';import 'package:pub_openai/models/realtime_beta_response/realtime_beta_response_usage.dart';import 'package:pub_openai/models/realtime_beta_response/status_details.dart';import 'package:pub_openai/models/realtime_beta_response_create_params/max_output_tokens.dart';import 'package:pub_openai/models/realtime_beta_response_create_params/max_output_tokens_variant2.dart';import 'package:pub_openai/models/realtime_conversation_item.dart';import 'package:pub_openai/models/realtime_response/realtime_response_audio.dart';import 'package:pub_openai/models/realtime_response_create_params/output_modalities.dart';/// The response resource.
@immutable final class RealtimeResponse {const RealtimeResponse({this.id, this.object, this.status, this.statusDetails, this.output, this.metadata, this.audio, this.usage, this.conversationId, this.outputModalities, this.maxOutputTokens, });

factory RealtimeResponse.fromJson(Map<String, dynamic> json) { return RealtimeResponse(
  id: json['id'] as String?,
  object: json['object'] != null ? RealtimeBetaResponseObject.fromJson(json['object'] as String) : null,
  status: json['status'] != null ? RealtimeBetaResponseStatus.fromJson(json['status'] as String) : null,
  statusDetails: json['status_details'] != null ? StatusDetails.fromJson(json['status_details'] as Map<String, dynamic>) : null,
  output: (json['output'] as List<dynamic>?)?.map((e) => RealtimeConversationItem.fromJson(e as Map<String, dynamic>)).toList(),
  metadata: (json['metadata'] as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, v as String)),
  audio: json['audio'] != null ? RealtimeResponseAudio.fromJson(json['audio'] as Map<String, dynamic>) : null,
  usage: json['usage'] != null ? RealtimeBetaResponseUsage.fromJson(json['usage'] as Map<String, dynamic>) : null,
  conversationId: json['conversation_id'] as String?,
  outputModalities: (json['output_modalities'] as List<dynamic>?)?.map((e) => OutputModalities.fromJson(e as String)).toList(),
  maxOutputTokens: json['max_output_tokens'] != null ? OneOf2.parse(json['max_output_tokens'], fromA: (v) => (v as num).toInt(), fromB: (v) => MaxOutputTokensVariant2.fromJson(v as String),) : null,
); }

/// The unique ID of the response, will look like `resp_1234`.
final String? id;

/// The object type, must be `realtime.response`.
final RealtimeBetaResponseObject? object;

/// The final status of the response (`completed`, `cancelled`, `failed`, or
/// `incomplete`, `in_progress`).
/// 
final RealtimeBetaResponseStatus? status;

/// Additional details about the status.
final StatusDetails? statusDetails;

/// The list of output items generated by the response.
final List<RealtimeConversationItem>? output;

/// Set of 16 key-value pairs that can be attached to an object. This can be
/// useful for storing additional information about the object in a structured
/// format, and querying for objects via API or the dashboard.
/// 
/// Keys are strings with a maximum length of 64 characters. Values are strings
/// with a maximum length of 512 characters.
/// 
final Map<String,String>? metadata;

/// Configuration for audio output.
final RealtimeResponseAudio? audio;

/// Usage statistics for the Response, this will correspond to billing. A
/// Realtime API session will maintain a conversation context and append new
/// Items to the Conversation, thus output from previous turns (text and
/// audio tokens) will become the input for later turns.
/// 
final RealtimeBetaResponseUsage? usage;

/// Which conversation the response is added to, determined by the `conversation`
/// field in the `response.create` event. If `auto`, the response will be added to
/// the default conversation and the value of `conversation_id` will be an id like
/// `conv_1234`. If `none`, the response will not be added to any conversation and
/// the value of `conversation_id` will be `null`. If responses are being triggered
/// automatically by VAD the response will be added to the default conversation
/// 
final String? conversationId;

/// The set of modalities the model used to respond, currently the only possible values are
/// `[\"audio\"]`, `[\"text\"]`. Audio output always include a text transcript. Setting the
/// output to mode `text` will disable audio output from the model.
/// 
final List<OutputModalities>? outputModalities;

/// Maximum number of output tokens for a single assistant response,
/// inclusive of tool calls, that was used in this response.
/// 
final MaxOutputTokens? maxOutputTokens;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  if (object != null) 'object': object?.toJson(),
  if (status != null) 'status': status?.toJson(),
  if (statusDetails != null) 'status_details': statusDetails?.toJson(),
  if (output != null) 'output': output?.map((e) => e.toJson()).toList(),
  'metadata': ?metadata,
  if (audio != null) 'audio': audio?.toJson(),
  if (usage != null) 'usage': usage?.toJson(),
  'conversation_id': ?conversationId,
  if (outputModalities != null) 'output_modalities': outputModalities?.map((e) => e.toJson()).toList(),
  if (maxOutputTokens != null) 'max_output_tokens': maxOutputTokens?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'id', 'object', 'status', 'status_details', 'output', 'metadata', 'audio', 'usage', 'conversation_id', 'output_modalities', 'max_output_tokens'}.contains(key)); } 
RealtimeResponse copyWith({String? Function()? id, RealtimeBetaResponseObject? Function()? object, RealtimeBetaResponseStatus? Function()? status, StatusDetails? Function()? statusDetails, List<RealtimeConversationItem>? Function()? output, Map<String, String>? Function()? metadata, RealtimeResponseAudio? Function()? audio, RealtimeBetaResponseUsage? Function()? usage, String? Function()? conversationId, List<OutputModalities>? Function()? outputModalities, MaxOutputTokens? Function()? maxOutputTokens, }) { return RealtimeResponse(
  id: id != null ? id() : this.id,
  object: object != null ? object() : this.object,
  status: status != null ? status() : this.status,
  statusDetails: statusDetails != null ? statusDetails() : this.statusDetails,
  output: output != null ? output() : this.output,
  metadata: metadata != null ? metadata() : this.metadata,
  audio: audio != null ? audio() : this.audio,
  usage: usage != null ? usage() : this.usage,
  conversationId: conversationId != null ? conversationId() : this.conversationId,
  outputModalities: outputModalities != null ? outputModalities() : this.outputModalities,
  maxOutputTokens: maxOutputTokens != null ? maxOutputTokens() : this.maxOutputTokens,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is RealtimeResponse &&
          id == other.id &&
          object == other.object &&
          status == other.status &&
          statusDetails == other.statusDetails &&
          listEquals(output, other.output) &&
          metadata == other.metadata &&
          audio == other.audio &&
          usage == other.usage &&
          conversationId == other.conversationId &&
          listEquals(outputModalities, other.outputModalities) &&
          maxOutputTokens == other.maxOutputTokens; } 
@override int get hashCode { return Object.hash(id, object, status, statusDetails, Object.hashAll(output ?? const []), metadata, audio, usage, conversationId, Object.hashAll(outputModalities ?? const []), maxOutputTokens); } 
@override String toString() { return 'RealtimeResponse(id: $id, object: $object, status: $status, statusDetails: $statusDetails, output: $output, metadata: $metadata, audio: $audio, usage: $usage, conversationId: $conversationId, outputModalities: $outputModalities, maxOutputTokens: $maxOutputTokens)'; } 
 }
