// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/computer_tool_call_output/computer_tool_call_output_status.dart';import 'package:pub_openai/models/realtime_conversation_item_function_call/realtime_conversation_item_function_call_object.dart';/// A function call item in a Realtime conversation.
@immutable final class RealtimeConversationItemFunctionCall {const RealtimeConversationItemFunctionCall({required this.type, required this.name, required this.arguments, this.id, this.object, this.status, this.callId, });

factory RealtimeConversationItemFunctionCall.fromJson(Map<String, dynamic> json) { return RealtimeConversationItemFunctionCall(
  id: json['id'] as String?,
  object: json['object'] != null ? RealtimeConversationItemFunctionCallObject.fromJson(json['object'] as String) : null,
  type: json['type'] as String,
  status: json['status'] != null ? ComputerToolCallOutputStatus.fromJson(json['status'] as String) : null,
  callId: json['call_id'] as String?,
  name: json['name'] as String,
  arguments: json['arguments'] as String,
); }

/// The unique ID of the item. This may be provided by the client or generated by the server.
final String? id;

/// Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item.
final RealtimeConversationItemFunctionCallObject? object;

/// The type of the item. Always `function_call`.
final String type;

/// The status of the item. Has no effect on the conversation.
final ComputerToolCallOutputStatus? status;

/// The ID of the function call.
final String? callId;

/// The name of the function being called.
final String name;

/// The arguments of the function call. This is a JSON-encoded string representing the arguments passed to the function, for example `{"arg1": "value1", "arg2": 42}`.
final String arguments;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  if (object != null) 'object': object?.toJson(),
  'type': type,
  if (status != null) 'status': status?.toJson(),
  'call_id': ?callId,
  'name': name,
  'arguments': arguments,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('name') && json['name'] is String &&
      json.containsKey('arguments') && json['arguments'] is String; } 
RealtimeConversationItemFunctionCall copyWith({String? Function()? id, RealtimeConversationItemFunctionCallObject? Function()? object, String? type, ComputerToolCallOutputStatus? Function()? status, String? Function()? callId, String? name, String? arguments, }) { return RealtimeConversationItemFunctionCall(
  id: id != null ? id() : this.id,
  object: object != null ? object() : this.object,
  type: type ?? this.type,
  status: status != null ? status() : this.status,
  callId: callId != null ? callId() : this.callId,
  name: name ?? this.name,
  arguments: arguments ?? this.arguments,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is RealtimeConversationItemFunctionCall &&
          id == other.id &&
          object == other.object &&
          type == other.type &&
          status == other.status &&
          callId == other.callId &&
          name == other.name &&
          arguments == other.arguments;

@override int get hashCode => Object.hash(id, object, type, status, callId, name, arguments);

@override String toString() => 'RealtimeConversationItemFunctionCall(id: $id, object: $object, type: $type, status: $status, callId: $callId, name: $name, arguments: $arguments)';

 }
