// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/realtime_session_create_request_ga.dart';/// Parameters required to initiate a realtime call and receive the SDP answer
/// needed to complete a WebRTC peer connection. Provide an SDP offer generated
/// by your client and optionally configure the session that will answer the call.
@immutable final class RealtimeCallCreateRequest {const RealtimeCallCreateRequest({required this.sdp, this.session, });

factory RealtimeCallCreateRequest.fromJson(Map<String, dynamic> json) { return RealtimeCallCreateRequest(
  sdp: json['sdp'] as String,
  session: json['session'] != null ? RealtimeSessionCreateRequestGa.fromJson(json['session'] as Map<String, dynamic>) : null,
); }

/// WebRTC Session Description Protocol (SDP) offer generated by the caller.
final String sdp;

/// Optional session configuration to apply before the realtime session is
/// created. Use the same parameters you would send in a [`create client secret`](/docs/api-reference/realtime-sessions/create-realtime-client-secret)
/// request.
final RealtimeSessionCreateRequestGa? session;

Map<String, dynamic> toJson() { return {
  'sdp': sdp,
  if (session != null) 'session': session?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('sdp') && json['sdp'] is String; } 
RealtimeCallCreateRequest copyWith({String? sdp, RealtimeSessionCreateRequestGa Function()? session, }) { return RealtimeCallCreateRequest(
  sdp: sdp ?? this.sdp,
  session: session != null ? session() : this.session,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is RealtimeCallCreateRequest &&
          sdp == other.sdp &&
          session == other.session; } 
@override int get hashCode { return Object.hash(sdp, session); } 
@override String toString() { return 'RealtimeCallCreateRequest(sdp: $sdp, session: $session)'; } 
 }
