// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/computer_tool_call_output/computer_tool_call_output_status.dart';import 'package:pub_openai/models/realtime_conversation_item_function_call/realtime_conversation_item_function_call_object.dart';/// A function call output item in a Realtime conversation.
@immutable final class RealtimeConversationItemFunctionCallOutput {const RealtimeConversationItemFunctionCallOutput({required this.type, required this.callId, required this.output, this.id, this.object, this.status, });

factory RealtimeConversationItemFunctionCallOutput.fromJson(Map<String, dynamic> json) { return RealtimeConversationItemFunctionCallOutput(
  id: json['id'] as String?,
  object: json['object'] != null ? RealtimeConversationItemFunctionCallObject.fromJson(json['object'] as String) : null,
  type: json['type'] as String,
  status: json['status'] != null ? ComputerToolCallOutputStatus.fromJson(json['status'] as String) : null,
  callId: json['call_id'] as String,
  output: json['output'] as String,
); }

/// The unique ID of the item. This may be provided by the client or generated by the server.
final String? id;

/// Identifier for the API object being returned - always `realtime.item`. Optional when creating a new item.
final RealtimeConversationItemFunctionCallObject? object;

/// The type of the item. Always `function_call_output`.
final String type;

/// The status of the item. Has no effect on the conversation.
final ComputerToolCallOutputStatus? status;

/// The ID of the function call this output is for.
final String callId;

/// The output of the function call, this is free text and can contain any information or simply be empty.
final String output;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  if (object != null) 'object': object?.toJson(),
  'type': type,
  if (status != null) 'status': status?.toJson(),
  'call_id': callId,
  'output': output,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('output') && json['output'] is String; } 
RealtimeConversationItemFunctionCallOutput copyWith({String Function()? id, RealtimeConversationItemFunctionCallObject Function()? object, String? type, ComputerToolCallOutputStatus Function()? status, String? callId, String? output, }) { return RealtimeConversationItemFunctionCallOutput(
  id: id != null ? id() : this.id,
  object: object != null ? object() : this.object,
  type: type ?? this.type,
  status: status != null ? status() : this.status,
  callId: callId ?? this.callId,
  output: output ?? this.output,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is RealtimeConversationItemFunctionCallOutput &&
          id == other.id &&
          object == other.object &&
          type == other.type &&
          status == other.status &&
          callId == other.callId &&
          output == other.output; } 
@override int get hashCode { return Object.hash(id, object, type, status, callId, output); } 
@override String toString() { return 'RealtimeConversationItemFunctionCallOutput(id: $id, object: $object, type: $type, status: $status, callId: $callId, output: $output)'; } 
 }
