// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/function_call_item_status.dart';import 'package:pub_openai/models/tool.dart';import 'package:pub_openai/models/tool_search_execution_type.dart';@immutable final class ToolSearchOutputItemParam {const ToolSearchOutputItemParam({required this.tools, this.id, this.callId, this.type = 'tool_search_output', this.execution, this.status, });

factory ToolSearchOutputItemParam.fromJson(Map<String, dynamic> json) { return ToolSearchOutputItemParam(
  id: json['id'] as String?,
  callId: json['call_id'] as String?,
  type: json['type'] as String,
  execution: json['execution'] != null ? ToolSearchExecutionType.fromJson(json['execution'] as String) : null,
  tools: (json['tools'] as List<dynamic>).map((e) => Tool.fromJson(e as Map<String, dynamic>)).toList(),
  status: json['status'] != null ? FunctionCallItemStatus.fromJson(json['status'] as String) : null,
); }

/// The unique ID of this tool search output.
final String? id;

/// The unique ID of the tool search call generated by the model.
final String? callId;

/// The item type. Always `tool_search_output`.
final String type;

/// Whether tool search was executed by the server or by the client.
final ToolSearchExecutionType? execution;

/// The loaded tool definitions returned by the tool search output.
final List<Tool> tools;

final FunctionCallItemStatus? status;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  'call_id': ?callId,
  'type': type,
  if (execution != null) 'execution': execution?.toJson(),
  'tools': tools.map((e) => e.toJson()).toList(),
  if (status != null) 'status': status?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('tools'); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final callId$ = callId;
if (callId$ != null) {
  if (callId$.isEmpty) { errors.add('callId: length must be >= 1'); }
  if (callId$.length > 64) { errors.add('callId: length must be <= 64'); }
}
return errors; } 
ToolSearchOutputItemParam copyWith({String? Function()? id, String? Function()? callId, String? type, ToolSearchExecutionType? Function()? execution, List<Tool>? tools, FunctionCallItemStatus? Function()? status, }) { return ToolSearchOutputItemParam(
  id: id != null ? id() : this.id,
  callId: callId != null ? callId() : this.callId,
  type: type ?? this.type,
  execution: execution != null ? execution() : this.execution,
  tools: tools ?? this.tools,
  status: status != null ? status() : this.status,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is ToolSearchOutputItemParam &&
          id == other.id &&
          callId == other.callId &&
          type == other.type &&
          execution == other.execution &&
          listEquals(tools, other.tools) &&
          status == other.status;

@override int get hashCode => Object.hash(id, callId, type, execution, Object.hashAll(tools), status);

@override String toString() => 'ToolSearchOutputItemParam(id: $id, callId: $callId, type: $type, execution: $execution, tools: $tools, status: $status)';

 }
