// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/tool_search_execution_type.dart';@immutable final class FunctionCallStatus {const FunctionCallStatus._(this.value);

factory FunctionCallStatus.fromJson(String json) { return switch (json) {
  'in_progress' => inProgress,
  'completed' => completed,
  'incomplete' => incomplete,
  _ => FunctionCallStatus._(json),
}; }

static const FunctionCallStatus inProgress = FunctionCallStatus._('in_progress');

static const FunctionCallStatus completed = FunctionCallStatus._('completed');

static const FunctionCallStatus incomplete = FunctionCallStatus._('incomplete');

static const List<FunctionCallStatus> values = [inProgress, completed, incomplete];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) { return identical(this, other) ||
    other is FunctionCallStatus && other.value == value; } 
@override int get hashCode { return value.hashCode; } 
@override String toString() { return 'FunctionCallStatus($value)'; } 
 }
@immutable final class ToolSearchCall {const ToolSearchCall({required this.id, required this.callId, required this.execution, required this.arguments, required this.status, this.type = 'tool_search_call', this.createdBy, });

factory ToolSearchCall.fromJson(Map<String, dynamic> json) { return ToolSearchCall(
  type: json['type'] as String,
  id: json['id'] as String,
  callId: json['call_id'] as String?,
  execution: ToolSearchExecutionType.fromJson(json['execution'] as String),
  arguments: json['arguments'],
  status: FunctionCallStatus.fromJson(json['status'] as String),
  createdBy: json['created_by'] as String?,
); }

/// The type of the item. Always `tool_search_call`.
final String type;

/// The unique ID of the tool search call item.
final String id;

/// The unique ID of the tool search call generated by the model.
final String? callId;

/// Whether tool search was executed by the server or by the client.
final ToolSearchExecutionType execution;

/// Arguments used for the tool search call.
final dynamic arguments;

/// The status of the tool search call item that was recorded.
final FunctionCallStatus status;

/// The identifier of the actor that created the item.
final String? createdBy;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'call_id': callId,
  'execution': execution.toJson(),
  'arguments': arguments,
  'status': status.toJson(),
  'created_by': ?createdBy,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('execution') &&
      json.containsKey('arguments') &&
      json.containsKey('status'); } 
ToolSearchCall copyWith({String? type, String? id, String? Function()? callId, ToolSearchExecutionType? execution, dynamic Function()? arguments, FunctionCallStatus? status, String? Function()? createdBy, }) { return ToolSearchCall(
  type: type ?? this.type,
  id: id ?? this.id,
  callId: callId != null ? callId() : this.callId,
  execution: execution ?? this.execution,
  arguments: arguments != null ? arguments() : this.arguments,
  status: status ?? this.status,
  createdBy: createdBy != null ? createdBy() : this.createdBy,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is ToolSearchCall &&
          type == other.type &&
          id == other.id &&
          callId == other.callId &&
          execution == other.execution &&
          arguments == other.arguments &&
          status == other.status &&
          createdBy == other.createdBy; } 
@override int get hashCode { return Object.hash(type, id, callId, execution, arguments, status, createdBy); } 
@override String toString() { return 'ToolSearchCall(type: $type, id: $id, callId: $callId, execution: $execution, arguments: $arguments, status: $status, createdBy: $createdBy)'; } 
 }
