// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/ToolSearchCall

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/tool_search_execution_type.dart';sealed class FunctionCallStatus {const FunctionCallStatus();

factory FunctionCallStatus.fromJson(String json) { return switch (json) {
  'in_progress' => inProgress,
  'completed' => completed,
  'incomplete' => incomplete,
  _ => FunctionCallStatus$Unknown(json),
}; }

static const FunctionCallStatus inProgress = FunctionCallStatus$inProgress._();

static const FunctionCallStatus completed = FunctionCallStatus$completed._();

static const FunctionCallStatus incomplete = FunctionCallStatus$incomplete._();

static const List<FunctionCallStatus> values = [inProgress, completed, incomplete];

String get value;
String toJson() { return value; } 
/// The Dart identifier name for this value, or the raw value if unknown.
String get name { return switch (value) {
  'in_progress' => 'inProgress',
  'completed' => 'completed',
  'incomplete' => 'incomplete',
  _ => value,
}; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return this is FunctionCallStatus$Unknown; } 
@override String toString() => 'FunctionCallStatus($value)';

 }
@immutable final class FunctionCallStatus$inProgress extends FunctionCallStatus {const FunctionCallStatus$inProgress._();

@override String get value => 'in_progress';

@override bool operator ==(Object other) => identical(this, other) || other is FunctionCallStatus$inProgress;

@override int get hashCode => 'in_progress'.hashCode;

 }
@immutable final class FunctionCallStatus$completed extends FunctionCallStatus {const FunctionCallStatus$completed._();

@override String get value => 'completed';

@override bool operator ==(Object other) => identical(this, other) || other is FunctionCallStatus$completed;

@override int get hashCode => 'completed'.hashCode;

 }
@immutable final class FunctionCallStatus$incomplete extends FunctionCallStatus {const FunctionCallStatus$incomplete._();

@override String get value => 'incomplete';

@override bool operator ==(Object other) => identical(this, other) || other is FunctionCallStatus$incomplete;

@override int get hashCode => 'incomplete'.hashCode;

 }
@immutable final class FunctionCallStatus$Unknown extends FunctionCallStatus {const FunctionCallStatus$Unknown(this.value);

@override final String value;

@override bool operator ==(Object other) => identical(this, other) ||
    other is FunctionCallStatus$Unknown && other.value == value;

@override int get hashCode => value.hashCode;

 }
@immutable final class ToolSearchCall {const ToolSearchCall({required this.id, required this.callId, required this.execution, required this.arguments, required this.status, this.type = 'tool_search_call', this.createdBy, });

factory ToolSearchCall.fromJson(Map<String, dynamic> json) { return ToolSearchCall(
  type: json['type'] as String,
  id: json['id'] as String,
  callId: json['call_id'] as String?,
  execution: ToolSearchExecutionType.fromJson(json['execution'] as String),
  arguments: json['arguments'],
  status: FunctionCallStatus.fromJson(json['status'] as String),
  createdBy: json['created_by'] as String?,
); }

/// The type of the item. Always `tool_search_call`.
final String type;

/// The unique ID of the tool search call item.
final String id;

/// The unique ID of the tool search call generated by the model.
final String? callId;

/// Whether tool search was executed by the server or by the client.
final ToolSearchExecutionType execution;

/// Arguments used for the tool search call.
final dynamic arguments;

/// The status of the tool search call item that was recorded.
final FunctionCallStatus status;

/// The identifier of the actor that created the item.
final String? createdBy;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'call_id': callId,
  'execution': execution.toJson(),
  'arguments': arguments,
  'status': status.toJson(),
  'created_by': ?createdBy,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('execution') &&
      json.containsKey('arguments') &&
      json.containsKey('status'); } 
ToolSearchCall copyWith({String? type, String? id, String? Function()? callId, ToolSearchExecutionType? execution, dynamic Function()? arguments, FunctionCallStatus? status, String? Function()? createdBy, }) { return ToolSearchCall(
  type: type ?? this.type,
  id: id ?? this.id,
  callId: callId != null ? callId() : this.callId,
  execution: execution ?? this.execution,
  arguments: arguments != null ? arguments() : this.arguments,
  status: status ?? this.status,
  createdBy: createdBy != null ? createdBy() : this.createdBy,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is ToolSearchCall &&
          type == other.type &&
          id == other.id &&
          callId == other.callId &&
          execution == other.execution &&
          arguments == other.arguments &&
          status == other.status &&
          createdBy == other.createdBy;

@override int get hashCode => Object.hash(type, id, callId, execution, arguments, status, createdBy);

@override String toString() => 'ToolSearchCall(type: $type, id: $id, callId: $callId, execution: $execution, arguments: $arguments, status: $status, createdBy: $createdBy)';

 }
