// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/ToolSearchCallItemParam

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/empty_model_param.dart';import 'package:pub_openai/models/function_call_item_status.dart';import 'package:pub_openai/models/tool_search_execution_type.dart';@immutable final class ToolSearchCallItemParam {const ToolSearchCallItemParam({required this.arguments, this.id, this.callId, this.type = 'tool_search_call', this.execution, this.status, });

factory ToolSearchCallItemParam.fromJson(Map<String, dynamic> json) { return ToolSearchCallItemParam(
  id: json['id'] as String?,
  callId: json['call_id'] as String?,
  type: json['type'] as String,
  execution: json['execution'] != null ? ToolSearchExecutionType.fromJson(json['execution'] as String) : null,
  arguments: EmptyModelParam.fromJson(json['arguments'] as Map<String, dynamic>),
  status: json['status'] != null ? FunctionCallItemStatus.fromJson(json['status'] as String) : null,
); }

/// The unique ID of this tool search call.
final String? id;

/// The unique ID of the tool search call generated by the model.
final String? callId;

/// The item type. Always `tool_search_call`.
final String type;

/// Whether tool search was executed by the server or by the client.
final ToolSearchExecutionType? execution;

/// The arguments supplied to the tool search call.
final EmptyModelParam arguments;

final FunctionCallItemStatus? status;

Map<String, dynamic> toJson() { return {
  'id': ?id,
  'call_id': ?callId,
  'type': type,
  if (execution != null) 'execution': execution?.toJson(),
  'arguments': arguments.toJson(),
  if (status != null) 'status': status?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('arguments'); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final callId$ = callId;
if (callId$ != null) {
  if (callId$.isEmpty) { errors.add('callId: length must be >= 1'); }
  if (callId$.length > 64) { errors.add('callId: length must be <= 64'); }
}
return errors; } 
ToolSearchCallItemParam copyWith({String? Function()? id, String? Function()? callId, String? type, ToolSearchExecutionType? Function()? execution, EmptyModelParam? arguments, FunctionCallItemStatus? Function()? status, }) { return ToolSearchCallItemParam(
  id: id != null ? id() : this.id,
  callId: callId != null ? callId() : this.callId,
  type: type ?? this.type,
  execution: execution != null ? execution() : this.execution,
  arguments: arguments ?? this.arguments,
  status: status != null ? status() : this.status,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is ToolSearchCallItemParam &&
          id == other.id &&
          callId == other.callId &&
          type == other.type &&
          execution == other.execution &&
          arguments == other.arguments &&
          status == other.status;

@override int get hashCode => Object.hash(id, callId, type, execution, arguments, status);

@override String toString() => 'ToolSearchCallItemParam(id: $id, callId: $callId, type: $type, execution: $execution, arguments: $arguments, status: $status)';

 }
