// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/ToolSearchOutput

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/tool.dart';import 'package:pub_openai/models/tool_search_execution_type.dart';@immutable final class FunctionCallOutputStatusEnum {const FunctionCallOutputStatusEnum._(this.value);

factory FunctionCallOutputStatusEnum.fromJson(String json) { return switch (json) {
  'in_progress' => inProgress,
  'completed' => completed,
  'incomplete' => incomplete,
  _ => FunctionCallOutputStatusEnum._(json),
}; }

static const FunctionCallOutputStatusEnum inProgress = FunctionCallOutputStatusEnum._('in_progress');

static const FunctionCallOutputStatusEnum completed = FunctionCallOutputStatusEnum._('completed');

static const FunctionCallOutputStatusEnum incomplete = FunctionCallOutputStatusEnum._('incomplete');

static const List<FunctionCallOutputStatusEnum> values = [inProgress, completed, incomplete];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) => identical(this, other) ||
    other is FunctionCallOutputStatusEnum && other.value == value;

@override int get hashCode => value.hashCode;

@override String toString() => 'FunctionCallOutputStatusEnum($value)';

 }
@immutable final class ToolSearchOutput {const ToolSearchOutput({required this.id, required this.callId, required this.execution, required this.tools, required this.status, this.type = 'tool_search_output', this.createdBy, });

factory ToolSearchOutput.fromJson(Map<String, dynamic> json) { return ToolSearchOutput(
  type: json['type'] as String,
  id: json['id'] as String,
  callId: json['call_id'] as String?,
  execution: ToolSearchExecutionType.fromJson(json['execution'] as String),
  tools: (json['tools'] as List<dynamic>).map((e) => Tool.fromJson(e as Map<String, dynamic>)).toList(),
  status: FunctionCallOutputStatusEnum.fromJson(json['status'] as String),
  createdBy: json['created_by'] as String?,
); }

/// The type of the item. Always `tool_search_output`.
final String type;

/// The unique ID of the tool search output item.
final String id;

/// The unique ID of the tool search call generated by the model.
final String? callId;

/// Whether tool search was executed by the server or by the client.
final ToolSearchExecutionType execution;

/// The loaded tool definitions returned by tool search.
final List<Tool> tools;

/// The status of the tool search output item that was recorded.
final FunctionCallOutputStatusEnum status;

/// The identifier of the actor that created the item.
final String? createdBy;

Map<String, dynamic> toJson() { return {
  'type': type,
  'id': id,
  'call_id': callId,
  'execution': execution.toJson(),
  'tools': tools.map((e) => e.toJson()).toList(),
  'status': status.toJson(),
  'created_by': ?createdBy,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('type') && json['type'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('call_id') && json['call_id'] is String &&
      json.containsKey('execution') &&
      json.containsKey('tools') &&
      json.containsKey('status'); } 
ToolSearchOutput copyWith({String? type, String? id, String? Function()? callId, ToolSearchExecutionType? execution, List<Tool>? tools, FunctionCallOutputStatusEnum? status, String? Function()? createdBy, }) { return ToolSearchOutput(
  type: type ?? this.type,
  id: id ?? this.id,
  callId: callId != null ? callId() : this.callId,
  execution: execution ?? this.execution,
  tools: tools ?? this.tools,
  status: status ?? this.status,
  createdBy: createdBy != null ? createdBy() : this.createdBy,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is ToolSearchOutput &&
          type == other.type &&
          id == other.id &&
          callId == other.callId &&
          execution == other.execution &&
          listEquals(tools, other.tools) &&
          status == other.status &&
          createdBy == other.createdBy;

@override int get hashCode => Object.hash(type, id, callId, execution, Object.hashAll(tools), status, createdBy);

@override String toString() => 'ToolSearchOutput(type: $type, id: $id, callId: $callId, execution: $execution, tools: $tools, status: $status, createdBy: $createdBy)';

 }
