// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';import 'package:pub_stripe_spec3/models/item_billing_thresholds_param.dart';typedef PostSubscriptionItemsItemRequestBillingThresholds = OneOf2<ItemBillingThresholdsParam,GetPaymentMethodConfigurationsApplicationVariant2>;
