// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';import 'package:pub_stripe_spec3/models/post_payment_links_payment_link_request/optional_items_variant1.dart';typedef PostPaymentLinksPaymentLinkRequestOptionalItems = OneOf2<List<OptionalItemsVariant1>,GetPaymentMethodConfigurationsApplicationVariant2>;
