// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';import 'package:pub_stripe_spec3/models/post_checkout_sessions_session_request/shipping_options_variant1.dart';typedef PostCheckoutSessionsSessionRequestShippingOptions = OneOf2<List<ShippingOptionsVariant1>,GetPaymentMethodConfigurationsApplicationVariant2>;
