// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/AccountCallCallNotificationInstance (inline: RequestMethod)

import 'package:degenerate_runtime/degenerate_runtime.dart';/// The HTTP method used to generate the notification. If the notification was generated during a phone call, this is the HTTP Method used to request the resource on your server. If the notification was generated by your use of our REST API, this is the HTTP method used to call the resource on our servers.
sealed class RequestMethod {const RequestMethod();

factory RequestMethod.fromJson(String json) { return switch (json) {
  'GET' => $get,
  'POST' => post,
  _ => RequestMethod$Unknown(json),
}; }

static const RequestMethod $get = RequestMethod$$get._();

static const RequestMethod post = RequestMethod$post._();

static const List<RequestMethod> values = [$get, post];

String get value;
String toJson() { return value; } 
/// The Dart identifier name for this value, or the raw value if unknown.
String get name { return switch (value) {
  'GET' => r'$get',
  'POST' => 'post',
  _ => value,
}; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return this is RequestMethod$Unknown; } 
@override String toString() => 'RequestMethod($value)';

 }
@immutable final class RequestMethod$$get extends RequestMethod {const RequestMethod$$get._();

@override String get value => 'GET';

@override bool operator ==(Object other) => identical(this, other) || other is RequestMethod$$get;

@override int get hashCode => 'GET'.hashCode;

 }
@immutable final class RequestMethod$post extends RequestMethod {const RequestMethod$post._();

@override String get value => 'POST';

@override bool operator ==(Object other) => identical(this, other) || other is RequestMethod$post;

@override int get hashCode => 'POST'.hashCode;

 }
@immutable final class RequestMethod$Unknown extends RequestMethod {const RequestMethod$Unknown(this.value);

@override final String value;

@override bool operator ==(Object other) => identical(this, other) ||
    other is RequestMethod$Unknown && other.value == value;

@override int get hashCode => value.hashCode;

 }
