// Behavior gate for the generated JSON codecs: for every synthesized fixture,
// `encode(decode(sample))` must deep-equal `sample`. The fixtures (samples +
// decode/encode closures) are generated by `--emit-roundtrip-fixtures`; this
// harness is the generic runner shared across the flagged snapshot packages.
//
// Each package defines its own `RoundtripFixture` class (same shape), so we
// import with prefixes and read the fields structurally.
import 'package:spec_05_components_and_references/roundtrip_fixtures.dart'
    as components;
import 'package:spec_08_schema_json_schema_2020_12/roundtrip_fixtures.dart'
    as schema;
import 'package:spec_12_unions/roundtrip_fixtures.dart' as unions;
import 'package:spec_14_constraints/roundtrip_fixtures.dart' as constraints;
import 'package:spec_extension_types/roundtrip_fixtures.dart' as exttypes;
import 'package:test/test.dart';

void main() {
  _run('components', [
    for (final f in components.roundtripFixtures)
      (f.schemaName, f.sample, f.decode, f.encode),
  ]);
  _run('schema-2020-12', [
    for (final f in schema.roundtripFixtures)
      (f.schemaName, f.sample, f.decode, f.encode),
  ]);
  _run('unions', [
    for (final f in unions.roundtripFixtures)
      (f.schemaName, f.sample, f.decode, f.encode),
  ]);
  _run('constraints', [
    for (final f in constraints.roundtripFixtures)
      (f.schemaName, f.sample, f.decode, f.encode),
  ]);
  _run('extension-types', [
    for (final f in exttypes.roundtripFixtures)
      (f.schemaName, f.sample, f.decode, f.encode),
  ]);
}

void _run(
  String group$,
  List<
    (
      String,
      Object?,
      Object? Function(Object?),
      Object? Function(Object?),
    )
  >
  fixtures,
) {
  group(group$, () {
    test('has fixtures', () => expect(fixtures, isNotEmpty));
    for (final (name, sample, decode, encode) in fixtures) {
      test(name, () {
        final reencoded = encode(decode(sample));
        expect(
          reencoded,
          equals(sample),
          reason:
              '$name: re-encoded JSON does not match the synthesized sample',
        );
      });
    }
  });
}
