// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/run_step_delta_step_details_tool_calls_code_object.dart';import 'package:pub_openai/models/run_step_delta_step_details_tool_calls_file_search_object.dart';import 'package:pub_openai/models/run_step_delta_step_details_tool_calls_function_object.dart';typedef RunStepDeltaStepDetailsToolCallsObjectToolCalls = OneOf3<RunStepDeltaStepDetailsToolCallsCodeObject,RunStepDeltaStepDetailsToolCallsFileSearchObject,RunStepDeltaStepDetailsToolCallsFunctionObject>;
