// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/payment_intent_payment_method_options_us_bank_account.dart';import 'package:pub_stripe_spec3/models/payment_intent_type_specific_payment_method_options_client.dart';typedef PaymentIntentPaymentMethodOptionsUsBankAccount2 = OneOf2<PaymentIntentPaymentMethodOptionsUsBankAccount,PaymentIntentTypeSpecificPaymentMethodOptionsClient>;
