// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/connect_account_reference.dart';/// 
@immutable final class InvoiceSettingQuoteSetting {const InvoiceSettingQuoteSetting({required this.issuer, this.daysUntilDue, });

factory InvoiceSettingQuoteSetting.fromJson(Map<String, dynamic> json) { return InvoiceSettingQuoteSetting(
  daysUntilDue: json['days_until_due'] != null ? (json['days_until_due'] as num).toInt() : null,
  issuer: ConnectAccountReference.fromJson(json['issuer'] as Map<String, dynamic>),
); }

/// Number of days within which a customer must pay invoices generated by this quote. This value will be `null` for quotes where `collection_method=charge_automatically`.
final int? daysUntilDue;

final ConnectAccountReference issuer;

Map<String, dynamic> toJson() { return {
  'days_until_due': ?daysUntilDue,
  'issuer': issuer.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('issuer'); } 
InvoiceSettingQuoteSetting copyWith({int? Function()? daysUntilDue, ConnectAccountReference? issuer, }) { return InvoiceSettingQuoteSetting(
  daysUntilDue: daysUntilDue != null ? daysUntilDue() : this.daysUntilDue,
  issuer: issuer ?? this.issuer,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is InvoiceSettingQuoteSetting &&
          daysUntilDue == other.daysUntilDue &&
          issuer == other.issuer;

@override int get hashCode => Object.hash(daysUntilDue, issuer);

@override String toString() => 'InvoiceSettingQuoteSetting(daysUntilDue: $daysUntilDue, issuer: $issuer)';

 }
