// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/connect_account_reference.dart';import 'package:pub_stripe_spec3/models/deleted_tax_id.dart';import 'package:pub_stripe_spec3/models/invoice/invoice_account_tax_ids.dart';import 'package:pub_stripe_spec3/models/tax_id.dart';/// 
@immutable final class InvoiceSettingSubscriptionSchedulePhaseSetting {const InvoiceSettingSubscriptionSchedulePhaseSetting({this.accountTaxIds, this.daysUntilDue, this.issuer, });

factory InvoiceSettingSubscriptionSchedulePhaseSetting.fromJson(Map<String, dynamic> json) { return InvoiceSettingSubscriptionSchedulePhaseSetting(
  accountTaxIds: (json['account_tax_ids'] as List<dynamic>?)?.map((e) => OneOf3.parse(e, fromA: (v) => v as String, fromB: (v) => TaxId.fromJson(v as Map<String, dynamic>), fromC: (v) => DeletedTaxId.fromJson(v as Map<String, dynamic>),)).toList(),
  daysUntilDue: json['days_until_due'] != null ? (json['days_until_due'] as num).toInt() : null,
  issuer: json['issuer'] != null ? ConnectAccountReference.fromJson(json['issuer'] as Map<String, dynamic>) : null,
); }

/// The account tax IDs associated with this phase of the subscription schedule. Will be set on invoices generated by this phase of the subscription schedule.
final List<InvoiceAccountTaxIds>? accountTaxIds;

/// Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
final int? daysUntilDue;

/// The connected account that issues the invoice. The invoice is presented with the branding and support information of the specified account.
final ConnectAccountReference? issuer;

Map<String, dynamic> toJson() { return {
  if (accountTaxIds != null) 'account_tax_ids': accountTaxIds?.map((e) => e.toJson()).toList(),
  'days_until_due': ?daysUntilDue,
  if (issuer != null) 'issuer': issuer?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'account_tax_ids', 'days_until_due', 'issuer'}.contains(key)); } 
InvoiceSettingSubscriptionSchedulePhaseSetting copyWith({List<InvoiceAccountTaxIds>? Function()? accountTaxIds, int? Function()? daysUntilDue, ConnectAccountReference? Function()? issuer, }) { return InvoiceSettingSubscriptionSchedulePhaseSetting(
  accountTaxIds: accountTaxIds != null ? accountTaxIds() : this.accountTaxIds,
  daysUntilDue: daysUntilDue != null ? daysUntilDue() : this.daysUntilDue,
  issuer: issuer != null ? issuer() : this.issuer,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is InvoiceSettingSubscriptionSchedulePhaseSetting &&
          listEquals(accountTaxIds, other.accountTaxIds) &&
          daysUntilDue == other.daysUntilDue &&
          issuer == other.issuer;

@override int get hashCode => Object.hash(Object.hashAll(accountTaxIds ?? const []), daysUntilDue, issuer);

@override String toString() => 'InvoiceSettingSubscriptionSchedulePhaseSetting(accountTaxIds: $accountTaxIds, daysUntilDue: $daysUntilDue, issuer: $issuer)';

 }
