// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/InvoiceSettingSubscriptionScheduleSetting

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/connect_account_reference.dart';import 'package:pub_stripe_spec3/models/deleted_tax_id.dart';import 'package:pub_stripe_spec3/models/invoice/invoice_account_tax_ids.dart';import 'package:pub_stripe_spec3/models/tax_id.dart';/// 
@immutable final class InvoiceSettingSubscriptionScheduleSetting {const InvoiceSettingSubscriptionScheduleSetting({required this.issuer, this.accountTaxIds, this.daysUntilDue, });

factory InvoiceSettingSubscriptionScheduleSetting.fromJson(Map<String, dynamic> json) { return InvoiceSettingSubscriptionScheduleSetting(
  accountTaxIds: (json['account_tax_ids'] as List<dynamic>?)?.map((e) => OneOf3.parse(e, fromA: (v) => v as String, fromB: (v) => TaxId.fromJson(v as Map<String, dynamic>), fromC: (v) => DeletedTaxId.fromJson(v as Map<String, dynamic>),)).toList(),
  daysUntilDue: json['days_until_due'] != null ? (json['days_until_due'] as num).toInt() : null,
  issuer: ConnectAccountReference.fromJson(json['issuer'] as Map<String, dynamic>),
); }

/// The account tax IDs associated with the subscription schedule. Will be set on invoices generated by the subscription schedule.
final List<InvoiceAccountTaxIds>? accountTaxIds;

/// Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
final int? daysUntilDue;

final ConnectAccountReference issuer;

Map<String, dynamic> toJson() { return {
  if (accountTaxIds != null) 'account_tax_ids': accountTaxIds?.map((e) => e.toJson()).toList(),
  'days_until_due': ?daysUntilDue,
  'issuer': issuer.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('issuer'); } 
InvoiceSettingSubscriptionScheduleSetting copyWith({List<InvoiceAccountTaxIds>? Function()? accountTaxIds, int? Function()? daysUntilDue, ConnectAccountReference? issuer, }) { return InvoiceSettingSubscriptionScheduleSetting(
  accountTaxIds: accountTaxIds != null ? accountTaxIds() : this.accountTaxIds,
  daysUntilDue: daysUntilDue != null ? daysUntilDue() : this.daysUntilDue,
  issuer: issuer ?? this.issuer,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is InvoiceSettingSubscriptionScheduleSetting &&
          listEquals(accountTaxIds, other.accountTaxIds) &&
          daysUntilDue == other.daysUntilDue &&
          issuer == other.issuer;

@override int get hashCode => Object.hash(Object.hashAll(accountTaxIds ?? const []), daysUntilDue, issuer);

@override String toString() => 'InvoiceSettingSubscriptionScheduleSetting(accountTaxIds: $accountTaxIds, daysUntilDue: $daysUntilDue, issuer: $issuer)';

 }
