// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// 
@immutable final class MandatePaypal {const MandatePaypal({this.billingAgreementId, this.payerId, });

factory MandatePaypal.fromJson(Map<String, dynamic> json) { return MandatePaypal(
  billingAgreementId: json['billing_agreement_id'] as String?,
  payerId: json['payer_id'] as String?,
); }

/// The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
final String? billingAgreementId;

/// PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
final String? payerId;

Map<String, dynamic> toJson() { return {
  'billing_agreement_id': ?billingAgreementId,
  'payer_id': ?payerId,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'billing_agreement_id', 'payer_id'}.contains(key)); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final billingAgreementId$ = billingAgreementId;
if (billingAgreementId$ != null) {
  if (billingAgreementId$.length > 5000) errors.add('billingAgreementId: length must be <= 5000');
}
final payerId$ = payerId;
if (payerId$ != null) {
  if (payerId$.length > 5000) errors.add('payerId: length must be <= 5000');
}
return errors; } 
MandatePaypal copyWith({String? Function()? billingAgreementId, String? Function()? payerId, }) { return MandatePaypal(
  billingAgreementId: billingAgreementId != null ? billingAgreementId() : this.billingAgreementId,
  payerId: payerId != null ? payerId() : this.payerId,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is MandatePaypal &&
          billingAgreementId == other.billingAgreementId &&
          payerId == other.payerId; } 
@override int get hashCode { return Object.hash(billingAgreementId, payerId); } 
@override String toString() { return 'MandatePaypal(billingAgreementId: $billingAgreementId, payerId: $payerId)'; } 
 }
