// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/mandate.dart';import 'package:pub_stripe_spec3/models/payment_method.dart';import 'package:pub_stripe_spec3/models/payment_method_details_bancontact/generated_sepa_debit.dart';import 'package:pub_stripe_spec3/models/payment_method_details_bancontact/generated_sepa_debit_mandate.dart';import 'package:pub_stripe_spec3/models/payment_method_details_bancontact/payment_method_details_bancontact_preferred_language.dart';/// 
@immutable final class PaymentMethodDetailsBancontact {const PaymentMethodDetailsBancontact({this.bankCode, this.bankName, this.bic, this.generatedSepaDebit, this.generatedSepaDebitMandate, this.ibanLast4, this.preferredLanguage, this.verifiedName, });

factory PaymentMethodDetailsBancontact.fromJson(Map<String, dynamic> json) { return PaymentMethodDetailsBancontact(
  bankCode: json['bank_code'] as String?,
  bankName: json['bank_name'] as String?,
  bic: json['bic'] as String?,
  generatedSepaDebit: json['generated_sepa_debit'] != null ? OneOf2.parse(json['generated_sepa_debit'], fromA: (v) => v as String, fromB: (v) => PaymentMethod.fromJson(v as Map<String, dynamic>),) : null,
  generatedSepaDebitMandate: json['generated_sepa_debit_mandate'] != null ? OneOf2.parse(json['generated_sepa_debit_mandate'], fromA: (v) => v as String, fromB: (v) => Mandate.fromJson(v as Map<String, dynamic>),) : null,
  ibanLast4: json['iban_last4'] as String?,
  preferredLanguage: json['preferred_language'] != null ? PaymentMethodDetailsBancontactPreferredLanguage.fromJson(json['preferred_language'] as String) : null,
  verifiedName: json['verified_name'] as String?,
); }

/// Bank code of bank associated with the bank account.
final String? bankCode;

/// Name of the bank associated with the bank account.
final String? bankName;

/// Bank Identifier Code of the bank associated with the bank account.
final String? bic;

/// The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
final GeneratedSepaDebit? generatedSepaDebit;

/// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
final GeneratedSepaDebitMandate? generatedSepaDebitMandate;

/// Last four characters of the IBAN.
final String? ibanLast4;

/// Preferred language of the Bancontact authorization page that the customer is redirected to.
/// Can be one of `en`, `de`, `fr`, or `nl`
final PaymentMethodDetailsBancontactPreferredLanguage? preferredLanguage;

/// Owner's verified full name. Values are verified or provided by Bancontact directly
/// (if supported) at the time of authorization or settlement. They cannot be set or mutated.
final String? verifiedName;

Map<String, dynamic> toJson() { return {
  'bank_code': ?bankCode,
  'bank_name': ?bankName,
  'bic': ?bic,
  if (generatedSepaDebit != null) 'generated_sepa_debit': generatedSepaDebit?.toJson(),
  if (generatedSepaDebitMandate != null) 'generated_sepa_debit_mandate': generatedSepaDebitMandate?.toJson(),
  'iban_last4': ?ibanLast4,
  if (preferredLanguage != null) 'preferred_language': preferredLanguage?.toJson(),
  'verified_name': ?verifiedName,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'bank_code', 'bank_name', 'bic', 'generated_sepa_debit', 'generated_sepa_debit_mandate', 'iban_last4', 'preferred_language', 'verified_name'}.contains(key)); } 
PaymentMethodDetailsBancontact copyWith({String? Function()? bankCode, String? Function()? bankName, String? Function()? bic, GeneratedSepaDebit? Function()? generatedSepaDebit, GeneratedSepaDebitMandate? Function()? generatedSepaDebitMandate, String? Function()? ibanLast4, PaymentMethodDetailsBancontactPreferredLanguage? Function()? preferredLanguage, String? Function()? verifiedName, }) { return PaymentMethodDetailsBancontact(
  bankCode: bankCode != null ? bankCode() : this.bankCode,
  bankName: bankName != null ? bankName() : this.bankName,
  bic: bic != null ? bic() : this.bic,
  generatedSepaDebit: generatedSepaDebit != null ? generatedSepaDebit() : this.generatedSepaDebit,
  generatedSepaDebitMandate: generatedSepaDebitMandate != null ? generatedSepaDebitMandate() : this.generatedSepaDebitMandate,
  ibanLast4: ibanLast4 != null ? ibanLast4() : this.ibanLast4,
  preferredLanguage: preferredLanguage != null ? preferredLanguage() : this.preferredLanguage,
  verifiedName: verifiedName != null ? verifiedName() : this.verifiedName,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PaymentMethodDetailsBancontact &&
          bankCode == other.bankCode &&
          bankName == other.bankName &&
          bic == other.bic &&
          generatedSepaDebit == other.generatedSepaDebit &&
          generatedSepaDebitMandate == other.generatedSepaDebitMandate &&
          ibanLast4 == other.ibanLast4 &&
          preferredLanguage == other.preferredLanguage &&
          verifiedName == other.verifiedName; } 
@override int get hashCode { return Object.hash(bankCode, bankName, bic, generatedSepaDebit, generatedSepaDebitMandate, ibanLast4, preferredLanguage, verifiedName); } 
@override String toString() { return 'PaymentMethodDetailsBancontact(bankCode: $bankCode, bankName: $bankName, bic: $bic, generatedSepaDebit: $generatedSepaDebit, generatedSepaDebitMandate: $generatedSepaDebitMandate, ibanLast4: $ibanLast4, preferredLanguage: $preferredLanguage, verifiedName: $verifiedName)'; } 
 }
