// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/PaymentMethodDetailsCardPresentReceipt

import 'package:degenerate_runtime/degenerate_runtime.dart';/// The type of account being debited or credited
@immutable final class PaymentMethodDetailsCardPresentReceiptAccountType {const PaymentMethodDetailsCardPresentReceiptAccountType._(this.value);

factory PaymentMethodDetailsCardPresentReceiptAccountType.fromJson(String json) { return switch (json) {
  'checking' => checking,
  'credit' => credit,
  'prepaid' => prepaid,
  'unknown' => unknown,
  _ => PaymentMethodDetailsCardPresentReceiptAccountType._(json),
}; }

static const PaymentMethodDetailsCardPresentReceiptAccountType checking = PaymentMethodDetailsCardPresentReceiptAccountType._('checking');

static const PaymentMethodDetailsCardPresentReceiptAccountType credit = PaymentMethodDetailsCardPresentReceiptAccountType._('credit');

static const PaymentMethodDetailsCardPresentReceiptAccountType prepaid = PaymentMethodDetailsCardPresentReceiptAccountType._('prepaid');

static const PaymentMethodDetailsCardPresentReceiptAccountType unknown = PaymentMethodDetailsCardPresentReceiptAccountType._('unknown');

static const List<PaymentMethodDetailsCardPresentReceiptAccountType> values = [checking, credit, prepaid, unknown];

final String value;

String toJson() { return value; } 
/// The Dart identifier name for this value, or the raw value if unknown.
String get name { return switch (value) {
  'checking' => 'checking',
  'credit' => 'credit',
  'prepaid' => 'prepaid',
  'unknown' => 'unknown',
  _ => value,
}; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) => identical(this, other) ||
    other is PaymentMethodDetailsCardPresentReceiptAccountType && other.value == value;

@override int get hashCode => value.hashCode;

@override String toString() => 'PaymentMethodDetailsCardPresentReceiptAccountType($value)';

 }
/// 
@immutable final class PaymentMethodDetailsCardPresentReceipt {const PaymentMethodDetailsCardPresentReceipt({this.accountType, this.applicationCryptogram, this.applicationPreferredName, this.authorizationCode, this.authorizationResponseCode, this.cardholderVerificationMethod, this.dedicatedFileName, this.terminalVerificationResults, this.transactionStatusInformation, });

factory PaymentMethodDetailsCardPresentReceipt.fromJson(Map<String, dynamic> json) { return PaymentMethodDetailsCardPresentReceipt(
  accountType: json['account_type'] != null ? PaymentMethodDetailsCardPresentReceiptAccountType.fromJson(json['account_type'] as String) : null,
  applicationCryptogram: json['application_cryptogram'] as String?,
  applicationPreferredName: json['application_preferred_name'] as String?,
  authorizationCode: json['authorization_code'] as String?,
  authorizationResponseCode: json['authorization_response_code'] as String?,
  cardholderVerificationMethod: json['cardholder_verification_method'] as String?,
  dedicatedFileName: json['dedicated_file_name'] as String?,
  terminalVerificationResults: json['terminal_verification_results'] as String?,
  transactionStatusInformation: json['transaction_status_information'] as String?,
); }

/// The type of account being debited or credited
final PaymentMethodDetailsCardPresentReceiptAccountType? accountType;

/// The Application Cryptogram, a unique value generated by the card to authenticate the transaction with issuers.
final String? applicationCryptogram;

/// The Application Identifier (AID) on the card used to determine which networks are eligible to process the transaction. Referenced from EMV tag 9F12, data encoded on the card's chip.
final String? applicationPreferredName;

/// Identifier for this transaction.
final String? authorizationCode;

/// EMV tag 8A. A code returned by the card issuer.
final String? authorizationResponseCode;

/// Describes the method used by the cardholder to verify ownership of the card. One of the following: `approval`, `failure`, `none`, `offline_pin`, `offline_pin_and_signature`, `online_pin`, or `signature`.
final String? cardholderVerificationMethod;

/// Similar to the application_preferred_name, identifying the applications (AIDs) available on the card. Referenced from EMV tag 84.
final String? dedicatedFileName;

/// A 5-byte string that records the checks and validations that occur between the card and the terminal. These checks determine how the terminal processes the transaction and what risk tolerance is acceptable. Referenced from EMV Tag 95.
final String? terminalVerificationResults;

/// An indication of which steps were completed during the card read process. Referenced from EMV Tag 9B.
final String? transactionStatusInformation;

Map<String, dynamic> toJson() { return {
  if (accountType != null) 'account_type': accountType?.toJson(),
  'application_cryptogram': ?applicationCryptogram,
  'application_preferred_name': ?applicationPreferredName,
  'authorization_code': ?authorizationCode,
  'authorization_response_code': ?authorizationResponseCode,
  'cardholder_verification_method': ?cardholderVerificationMethod,
  'dedicated_file_name': ?dedicatedFileName,
  'terminal_verification_results': ?terminalVerificationResults,
  'transaction_status_information': ?transactionStatusInformation,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'account_type', 'application_cryptogram', 'application_preferred_name', 'authorization_code', 'authorization_response_code', 'cardholder_verification_method', 'dedicated_file_name', 'terminal_verification_results', 'transaction_status_information'}.contains(key)); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final applicationCryptogram$ = applicationCryptogram;
if (applicationCryptogram$ != null) {
  if (applicationCryptogram$.length > 5000) { errors.add('applicationCryptogram: length must be <= 5000'); }
}
final applicationPreferredName$ = applicationPreferredName;
if (applicationPreferredName$ != null) {
  if (applicationPreferredName$.length > 5000) { errors.add('applicationPreferredName: length must be <= 5000'); }
}
final authorizationCode$ = authorizationCode;
if (authorizationCode$ != null) {
  if (authorizationCode$.length > 5000) { errors.add('authorizationCode: length must be <= 5000'); }
}
final authorizationResponseCode$ = authorizationResponseCode;
if (authorizationResponseCode$ != null) {
  if (authorizationResponseCode$.length > 5000) { errors.add('authorizationResponseCode: length must be <= 5000'); }
}
final cardholderVerificationMethod$ = cardholderVerificationMethod;
if (cardholderVerificationMethod$ != null) {
  if (cardholderVerificationMethod$.length > 5000) { errors.add('cardholderVerificationMethod: length must be <= 5000'); }
}
final dedicatedFileName$ = dedicatedFileName;
if (dedicatedFileName$ != null) {
  if (dedicatedFileName$.length > 5000) { errors.add('dedicatedFileName: length must be <= 5000'); }
}
final terminalVerificationResults$ = terminalVerificationResults;
if (terminalVerificationResults$ != null) {
  if (terminalVerificationResults$.length > 5000) { errors.add('terminalVerificationResults: length must be <= 5000'); }
}
final transactionStatusInformation$ = transactionStatusInformation;
if (transactionStatusInformation$ != null) {
  if (transactionStatusInformation$.length > 5000) { errors.add('transactionStatusInformation: length must be <= 5000'); }
}
return errors; } 
PaymentMethodDetailsCardPresentReceipt copyWith({PaymentMethodDetailsCardPresentReceiptAccountType? Function()? accountType, String? Function()? applicationCryptogram, String? Function()? applicationPreferredName, String? Function()? authorizationCode, String? Function()? authorizationResponseCode, String? Function()? cardholderVerificationMethod, String? Function()? dedicatedFileName, String? Function()? terminalVerificationResults, String? Function()? transactionStatusInformation, }) { return PaymentMethodDetailsCardPresentReceipt(
  accountType: accountType != null ? accountType() : this.accountType,
  applicationCryptogram: applicationCryptogram != null ? applicationCryptogram() : this.applicationCryptogram,
  applicationPreferredName: applicationPreferredName != null ? applicationPreferredName() : this.applicationPreferredName,
  authorizationCode: authorizationCode != null ? authorizationCode() : this.authorizationCode,
  authorizationResponseCode: authorizationResponseCode != null ? authorizationResponseCode() : this.authorizationResponseCode,
  cardholderVerificationMethod: cardholderVerificationMethod != null ? cardholderVerificationMethod() : this.cardholderVerificationMethod,
  dedicatedFileName: dedicatedFileName != null ? dedicatedFileName() : this.dedicatedFileName,
  terminalVerificationResults: terminalVerificationResults != null ? terminalVerificationResults() : this.terminalVerificationResults,
  transactionStatusInformation: transactionStatusInformation != null ? transactionStatusInformation() : this.transactionStatusInformation,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is PaymentMethodDetailsCardPresentReceipt &&
          accountType == other.accountType &&
          applicationCryptogram == other.applicationCryptogram &&
          applicationPreferredName == other.applicationPreferredName &&
          authorizationCode == other.authorizationCode &&
          authorizationResponseCode == other.authorizationResponseCode &&
          cardholderVerificationMethod == other.cardholderVerificationMethod &&
          dedicatedFileName == other.dedicatedFileName &&
          terminalVerificationResults == other.terminalVerificationResults &&
          transactionStatusInformation == other.transactionStatusInformation;

@override int get hashCode => Object.hash(accountType, applicationCryptogram, applicationPreferredName, authorizationCode, authorizationResponseCode, cardholderVerificationMethod, dedicatedFileName, terminalVerificationResults, transactionStatusInformation);

@override String toString() => 'PaymentMethodDetailsCardPresentReceipt(\n  accountType: $accountType,\n  applicationCryptogram: $applicationCryptogram,\n  applicationPreferredName: $applicationPreferredName,\n  authorizationCode: $authorizationCode,\n  authorizationResponseCode: $authorizationResponseCode,\n  cardholderVerificationMethod: $cardholderVerificationMethod,\n  dedicatedFileName: $dedicatedFileName,\n  terminalVerificationResults: $terminalVerificationResults,\n  transactionStatusInformation: $transactionStatusInformation,\n)';

 }
