// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// 
@immutable final class PaymentMethodDetailsPromptpay {const PaymentMethodDetailsPromptpay({this.reference});

factory PaymentMethodDetailsPromptpay.fromJson(Map<String, dynamic> json) { return PaymentMethodDetailsPromptpay(
  reference: json['reference'] as String?,
); }

/// Bill reference generated by PromptPay
final String? reference;

Map<String, dynamic> toJson() { return {
  'reference': ?reference,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'reference'}.contains(key)); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final reference$ = reference;
if (reference$ != null) {
  if (reference$.length > 5000) errors.add('reference: length must be <= 5000');
}
return errors; } 
PaymentMethodDetailsPromptpay copyWith({String? Function()? reference}) { return PaymentMethodDetailsPromptpay(
  reference: reference != null ? reference() : this.reference,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PaymentMethodDetailsPromptpay &&
          reference == other.reference; } 
@override int get hashCode { return reference.hashCode; } 
@override String toString() { return 'PaymentMethodDetailsPromptpay(reference: $reference)'; } 
 }
