// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/PaymentMethodDetailsPaymentRecordPromptpay

import 'package:degenerate_runtime/degenerate_runtime.dart';/// 
@immutable final class PaymentMethodDetailsPaymentRecordPromptpay {const PaymentMethodDetailsPaymentRecordPromptpay({this.reference});

factory PaymentMethodDetailsPaymentRecordPromptpay.fromJson(Map<String, dynamic> json) { return PaymentMethodDetailsPaymentRecordPromptpay(
  reference: json['reference'] as String?,
); }

/// Bill reference generated by PromptPay
final String? reference;

Map<String, dynamic> toJson() { return {
  'reference': ?reference,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'reference'}.contains(key)); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final reference$ = reference;
if (reference$ != null) {
  if (reference$.length > 5000) { errors.add('reference: length must be <= 5000'); }
}
return errors; } 
PaymentMethodDetailsPaymentRecordPromptpay copyWith({String? Function()? reference}) { return PaymentMethodDetailsPaymentRecordPromptpay(
  reference: reference != null ? reference() : this.reference,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is PaymentMethodDetailsPaymentRecordPromptpay &&
          reference == other.reference;

@override int get hashCode => reference.hashCode;

@override String toString() => 'PaymentMethodDetailsPaymentRecordPromptpay(reference: $reference)';

 }
