// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/mandate.dart';import 'package:pub_stripe_spec3/models/payment_method.dart';import 'package:pub_stripe_spec3/models/payment_method_details_bancontact/generated_sepa_debit.dart';import 'package:pub_stripe_spec3/models/payment_method_details_bancontact/generated_sepa_debit_mandate.dart';import 'package:pub_stripe_spec3/models/payment_method_details_ideal/bic.dart';import 'package:pub_stripe_spec3/models/payment_method_details_ideal/payment_method_details_ideal_bank.dart';/// 
@immutable final class PaymentMethodDetailsIdeal {const PaymentMethodDetailsIdeal({this.bank, this.bic, this.generatedSepaDebit, this.generatedSepaDebitMandate, this.ibanLast4, this.transactionId, this.verifiedName, });

factory PaymentMethodDetailsIdeal.fromJson(Map<String, dynamic> json) { return PaymentMethodDetailsIdeal(
  bank: json['bank'] != null ? PaymentMethodDetailsIdealBank.fromJson(json['bank'] as String) : null,
  bic: json['bic'] != null ? Bic.fromJson(json['bic'] as String) : null,
  generatedSepaDebit: json['generated_sepa_debit'] != null ? OneOf2.parse(json['generated_sepa_debit'], fromA: (v) => v as String, fromB: (v) => PaymentMethod.fromJson(v as Map<String, dynamic>),) : null,
  generatedSepaDebitMandate: json['generated_sepa_debit_mandate'] != null ? OneOf2.parse(json['generated_sepa_debit_mandate'], fromA: (v) => v as String, fromB: (v) => Mandate.fromJson(v as Map<String, dynamic>),) : null,
  ibanLast4: json['iban_last4'] as String?,
  transactionId: json['transaction_id'] as String?,
  verifiedName: json['verified_name'] as String?,
); }

/// The customer's bank. Can be one of `abn_amro`, `adyen`, `asn_bank`, `bunq`, `buut`, `finom`, `handelsbanken`, `ing`, `knab`, `mollie`, `moneyou`, `n26`, `nn`, `rabobank`, `regiobank`, `revolut`, `sns_bank`, `triodos_bank`, `van_lanschot`, or `yoursafe`.
final PaymentMethodDetailsIdealBank? bank;

/// The Bank Identifier Code of the customer's bank.
final Bic? bic;

/// The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
final GeneratedSepaDebit? generatedSepaDebit;

/// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
final GeneratedSepaDebitMandate? generatedSepaDebitMandate;

/// Last four characters of the IBAN.
final String? ibanLast4;

/// Unique transaction ID generated by iDEAL.
final String? transactionId;

/// Owner's verified full name. Values are verified or provided by iDEAL directly
/// (if supported) at the time of authorization or settlement. They cannot be set or mutated.
final String? verifiedName;

Map<String, dynamic> toJson() { return {
  if (bank != null) 'bank': bank?.toJson(),
  if (bic != null) 'bic': bic?.toJson(),
  if (generatedSepaDebit != null) 'generated_sepa_debit': generatedSepaDebit?.toJson(),
  if (generatedSepaDebitMandate != null) 'generated_sepa_debit_mandate': generatedSepaDebitMandate?.toJson(),
  'iban_last4': ?ibanLast4,
  'transaction_id': ?transactionId,
  'verified_name': ?verifiedName,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'bank', 'bic', 'generated_sepa_debit', 'generated_sepa_debit_mandate', 'iban_last4', 'transaction_id', 'verified_name'}.contains(key)); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final ibanLast4$ = ibanLast4;
if (ibanLast4$ != null) {
  if (ibanLast4$.length > 5000) { errors.add('ibanLast4: length must be <= 5000'); }
}
final transactionId$ = transactionId;
if (transactionId$ != null) {
  if (transactionId$.length > 5000) { errors.add('transactionId: length must be <= 5000'); }
}
final verifiedName$ = verifiedName;
if (verifiedName$ != null) {
  if (verifiedName$.length > 5000) { errors.add('verifiedName: length must be <= 5000'); }
}
return errors; } 
PaymentMethodDetailsIdeal copyWith({PaymentMethodDetailsIdealBank? Function()? bank, Bic? Function()? bic, GeneratedSepaDebit? Function()? generatedSepaDebit, GeneratedSepaDebitMandate? Function()? generatedSepaDebitMandate, String? Function()? ibanLast4, String? Function()? transactionId, String? Function()? verifiedName, }) { return PaymentMethodDetailsIdeal(
  bank: bank != null ? bank() : this.bank,
  bic: bic != null ? bic() : this.bic,
  generatedSepaDebit: generatedSepaDebit != null ? generatedSepaDebit() : this.generatedSepaDebit,
  generatedSepaDebitMandate: generatedSepaDebitMandate != null ? generatedSepaDebitMandate() : this.generatedSepaDebitMandate,
  ibanLast4: ibanLast4 != null ? ibanLast4() : this.ibanLast4,
  transactionId: transactionId != null ? transactionId() : this.transactionId,
  verifiedName: verifiedName != null ? verifiedName() : this.verifiedName,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is PaymentMethodDetailsIdeal &&
          bank == other.bank &&
          bic == other.bic &&
          generatedSepaDebit == other.generatedSepaDebit &&
          generatedSepaDebitMandate == other.generatedSepaDebitMandate &&
          ibanLast4 == other.ibanLast4 &&
          transactionId == other.transactionId &&
          verifiedName == other.verifiedName;

@override int get hashCode => Object.hash(bank, bic, generatedSepaDebit, generatedSepaDebitMandate, ibanLast4, transactionId, verifiedName);

@override String toString() => 'PaymentMethodDetailsIdeal(bank: $bank, bic: $bic, generatedSepaDebit: $generatedSepaDebit, generatedSepaDebitMandate: $generatedSepaDebitMandate, ibanLast4: $ibanLast4, transactionId: $transactionId, verifiedName: $verifiedName)';

 }
