// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/PaymentMethodDetailsFpx

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/payment_method_details_fpx/payment_method_details_fpx_bank.dart';/// 
@immutable final class PaymentMethodDetailsFpx {const PaymentMethodDetailsFpx({required this.bank, this.transactionId, });

factory PaymentMethodDetailsFpx.fromJson(Map<String, dynamic> json) { return PaymentMethodDetailsFpx(
  bank: PaymentMethodDetailsFpxBank.fromJson(json['bank'] as String),
  transactionId: json['transaction_id'] as String?,
); }

/// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
final PaymentMethodDetailsFpxBank bank;

/// Unique transaction id generated by FPX for every request from the merchant
final String? transactionId;

Map<String, dynamic> toJson() { return {
  'bank': bank.toJson(),
  'transaction_id': ?transactionId,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('bank'); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final transactionId$ = transactionId;
if (transactionId$ != null) {
  if (transactionId$.length > 5000) { errors.add('transactionId: length must be <= 5000'); }
}
return errors; } 
PaymentMethodDetailsFpx copyWith({PaymentMethodDetailsFpxBank? bank, String? Function()? transactionId, }) { return PaymentMethodDetailsFpx(
  bank: bank ?? this.bank,
  transactionId: transactionId != null ? transactionId() : this.transactionId,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is PaymentMethodDetailsFpx &&
          bank == other.bank &&
          transactionId == other.transactionId;

@override int get hashCode => Object.hash(bank, transactionId);

@override String toString() => 'PaymentMethodDetailsFpx(bank: $bank, transactionId: $transactionId)';

 }
