// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// 
@immutable final class PaymentMethodDetailsGrabpay {const PaymentMethodDetailsGrabpay({this.transactionId});

factory PaymentMethodDetailsGrabpay.fromJson(Map<String, dynamic> json) { return PaymentMethodDetailsGrabpay(
  transactionId: json['transaction_id'] as String?,
); }

/// Unique transaction id generated by GrabPay
final String? transactionId;

Map<String, dynamic> toJson() { return {
  'transaction_id': ?transactionId,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'transaction_id'}.contains(key)); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final transactionId$ = transactionId;
if (transactionId$ != null) {
  if (transactionId$.length > 5000) errors.add('transactionId: length must be <= 5000');
}
return errors; } 
PaymentMethodDetailsGrabpay copyWith({String? Function()? transactionId}) { return PaymentMethodDetailsGrabpay(
  transactionId: transactionId != null ? transactionId() : this.transactionId,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is PaymentMethodDetailsGrabpay &&
          transactionId == other.transactionId;

@override int get hashCode => transactionId.hashCode;

@override String toString() => 'PaymentMethodDetailsGrabpay(transactionId: $transactionId)';

 }
