// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/paypal_seller_protection.dart';/// 
@immutable final class PaymentMethodDetailsPaypal {const PaymentMethodDetailsPaypal({this.country, this.payerEmail, this.payerId, this.payerName, this.sellerProtection, this.transactionId, });

factory PaymentMethodDetailsPaypal.fromJson(Map<String, dynamic> json) { return PaymentMethodDetailsPaypal(
  country: json['country'] as String?,
  payerEmail: json['payer_email'] as String?,
  payerId: json['payer_id'] as String?,
  payerName: json['payer_name'] as String?,
  sellerProtection: json['seller_protection'] != null ? PaypalSellerProtection.fromJson(json['seller_protection'] as Map<String, dynamic>) : null,
  transactionId: json['transaction_id'] as String?,
); }

/// Two-letter ISO code representing the buyer's country. Values are provided by PayPal directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
final String? country;

/// Owner's email. Values are provided by PayPal directly
/// (if supported) at the time of authorization or settlement. They cannot be set or mutated.
final String? payerEmail;

/// PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
final String? payerId;

/// Owner's full name. Values provided by PayPal directly
/// (if supported) at the time of authorization or settlement. They cannot be set or mutated.
final String? payerName;

/// The level of protection offered as defined by PayPal Seller Protection for Merchants, for this transaction.
final PaypalSellerProtection? sellerProtection;

/// A unique ID generated by PayPal for this transaction.
final String? transactionId;

Map<String, dynamic> toJson() { return {
  'country': ?country,
  'payer_email': ?payerEmail,
  'payer_id': ?payerId,
  'payer_name': ?payerName,
  if (sellerProtection != null) 'seller_protection': sellerProtection?.toJson(),
  'transaction_id': ?transactionId,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'country', 'payer_email', 'payer_id', 'payer_name', 'seller_protection', 'transaction_id'}.contains(key)); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final country$ = country;
if (country$ != null) {
  if (country$.length > 5000) errors.add('country: length must be <= 5000');
}
final payerEmail$ = payerEmail;
if (payerEmail$ != null) {
  if (payerEmail$.length > 5000) errors.add('payerEmail: length must be <= 5000');
}
final payerId$ = payerId;
if (payerId$ != null) {
  if (payerId$.length > 5000) errors.add('payerId: length must be <= 5000');
}
final payerName$ = payerName;
if (payerName$ != null) {
  if (payerName$.length > 5000) errors.add('payerName: length must be <= 5000');
}
final transactionId$ = transactionId;
if (transactionId$ != null) {
  if (transactionId$.length > 5000) errors.add('transactionId: length must be <= 5000');
}
return errors; } 
PaymentMethodDetailsPaypal copyWith({String? Function()? country, String? Function()? payerEmail, String? Function()? payerId, String? Function()? payerName, PaypalSellerProtection? Function()? sellerProtection, String? Function()? transactionId, }) { return PaymentMethodDetailsPaypal(
  country: country != null ? country() : this.country,
  payerEmail: payerEmail != null ? payerEmail() : this.payerEmail,
  payerId: payerId != null ? payerId() : this.payerId,
  payerName: payerName != null ? payerName() : this.payerName,
  sellerProtection: sellerProtection != null ? sellerProtection() : this.sellerProtection,
  transactionId: transactionId != null ? transactionId() : this.transactionId,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PaymentMethodDetailsPaypal &&
          country == other.country &&
          payerEmail == other.payerEmail &&
          payerId == other.payerId &&
          payerName == other.payerName &&
          sellerProtection == other.sellerProtection &&
          transactionId == other.transactionId; } 
@override int get hashCode { return Object.hash(country, payerEmail, payerId, payerName, sellerProtection, transactionId); } 
@override String toString() { return 'PaymentMethodDetailsPaypal(country: $country, payerEmail: $payerEmail, payerId: $payerId, payerName: $payerName, sellerProtection: $sellerProtection, transactionId: $transactionId)'; } 
 }
