// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/package_dimensions.dart';import 'package:pub_stripe_spec3/models/post_products_request/default_price_data.dart';import 'package:pub_stripe_spec3/models/post_products_request/post_products_request_marketing_features.dart';@immutable final class PostProductsRequest {const PostProductsRequest({required this.name, this.active, this.defaultPriceData, this.description, this.expand, this.id, this.images, this.marketingFeatures, this.metadata, this.packageDimensions, this.shippable, this.statementDescriptor, this.taxCode, this.unitLabel, this.url, });

factory PostProductsRequest.fromJson(Map<String, dynamic> json) { return PostProductsRequest(
  active: json['active'] as bool?,
  defaultPriceData: json['default_price_data'] != null ? DefaultPriceData.fromJson(json['default_price_data'] as Map<String, dynamic>) : null,
  description: json['description'] as String?,
  expand: (json['expand'] as List<dynamic>?)?.map((e) => e as String).toList(),
  id: json['id'] as String?,
  images: (json['images'] as List<dynamic>?)?.map((e) => e as String).toList(),
  marketingFeatures: (json['marketing_features'] as List<dynamic>?)?.map((e) => PostProductsRequestMarketingFeatures.fromJson(e as Map<String, dynamic>)).toList(),
  metadata: (json['metadata'] as Map<String, dynamic>?)?.map((k, v) => MapEntry(k, v as String)),
  name: json['name'] as String,
  packageDimensions: json['package_dimensions'] != null ? PackageDimensions.fromJson(json['package_dimensions'] as Map<String, dynamic>) : null,
  shippable: json['shippable'] as bool?,
  statementDescriptor: json['statement_descriptor'] as String?,
  taxCode: json['tax_code'] as String?,
  unitLabel: json['unit_label'] as String?,
  url: json['url'] as String?,
); }

/// Whether the product is currently available for purchase. Defaults to `true`.
final bool? active;

/// Data used to generate a new [Price](https://docs.stripe.com/api/prices) object. This Price will be set as the default price for this product.
final DefaultPriceData? defaultPriceData;

/// The product's description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
final String? description;

/// Specifies which fields in the response should be expanded.
final List<String>? expand;

/// An identifier will be randomly generated by Stripe. You can optionally override this ID, but the ID must be unique across all products in your Stripe account.
final String? id;

/// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
final List<String>? images;

/// A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://docs.stripe.com/payments/checkout/pricing-table).
final List<PostProductsRequestMarketingFeatures>? marketingFeatures;

/// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
final Map<String,String>? metadata;

/// The product's name, meant to be displayable to the customer.
final String name;

/// The dimensions of this product for shipping purposes.
final PackageDimensions? packageDimensions;

/// Whether this product is shipped (i.e., physical goods).
final bool? shippable;

/// An arbitrary string to be displayed on your customer's credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all.
/// 
/// This may be up to 22 characters. The statement description may not include `<`, `>`, `\`, `"`, `'` characters, and will appear on your customer's statement in capital letters. Non-ASCII characters are automatically stripped.
///  It must contain at least one letter. Only used for subscription payments.
final String? statementDescriptor;

/// A [tax code](https://docs.stripe.com/tax/tax-categories) ID.
final String? taxCode;

/// A label that represents units of this product. When set, this will be included in customers' receipts, invoices, Checkout, and the customer portal.
final String? unitLabel;

/// A URL of a publicly-accessible webpage for this product.
final String? url;

Map<String, dynamic> toJson() { return {
  'active': ?active,
  if (defaultPriceData != null) 'default_price_data': defaultPriceData?.toJson(),
  'description': ?description,
  'expand': ?expand,
  'id': ?id,
  'images': ?images,
  if (marketingFeatures != null) 'marketing_features': marketingFeatures?.map((e) => e.toJson()).toList(),
  'metadata': ?metadata,
  'name': name,
  if (packageDimensions != null) 'package_dimensions': packageDimensions?.toJson(),
  'shippable': ?shippable,
  'statement_descriptor': ?statementDescriptor,
  'tax_code': ?taxCode,
  'unit_label': ?unitLabel,
  'url': ?url,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('name') && json['name'] is String; } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final description$ = description;
if (description$ != null) {
  if (description$.length > 40000) errors.add('description: length must be <= 40000');
}
final id$ = id;
if (id$ != null) {
  if (id$.length > 5000) errors.add('id: length must be <= 5000');
}
if (name.length > 5000) errors.add('name: length must be <= 5000');
final statementDescriptor$ = statementDescriptor;
if (statementDescriptor$ != null) {
  if (statementDescriptor$.length > 22) errors.add('statementDescriptor: length must be <= 22');
}
final unitLabel$ = unitLabel;
if (unitLabel$ != null) {
  if (unitLabel$.length > 12) errors.add('unitLabel: length must be <= 12');
}
final url$ = url;
if (url$ != null) {
  if (url$.length > 5000) errors.add('url: length must be <= 5000');
}
return errors; } 
PostProductsRequest copyWith({bool? Function()? active, DefaultPriceData? Function()? defaultPriceData, String? Function()? description, List<String>? Function()? expand, String? Function()? id, List<String>? Function()? images, List<PostProductsRequestMarketingFeatures>? Function()? marketingFeatures, Map<String, String>? Function()? metadata, String? name, PackageDimensions? Function()? packageDimensions, bool? Function()? shippable, String? Function()? statementDescriptor, String? Function()? taxCode, String? Function()? unitLabel, String? Function()? url, }) { return PostProductsRequest(
  active: active != null ? active() : this.active,
  defaultPriceData: defaultPriceData != null ? defaultPriceData() : this.defaultPriceData,
  description: description != null ? description() : this.description,
  expand: expand != null ? expand() : this.expand,
  id: id != null ? id() : this.id,
  images: images != null ? images() : this.images,
  marketingFeatures: marketingFeatures != null ? marketingFeatures() : this.marketingFeatures,
  metadata: metadata != null ? metadata() : this.metadata,
  name: name ?? this.name,
  packageDimensions: packageDimensions != null ? packageDimensions() : this.packageDimensions,
  shippable: shippable != null ? shippable() : this.shippable,
  statementDescriptor: statementDescriptor != null ? statementDescriptor() : this.statementDescriptor,
  taxCode: taxCode != null ? taxCode() : this.taxCode,
  unitLabel: unitLabel != null ? unitLabel() : this.unitLabel,
  url: url != null ? url() : this.url,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is PostProductsRequest &&
          active == other.active &&
          defaultPriceData == other.defaultPriceData &&
          description == other.description &&
          listEquals(expand, other.expand) &&
          id == other.id &&
          listEquals(images, other.images) &&
          listEquals(marketingFeatures, other.marketingFeatures) &&
          metadata == other.metadata &&
          name == other.name &&
          packageDimensions == other.packageDimensions &&
          shippable == other.shippable &&
          statementDescriptor == other.statementDescriptor &&
          taxCode == other.taxCode &&
          unitLabel == other.unitLabel &&
          url == other.url;

@override int get hashCode => Object.hash(active, defaultPriceData, description, Object.hashAll(expand ?? const []), id, Object.hashAll(images ?? const []), Object.hashAll(marketingFeatures ?? const []), metadata, name, packageDimensions, shippable, statementDescriptor, taxCode, unitLabel, url);

@override String toString() => 'PostProductsRequest(\n  active: $active,\n  defaultPriceData: $defaultPriceData,\n  description: $description,\n  expand: $expand,\n  id: $id,\n  images: $images,\n  marketingFeatures: $marketingFeatures,\n  metadata: $metadata,\n  name: $name,\n  packageDimensions: $packageDimensions,\n  shippable: $shippable,\n  statementDescriptor: $statementDescriptor,\n  taxCode: $taxCode,\n  unitLabel: $unitLabel,\n  url: $url,\n)';

 }
