// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';import 'package:pub_stripe_spec3/models/post_accounts_account_bank_accounts_id_request/metadata.dart';@immutable final class PostTerminalReadersRequest {const PostTerminalReadersRequest({required this.registrationCode, this.expand, this.label, this.location, this.metadata, });

factory PostTerminalReadersRequest.fromJson(Map<String, dynamic> json) { return PostTerminalReadersRequest(
  expand: (json['expand'] as List<dynamic>?)?.map((e) => e as String).toList(),
  label: json['label'] as String?,
  location: json['location'] as String?,
  metadata: json['metadata'] != null ? OneOf2.parse(json['metadata'], fromA: (v) => (v as Map<String, dynamic>).map((k, v) => MapEntry(k, v as String)), fromB: (v) => GetPaymentMethodConfigurationsApplicationVariant2.fromJson(v as String),) : null,
  registrationCode: json['registration_code'] as String,
); }

/// Specifies which fields in the response should be expanded.
final List<String>? expand;

/// Custom label given to the reader for easier identification. If no label is specified, the registration code will be used.
final String? label;

/// The location to assign the reader to.
final String? location;

/// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
final Metadata? metadata;

/// A code generated by the reader used for registering to an account.
final String registrationCode;

Map<String, dynamic> toJson() { return {
  'expand': ?expand,
  'label': ?label,
  'location': ?location,
  if (metadata != null) 'metadata': metadata?.toJson(),
  'registration_code': registrationCode,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('registration_code') && json['registration_code'] is String; } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final label$ = label;
if (label$ != null) {
  if (label$.length > 5000) errors.add('label: length must be <= 5000');
}
final location$ = location;
if (location$ != null) {
  if (location$.length > 5000) errors.add('location: length must be <= 5000');
}
if (registrationCode.length > 5000) errors.add('registrationCode: length must be <= 5000');
return errors; } 
PostTerminalReadersRequest copyWith({List<String>? Function()? expand, String? Function()? label, String? Function()? location, Metadata? Function()? metadata, String? registrationCode, }) { return PostTerminalReadersRequest(
  expand: expand != null ? expand() : this.expand,
  label: label != null ? label() : this.label,
  location: location != null ? location() : this.location,
  metadata: metadata != null ? metadata() : this.metadata,
  registrationCode: registrationCode ?? this.registrationCode,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is PostTerminalReadersRequest &&
          listEquals(expand, other.expand) &&
          label == other.label &&
          location == other.location &&
          metadata == other.metadata &&
          registrationCode == other.registrationCode; } 
@override int get hashCode { return Object.hash(Object.hashAll(expand ?? const []), label, location, metadata, registrationCode); } 
@override String toString() { return 'PostTerminalReadersRequest(expand: $expand, label: $label, location: $location, metadata: $metadata, registrationCode: $registrationCode)'; } 
 }
