// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';import 'package:pub_stripe_spec3/models/get_prices_recurring/get_prices_recurring_interval.dart';import 'package:pub_stripe_spec3/models/get_prices_recurring/usage_type.dart';import 'package:pub_stripe_spec3/models/inline_product_params.dart';import 'package:pub_stripe_spec3/models/plan/billing_scheme.dart';import 'package:pub_stripe_spec3/models/post_accounts_account_bank_accounts_id_request/metadata.dart';import 'package:pub_stripe_spec3/models/post_plans_request/post_plans_request_product.dart';import 'package:pub_stripe_spec3/models/post_plans_request/post_plans_request_tiers_mode.dart';import 'package:pub_stripe_spec3/models/post_plans_request/post_plans_request_transform_usage.dart';import 'package:pub_stripe_spec3/models/post_plans_request/tiers.dart';@immutable final class PostPlansRequest {const PostPlansRequest({required this.currency, required this.interval, this.active, this.amount, this.amountDecimal, this.billingScheme, this.expand, this.id, this.intervalCount, this.metadata, this.meter, this.nickname, this.product, this.tiers, this.tiersMode, this.transformUsage, this.trialPeriodDays, this.usageType, });

factory PostPlansRequest.fromJson(Map<String, dynamic> json) { return PostPlansRequest(
  active: json['active'] as bool?,
  amount: json['amount'] != null ? (json['amount'] as num).toInt() : null,
  amountDecimal: json['amount_decimal'] as String?,
  billingScheme: json['billing_scheme'] != null ? BillingScheme.fromJson(json['billing_scheme'] as String) : null,
  currency: json['currency'] as String,
  expand: (json['expand'] as List<dynamic>?)?.map((e) => e as String).toList(),
  id: json['id'] as String?,
  interval: GetPricesRecurringInterval.fromJson(json['interval'] as String),
  intervalCount: json['interval_count'] != null ? (json['interval_count'] as num).toInt() : null,
  metadata: json['metadata'] != null ? OneOf2.parse(json['metadata'], fromA: (v) => (v as Map<String, dynamic>).map((k, v) => MapEntry(k, v as String)), fromB: (v) => GetPaymentMethodConfigurationsApplicationVariant2.fromJson(v as String),) : null,
  meter: json['meter'] as String?,
  nickname: json['nickname'] as String?,
  product: json['product'] != null ? OneOf2.parse(json['product'], fromA: (v) => InlineProductParams.fromJson(v as Map<String, dynamic>), fromB: (v) => v as String,) : null,
  tiers: (json['tiers'] as List<dynamic>?)?.map((e) => Tiers.fromJson(e as Map<String, dynamic>)).toList(),
  tiersMode: json['tiers_mode'] != null ? PostPlansRequestTiersMode.fromJson(json['tiers_mode'] as String) : null,
  transformUsage: json['transform_usage'] != null ? PostPlansRequestTransformUsage.fromJson(json['transform_usage'] as Map<String, dynamic>) : null,
  trialPeriodDays: json['trial_period_days'] != null ? (json['trial_period_days'] as num).toInt() : null,
  usageType: json['usage_type'] != null ? UsageType.fromJson(json['usage_type'] as String) : null,
); }

/// Whether the plan is currently available for new subscriptions. Defaults to `true`.
final bool? active;

/// A positive integer in cents (or local equivalent) (or 0 for a free plan) representing how much to charge on a recurring basis.
final int? amount;

/// Same as `amount`, but accepts a decimal value with at most 12 decimal places. Only one of `amount` and `amount_decimal` can be set.
final String? amountDecimal;

/// Describes how to compute the price per period. Either `per_unit` or `tiered`. `per_unit` indicates that the fixed amount (specified in `amount`) will be charged per unit in `quantity` (for plans with `usage_type=licensed`), or per unit of total usage (for plans with `usage_type=metered`). `tiered` indicates that the unit pricing will be computed using a tiering strategy as defined using the `tiers` and `tiers_mode` attributes.
final BillingScheme? billingScheme;

/// Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
final String currency;

/// Specifies which fields in the response should be expanded.
final List<String>? expand;

/// An identifier randomly generated by Stripe. Used to identify this plan when subscribing a customer. You can optionally override this ID, but the ID must be unique across all plans in your Stripe account. You can, however, use the same plan ID in both live and test modes.
final String? id;

/// Specifies billing frequency. Either `day`, `week`, `month` or `year`.
final GetPricesRecurringInterval interval;

/// The number of intervals between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of three years interval allowed (3 years, 36 months, or 156 weeks).
final int? intervalCount;

/// Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.
final Metadata? metadata;

/// The meter tracking the usage of a metered price
final String? meter;

/// A brief description of the plan, hidden from customers.
final String? nickname;

final PostPlansRequestProduct? product;

/// Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.
final List<Tiers>? tiers;

/// Defines if the tiering price should be `graduated` or `volume` based. In `volume`-based tiering, the maximum quantity within a period determines the per unit price, in `graduated` tiering pricing can successively change as the quantity grows.
final PostPlansRequestTiersMode? tiersMode;

/// Apply a transformation to the reported usage or set quantity before computing the billed price. Cannot be combined with `tiers`.
final PostPlansRequestTransformUsage? transformUsage;

/// Default number of trial days when subscribing a customer to this plan using [`trial_from_plan=true`](https://docs.stripe.com/api#create_subscription-trial_from_plan).
final int? trialPeriodDays;

/// Configures how the quantity per period should be determined. Can be either `metered` or `licensed`. `licensed` automatically bills the `quantity` set when adding it to a subscription. `metered` aggregates the total usage based on usage records. Defaults to `licensed`.
final UsageType? usageType;

Map<String, dynamic> toJson() { return {
  'active': ?active,
  'amount': ?amount,
  'amount_decimal': ?amountDecimal,
  if (billingScheme != null) 'billing_scheme': billingScheme?.toJson(),
  'currency': currency,
  'expand': ?expand,
  'id': ?id,
  'interval': interval.toJson(),
  'interval_count': ?intervalCount,
  if (metadata != null) 'metadata': metadata?.toJson(),
  'meter': ?meter,
  'nickname': ?nickname,
  if (product != null) 'product': product?.toJson(),
  if (tiers != null) 'tiers': tiers?.map((e) => e.toJson()).toList(),
  if (tiersMode != null) 'tiers_mode': tiersMode?.toJson(),
  if (transformUsage != null) 'transform_usage': transformUsage?.toJson(),
  'trial_period_days': ?trialPeriodDays,
  if (usageType != null) 'usage_type': usageType?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('currency') && json['currency'] is String &&
      json.containsKey('interval'); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final id$ = id;
if (id$ != null) {
  if (id$.length > 5000) errors.add('id: length must be <= 5000');
}
final meter$ = meter;
if (meter$ != null) {
  if (meter$.length > 5000) errors.add('meter: length must be <= 5000');
}
final nickname$ = nickname;
if (nickname$ != null) {
  if (nickname$.length > 5000) errors.add('nickname: length must be <= 5000');
}
return errors; } 
PostPlansRequest copyWith({bool? Function()? active, int? Function()? amount, String? Function()? amountDecimal, BillingScheme? Function()? billingScheme, String? currency, List<String>? Function()? expand, String? Function()? id, GetPricesRecurringInterval? interval, int? Function()? intervalCount, Metadata? Function()? metadata, String? Function()? meter, String? Function()? nickname, PostPlansRequestProduct? Function()? product, List<Tiers>? Function()? tiers, PostPlansRequestTiersMode? Function()? tiersMode, PostPlansRequestTransformUsage? Function()? transformUsage, int? Function()? trialPeriodDays, UsageType? Function()? usageType, }) { return PostPlansRequest(
  active: active != null ? active() : this.active,
  amount: amount != null ? amount() : this.amount,
  amountDecimal: amountDecimal != null ? amountDecimal() : this.amountDecimal,
  billingScheme: billingScheme != null ? billingScheme() : this.billingScheme,
  currency: currency ?? this.currency,
  expand: expand != null ? expand() : this.expand,
  id: id != null ? id() : this.id,
  interval: interval ?? this.interval,
  intervalCount: intervalCount != null ? intervalCount() : this.intervalCount,
  metadata: metadata != null ? metadata() : this.metadata,
  meter: meter != null ? meter() : this.meter,
  nickname: nickname != null ? nickname() : this.nickname,
  product: product != null ? product() : this.product,
  tiers: tiers != null ? tiers() : this.tiers,
  tiersMode: tiersMode != null ? tiersMode() : this.tiersMode,
  transformUsage: transformUsage != null ? transformUsage() : this.transformUsage,
  trialPeriodDays: trialPeriodDays != null ? trialPeriodDays() : this.trialPeriodDays,
  usageType: usageType != null ? usageType() : this.usageType,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is PostPlansRequest &&
          active == other.active &&
          amount == other.amount &&
          amountDecimal == other.amountDecimal &&
          billingScheme == other.billingScheme &&
          currency == other.currency &&
          listEquals(expand, other.expand) &&
          id == other.id &&
          interval == other.interval &&
          intervalCount == other.intervalCount &&
          metadata == other.metadata &&
          meter == other.meter &&
          nickname == other.nickname &&
          product == other.product &&
          listEquals(tiers, other.tiers) &&
          tiersMode == other.tiersMode &&
          transformUsage == other.transformUsage &&
          trialPeriodDays == other.trialPeriodDays &&
          usageType == other.usageType;

@override int get hashCode => Object.hash(active, amount, amountDecimal, billingScheme, currency, Object.hashAll(expand ?? const []), id, interval, intervalCount, metadata, meter, nickname, product, Object.hashAll(tiers ?? const []), tiersMode, transformUsage, trialPeriodDays, usageType);

@override String toString() => 'PostPlansRequest(active: $active, amount: $amount, amountDecimal: $amountDecimal, billingScheme: $billingScheme, currency: $currency, expand: $expand, id: $id, interval: $interval, intervalCount: $intervalCount, metadata: $metadata, meter: $meter, nickname: $nickname, product: $product, tiers: $tiers, tiersMode: $tiersMode, transformUsage: $transformUsage, trialPeriodDays: $trialPeriodDays, usageType: $usageType)';

 }
