// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/SetupAttemptPaymentMethodDetailsCardPresent

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/payment_method.dart';import 'package:pub_stripe_spec3/models/payment_method_details_card_present_offline.dart';import 'package:pub_stripe_spec3/models/setup_attempt_payment_method_details_card_present/generated_card.dart';/// 
@immutable final class SetupAttemptPaymentMethodDetailsCardPresent {const SetupAttemptPaymentMethodDetailsCardPresent({this.generatedCard, this.offline, });

factory SetupAttemptPaymentMethodDetailsCardPresent.fromJson(Map<String, dynamic> json) { return SetupAttemptPaymentMethodDetailsCardPresent(
  generatedCard: json['generated_card'] != null ? OneOf2.parse(json['generated_card'], fromA: (v) => v as String, fromB: (v) => PaymentMethod.fromJson(v as Map<String, dynamic>),) : null,
  offline: json['offline'] != null ? PaymentMethodDetailsCardPresentOffline.fromJson(json['offline'] as Map<String, dynamic>) : null,
); }

/// The ID of the Card PaymentMethod which was generated by this SetupAttempt.
final GeneratedCard? generatedCard;

/// Details about payments collected offline.
final PaymentMethodDetailsCardPresentOffline? offline;

Map<String, dynamic> toJson() { return {
  if (generatedCard != null) 'generated_card': generatedCard?.toJson(),
  if (offline != null) 'offline': offline?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'generated_card', 'offline'}.contains(key)); } 
SetupAttemptPaymentMethodDetailsCardPresent copyWith({GeneratedCard? Function()? generatedCard, PaymentMethodDetailsCardPresentOffline? Function()? offline, }) { return SetupAttemptPaymentMethodDetailsCardPresent(
  generatedCard: generatedCard != null ? generatedCard() : this.generatedCard,
  offline: offline != null ? offline() : this.offline,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is SetupAttemptPaymentMethodDetailsCardPresent &&
          generatedCard == other.generatedCard &&
          offline == other.offline;

@override int get hashCode => Object.hash(generatedCard, offline);

@override String toString() => 'SetupAttemptPaymentMethodDetailsCardPresent(generatedCard: $generatedCard, offline: $offline)';

 }
