// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';/// 
@immutable final class SetupIntentPaymentMethodOptionsPaypal {const SetupIntentPaymentMethodOptionsPaypal({this.billingAgreementId});

factory SetupIntentPaymentMethodOptionsPaypal.fromJson(Map<String, dynamic> json) { return SetupIntentPaymentMethodOptionsPaypal(
  billingAgreementId: json['billing_agreement_id'] as String?,
); }

/// The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
final String? billingAgreementId;

Map<String, dynamic> toJson() { return {
  'billing_agreement_id': ?billingAgreementId,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'billing_agreement_id'}.contains(key)); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final billingAgreementId$ = billingAgreementId;
if (billingAgreementId$ != null) {
  if (billingAgreementId$.length > 5000) errors.add('billingAgreementId: length must be <= 5000');
}
return errors; } 
SetupIntentPaymentMethodOptionsPaypal copyWith({String? Function()? billingAgreementId}) { return SetupIntentPaymentMethodOptionsPaypal(
  billingAgreementId: billingAgreementId != null ? billingAgreementId() : this.billingAgreementId,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is SetupIntentPaymentMethodOptionsPaypal &&
          billingAgreementId == other.billingAgreementId;

@override int get hashCode => billingAgreementId.hashCode;

@override String toString() => 'SetupIntentPaymentMethodOptionsPaypal(billingAgreementId: $billingAgreementId)';

 }
