// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/SubscriptionsResourceSubscriptionInvoiceSettings

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/connect_account_reference.dart';import 'package:pub_stripe_spec3/models/deleted_tax_id.dart';import 'package:pub_stripe_spec3/models/invoice/invoice_account_tax_ids.dart';import 'package:pub_stripe_spec3/models/tax_id.dart';/// 
@immutable final class SubscriptionsResourceSubscriptionInvoiceSettings {const SubscriptionsResourceSubscriptionInvoiceSettings({required this.issuer, this.accountTaxIds, });

factory SubscriptionsResourceSubscriptionInvoiceSettings.fromJson(Map<String, dynamic> json) { return SubscriptionsResourceSubscriptionInvoiceSettings(
  accountTaxIds: (json['account_tax_ids'] as List<dynamic>?)?.map((e) => OneOf3.parse(e, fromA: (v) => v as String, fromB: (v) => TaxId.fromJson(v as Map<String, dynamic>), fromC: (v) => DeletedTaxId.fromJson(v as Map<String, dynamic>),)).toList(),
  issuer: ConnectAccountReference.fromJson(json['issuer'] as Map<String, dynamic>),
); }

/// The account tax IDs associated with the subscription. Will be set on invoices generated by the subscription.
final List<InvoiceAccountTaxIds>? accountTaxIds;

final ConnectAccountReference issuer;

Map<String, dynamic> toJson() { return {
  if (accountTaxIds != null) 'account_tax_ids': accountTaxIds?.map((e) => e.toJson()).toList(),
  'issuer': issuer.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('issuer'); } 
SubscriptionsResourceSubscriptionInvoiceSettings copyWith({List<InvoiceAccountTaxIds>? Function()? accountTaxIds, ConnectAccountReference? issuer, }) { return SubscriptionsResourceSubscriptionInvoiceSettings(
  accountTaxIds: accountTaxIds != null ? accountTaxIds() : this.accountTaxIds,
  issuer: issuer ?? this.issuer,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is SubscriptionsResourceSubscriptionInvoiceSettings &&
          listEquals(accountTaxIds, other.accountTaxIds) &&
          issuer == other.issuer;

@override int get hashCode => Object.hash(Object.hashAll(accountTaxIds ?? const []), issuer);

@override String toString() => 'SubscriptionsResourceSubscriptionInvoiceSettings(accountTaxIds: $accountTaxIds, issuer: $issuer)';

 }
