// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/carrier_text_param.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';typedef PostIssuingPersonalizationDesignsPersonalizationDesignRequestCarrierText = OneOf2<carrier_text_param,GetPaymentMethodConfigurationsApplicationVariant2>;
