// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_openai/models/run_step_delta_step_details_tool_calls_code_output_image_object.dart';import 'package:pub_openai/models/run_step_delta_step_details_tool_calls_code_output_logs_object.dart';typedef RunStepDeltaStepDetailsToolCallsCodeObjectCodeInterpreterOutputs = OneOf2<RunStepDeltaStepDetailsToolCallsCodeOutputLogsObject,RunStepDeltaStepDetailsToolCallsCodeOutputImageObject>;
