// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/PaymentMethodDetailsBancontact (inline: GeneratedSepaDebit)

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/payment_method.dart';/// The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
///
/// Variants:
/// - `.a` → [String]
/// - `.b` → [PaymentMethod]
typedef GeneratedSepaDebit = OneOf2<String,PaymentMethod>;
