// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/PaymentMethodDetailsBancontact (inline: GeneratedSepaDebitMandate)

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/mandate.dart';/// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
///
/// Variants:
/// - `.a` → [String]
/// - `.b` → [Mandate]
typedef GeneratedSepaDebitMandate = OneOf2<String,Mandate>;
