/// Typed union containers for OpenAPI `oneOf` / `anyOf` schemas.
///
/// Instead of generating a sealed class per union, specs emit a typedef:
/// ```dart
/// typedef FilterValue = OneOf3<String, double, bool>;
/// ```
///
/// Construction: `OneOf3.a('hello')` or `OneOf3.from('hello')`
/// Reading: `switch (v.value) { case String s: ... }`
library;

// GENERATED by scripts/generate_one_of.dart — do not edit by hand.

import 'package:meta/meta.dart';

String _oneOfError(Object? json, List<(String, Object)> errors) {
  final variants = errors.map((e) => '  ${e.$1}: ${e.$2}').join('\n');
  return 'No variant matched for value ($json):\n$variants';
}

/// Serializes a held union value to JSON. Primitives pass through;
/// lists and maps are serialized element-wise (a held `List<T>` has
/// no `toJson`, so recurse); everything else uses its `toJson()`.
Object? _oneOfValueToJson(Object? v) {
  if (v == null || v is String || v is num || v is bool) return v;
  if (v is List) return v.map(_oneOfValueToJson).toList();
  if (v is Map) {
    return v.map((k, val) => MapEntry(k, _oneOfValueToJson(val)));
  }
  return (v as dynamic).toJson();
}

// ─── OneOf2 ──────────────────────────────────────────────────────

/// Typed union of 2 variants.
@immutable
final class OneOf2<A, B> {
  const OneOf2._(this.value);

  /// Wraps a value of variant A.
  const OneOf2.a(A value) : this._(value);
  /// Wraps a value of variant B.
  const OneOf2.b(B value) : this._(value);

  /// Wraps a typed value, matching by runtime type.
  factory OneOf2.from(Object? value) {
    if (value is A) return OneOf2._(value);
    if (value is B) return OneOf2._(value);
    throw ArgumentError('Value $value is not A or B');
  }

  /// Deserializes from JSON using typed parsers.
  static OneOf2<A, B> parse<A, B>(
    Object? json, {
    required A Function(Object) fromA,
    required B Function(Object) fromB,
  }) {
    if (json is A) return OneOf2._(json);
    if (json is B) return OneOf2._(json);
    final errors = <(String, Object)>[];
    try {
      return OneOf2._(fromA(json!));
    } on Object catch (e) {
      errors.add(('$A', e));
    }
    try {
      return OneOf2._(fromB(json!));
    } on Object catch (e) {
      errors.add(('$B', e));
    }
    throw ArgumentError(_oneOfError(json, errors));
  }

  /// The wrapped value.
  final Object? value;

  /// Serializes to JSON. Primitives pass through; lists/maps are
  /// serialized element-wise; objects use `toJson()`.
  Object? toJson() => _oneOfValueToJson(value);

  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is OneOf2<A, B> && value == other.value;

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => 'OneOf2($value)';
}

// ─── OneOf3 ──────────────────────────────────────────────────────

/// Typed union of 3 variants.
@immutable
final class OneOf3<A, B, C> {
  const OneOf3._(this.value);

  /// Wraps a value of variant A.
  const OneOf3.a(A value) : this._(value);
  /// Wraps a value of variant B.
  const OneOf3.b(B value) : this._(value);
  /// Wraps a value of variant C.
  const OneOf3.c(C value) : this._(value);

  /// Wraps a typed value, matching by runtime type.
  factory OneOf3.from(Object? value) {
    if (value is A) return OneOf3._(value);
    if (value is B) return OneOf3._(value);
    if (value is C) return OneOf3._(value);
    throw ArgumentError('Value $value is not A or B or C');
  }

  /// Deserializes from JSON using typed parsers.
  static OneOf3<A, B, C> parse<A, B, C>(
    Object? json, {
    required A Function(Object) fromA,
    required B Function(Object) fromB,
    required C Function(Object) fromC,
  }) {
    if (json is A) return OneOf3._(json);
    if (json is B) return OneOf3._(json);
    if (json is C) return OneOf3._(json);
    final errors = <(String, Object)>[];
    try {
      return OneOf3._(fromA(json!));
    } on Object catch (e) {
      errors.add(('$A', e));
    }
    try {
      return OneOf3._(fromB(json!));
    } on Object catch (e) {
      errors.add(('$B', e));
    }
    try {
      return OneOf3._(fromC(json!));
    } on Object catch (e) {
      errors.add(('$C', e));
    }
    throw ArgumentError(_oneOfError(json, errors));
  }

  /// The wrapped value.
  final Object? value;

  /// Serializes to JSON. Primitives pass through; lists/maps are
  /// serialized element-wise; objects use `toJson()`.
  Object? toJson() => _oneOfValueToJson(value);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneOf3<A, B, C> && value == other.value;

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => 'OneOf3($value)';
}

// ─── OneOf4 ──────────────────────────────────────────────────────

/// Typed union of 4 variants.
@immutable
final class OneOf4<A, B, C, D> {
  const OneOf4._(this.value);

  /// Wraps a value of variant A.
  const OneOf4.a(A value) : this._(value);
  /// Wraps a value of variant B.
  const OneOf4.b(B value) : this._(value);
  /// Wraps a value of variant C.
  const OneOf4.c(C value) : this._(value);
  /// Wraps a value of variant D.
  const OneOf4.d(D value) : this._(value);

  /// Wraps a typed value, matching by runtime type.
  factory OneOf4.from(Object? value) {
    if (value is A) return OneOf4._(value);
    if (value is B) return OneOf4._(value);
    if (value is C) return OneOf4._(value);
    if (value is D) return OneOf4._(value);
    throw ArgumentError('Value $value is not A or B or C or D');
  }

  /// Deserializes from JSON using typed parsers.
  static OneOf4<A, B, C, D> parse<A, B, C, D>(
    Object? json, {
    required A Function(Object) fromA,
    required B Function(Object) fromB,
    required C Function(Object) fromC,
    required D Function(Object) fromD,
  }) {
    if (json is A) return OneOf4._(json);
    if (json is B) return OneOf4._(json);
    if (json is C) return OneOf4._(json);
    if (json is D) return OneOf4._(json);
    final errors = <(String, Object)>[];
    try {
      return OneOf4._(fromA(json!));
    } on Object catch (e) {
      errors.add(('$A', e));
    }
    try {
      return OneOf4._(fromB(json!));
    } on Object catch (e) {
      errors.add(('$B', e));
    }
    try {
      return OneOf4._(fromC(json!));
    } on Object catch (e) {
      errors.add(('$C', e));
    }
    try {
      return OneOf4._(fromD(json!));
    } on Object catch (e) {
      errors.add(('$D', e));
    }
    throw ArgumentError(_oneOfError(json, errors));
  }

  /// The wrapped value.
  final Object? value;

  /// Serializes to JSON. Primitives pass through; lists/maps are
  /// serialized element-wise; objects use `toJson()`.
  Object? toJson() => _oneOfValueToJson(value);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneOf4<A, B, C, D> && value == other.value;

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => 'OneOf4($value)';
}

// ─── OneOf5 ──────────────────────────────────────────────────────

/// Typed union of 5 variants.
@immutable
final class OneOf5<A, B, C, D, E> {
  const OneOf5._(this.value);

  /// Wraps a value of variant A.
  const OneOf5.a(A value) : this._(value);
  /// Wraps a value of variant B.
  const OneOf5.b(B value) : this._(value);
  /// Wraps a value of variant C.
  const OneOf5.c(C value) : this._(value);
  /// Wraps a value of variant D.
  const OneOf5.d(D value) : this._(value);
  /// Wraps a value of variant E.
  const OneOf5.e(E value) : this._(value);

  /// Wraps a typed value, matching by runtime type.
  factory OneOf5.from(Object? value) {
    if (value is A) return OneOf5._(value);
    if (value is B) return OneOf5._(value);
    if (value is C) return OneOf5._(value);
    if (value is D) return OneOf5._(value);
    if (value is E) return OneOf5._(value);
    throw ArgumentError('Value $value is not A or B or C or D or E');
  }

  /// Deserializes from JSON using typed parsers.
  static OneOf5<A, B, C, D, E> parse<A, B, C, D, E>(
    Object? json, {
    required A Function(Object) fromA,
    required B Function(Object) fromB,
    required C Function(Object) fromC,
    required D Function(Object) fromD,
    required E Function(Object) fromE,
  }) {
    if (json is A) return OneOf5._(json);
    if (json is B) return OneOf5._(json);
    if (json is C) return OneOf5._(json);
    if (json is D) return OneOf5._(json);
    if (json is E) return OneOf5._(json);
    final errors = <(String, Object)>[];
    try {
      return OneOf5._(fromA(json!));
    } on Object catch (e) {
      errors.add(('$A', e));
    }
    try {
      return OneOf5._(fromB(json!));
    } on Object catch (e) {
      errors.add(('$B', e));
    }
    try {
      return OneOf5._(fromC(json!));
    } on Object catch (e) {
      errors.add(('$C', e));
    }
    try {
      return OneOf5._(fromD(json!));
    } on Object catch (e) {
      errors.add(('$D', e));
    }
    try {
      return OneOf5._(fromE(json!));
    } on Object catch (e) {
      errors.add(('$E', e));
    }
    throw ArgumentError(_oneOfError(json, errors));
  }

  /// The wrapped value.
  final Object? value;

  /// Serializes to JSON. Primitives pass through; lists/maps are
  /// serialized element-wise; objects use `toJson()`.
  Object? toJson() => _oneOfValueToJson(value);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneOf5<A, B, C, D, E> && value == other.value;

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => 'OneOf5($value)';
}

// ─── OneOf6 ──────────────────────────────────────────────────────

/// Typed union of 6 variants.
@immutable
final class OneOf6<A, B, C, D, E, F> {
  const OneOf6._(this.value);

  /// Wraps a value of variant A.
  const OneOf6.a(A value) : this._(value);
  /// Wraps a value of variant B.
  const OneOf6.b(B value) : this._(value);
  /// Wraps a value of variant C.
  const OneOf6.c(C value) : this._(value);
  /// Wraps a value of variant D.
  const OneOf6.d(D value) : this._(value);
  /// Wraps a value of variant E.
  const OneOf6.e(E value) : this._(value);
  /// Wraps a value of variant F.
  const OneOf6.f(F value) : this._(value);

  /// Wraps a typed value, matching by runtime type.
  factory OneOf6.from(Object? value) {
    if (value is A) return OneOf6._(value);
    if (value is B) return OneOf6._(value);
    if (value is C) return OneOf6._(value);
    if (value is D) return OneOf6._(value);
    if (value is E) return OneOf6._(value);
    if (value is F) return OneOf6._(value);
    throw ArgumentError('Value $value is not A or B or C or D or E or F');
  }

  /// Deserializes from JSON using typed parsers.
  static OneOf6<A, B, C, D, E, F> parse<A, B, C, D, E, F>(
    Object? json, {
    required A Function(Object) fromA,
    required B Function(Object) fromB,
    required C Function(Object) fromC,
    required D Function(Object) fromD,
    required E Function(Object) fromE,
    required F Function(Object) fromF,
  }) {
    if (json is A) return OneOf6._(json);
    if (json is B) return OneOf6._(json);
    if (json is C) return OneOf6._(json);
    if (json is D) return OneOf6._(json);
    if (json is E) return OneOf6._(json);
    if (json is F) return OneOf6._(json);
    final errors = <(String, Object)>[];
    try {
      return OneOf6._(fromA(json!));
    } on Object catch (e) {
      errors.add(('$A', e));
    }
    try {
      return OneOf6._(fromB(json!));
    } on Object catch (e) {
      errors.add(('$B', e));
    }
    try {
      return OneOf6._(fromC(json!));
    } on Object catch (e) {
      errors.add(('$C', e));
    }
    try {
      return OneOf6._(fromD(json!));
    } on Object catch (e) {
      errors.add(('$D', e));
    }
    try {
      return OneOf6._(fromE(json!));
    } on Object catch (e) {
      errors.add(('$E', e));
    }
    try {
      return OneOf6._(fromF(json!));
    } on Object catch (e) {
      errors.add(('$F', e));
    }
    throw ArgumentError(_oneOfError(json, errors));
  }

  /// The wrapped value.
  final Object? value;

  /// Serializes to JSON. Primitives pass through; lists/maps are
  /// serialized element-wise; objects use `toJson()`.
  Object? toJson() => _oneOfValueToJson(value);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneOf6<A, B, C, D, E, F> && value == other.value;

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => 'OneOf6($value)';
}

// ─── OneOf7 ──────────────────────────────────────────────────────

/// Typed union of 7 variants.
@immutable
final class OneOf7<A, B, C, D, E, F, G> {
  const OneOf7._(this.value);

  /// Wraps a value of variant A.
  const OneOf7.a(A value) : this._(value);
  /// Wraps a value of variant B.
  const OneOf7.b(B value) : this._(value);
  /// Wraps a value of variant C.
  const OneOf7.c(C value) : this._(value);
  /// Wraps a value of variant D.
  const OneOf7.d(D value) : this._(value);
  /// Wraps a value of variant E.
  const OneOf7.e(E value) : this._(value);
  /// Wraps a value of variant F.
  const OneOf7.f(F value) : this._(value);
  /// Wraps a value of variant G.
  const OneOf7.g(G value) : this._(value);

  /// Wraps a typed value, matching by runtime type.
  factory OneOf7.from(Object? value) {
    if (value is A) return OneOf7._(value);
    if (value is B) return OneOf7._(value);
    if (value is C) return OneOf7._(value);
    if (value is D) return OneOf7._(value);
    if (value is E) return OneOf7._(value);
    if (value is F) return OneOf7._(value);
    if (value is G) return OneOf7._(value);
    throw ArgumentError('Value $value is not A or B or C or D or E or F or G');
  }

  /// Deserializes from JSON using typed parsers.
  static OneOf7<A, B, C, D, E, F, G> parse<A, B, C, D, E, F, G>(
    Object? json, {
    required A Function(Object) fromA,
    required B Function(Object) fromB,
    required C Function(Object) fromC,
    required D Function(Object) fromD,
    required E Function(Object) fromE,
    required F Function(Object) fromF,
    required G Function(Object) fromG,
  }) {
    if (json is A) return OneOf7._(json);
    if (json is B) return OneOf7._(json);
    if (json is C) return OneOf7._(json);
    if (json is D) return OneOf7._(json);
    if (json is E) return OneOf7._(json);
    if (json is F) return OneOf7._(json);
    if (json is G) return OneOf7._(json);
    final errors = <(String, Object)>[];
    try {
      return OneOf7._(fromA(json!));
    } on Object catch (e) {
      errors.add(('$A', e));
    }
    try {
      return OneOf7._(fromB(json!));
    } on Object catch (e) {
      errors.add(('$B', e));
    }
    try {
      return OneOf7._(fromC(json!));
    } on Object catch (e) {
      errors.add(('$C', e));
    }
    try {
      return OneOf7._(fromD(json!));
    } on Object catch (e) {
      errors.add(('$D', e));
    }
    try {
      return OneOf7._(fromE(json!));
    } on Object catch (e) {
      errors.add(('$E', e));
    }
    try {
      return OneOf7._(fromF(json!));
    } on Object catch (e) {
      errors.add(('$F', e));
    }
    try {
      return OneOf7._(fromG(json!));
    } on Object catch (e) {
      errors.add(('$G', e));
    }
    throw ArgumentError(_oneOfError(json, errors));
  }

  /// The wrapped value.
  final Object? value;

  /// Serializes to JSON. Primitives pass through; lists/maps are
  /// serialized element-wise; objects use `toJson()`.
  Object? toJson() => _oneOfValueToJson(value);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneOf7<A, B, C, D, E, F, G> && value == other.value;

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => 'OneOf7($value)';
}

// ─── OneOf8 ──────────────────────────────────────────────────────

/// Typed union of 8 variants.
@immutable
final class OneOf8<A, B, C, D, E, F, G, H> {
  const OneOf8._(this.value);

  /// Wraps a value of variant A.
  const OneOf8.a(A value) : this._(value);
  /// Wraps a value of variant B.
  const OneOf8.b(B value) : this._(value);
  /// Wraps a value of variant C.
  const OneOf8.c(C value) : this._(value);
  /// Wraps a value of variant D.
  const OneOf8.d(D value) : this._(value);
  /// Wraps a value of variant E.
  const OneOf8.e(E value) : this._(value);
  /// Wraps a value of variant F.
  const OneOf8.f(F value) : this._(value);
  /// Wraps a value of variant G.
  const OneOf8.g(G value) : this._(value);
  /// Wraps a value of variant H.
  const OneOf8.h(H value) : this._(value);

  /// Wraps a typed value, matching by runtime type.
  factory OneOf8.from(Object? value) {
    if (value is A) return OneOf8._(value);
    if (value is B) return OneOf8._(value);
    if (value is C) return OneOf8._(value);
    if (value is D) return OneOf8._(value);
    if (value is E) return OneOf8._(value);
    if (value is F) return OneOf8._(value);
    if (value is G) return OneOf8._(value);
    if (value is H) return OneOf8._(value);
    throw ArgumentError(
      'Value $value is not A or B or C or D or E or F or G or H',
    );
  }

  /// Deserializes from JSON using typed parsers.
  static OneOf8<A, B, C, D, E, F, G, H> parse<A, B, C, D, E, F, G, H>(
    Object? json, {
    required A Function(Object) fromA,
    required B Function(Object) fromB,
    required C Function(Object) fromC,
    required D Function(Object) fromD,
    required E Function(Object) fromE,
    required F Function(Object) fromF,
    required G Function(Object) fromG,
    required H Function(Object) fromH,
  }) {
    if (json is A) return OneOf8._(json);
    if (json is B) return OneOf8._(json);
    if (json is C) return OneOf8._(json);
    if (json is D) return OneOf8._(json);
    if (json is E) return OneOf8._(json);
    if (json is F) return OneOf8._(json);
    if (json is G) return OneOf8._(json);
    if (json is H) return OneOf8._(json);
    final errors = <(String, Object)>[];
    try {
      return OneOf8._(fromA(json!));
    } on Object catch (e) {
      errors.add(('$A', e));
    }
    try {
      return OneOf8._(fromB(json!));
    } on Object catch (e) {
      errors.add(('$B', e));
    }
    try {
      return OneOf8._(fromC(json!));
    } on Object catch (e) {
      errors.add(('$C', e));
    }
    try {
      return OneOf8._(fromD(json!));
    } on Object catch (e) {
      errors.add(('$D', e));
    }
    try {
      return OneOf8._(fromE(json!));
    } on Object catch (e) {
      errors.add(('$E', e));
    }
    try {
      return OneOf8._(fromF(json!));
    } on Object catch (e) {
      errors.add(('$F', e));
    }
    try {
      return OneOf8._(fromG(json!));
    } on Object catch (e) {
      errors.add(('$G', e));
    }
    try {
      return OneOf8._(fromH(json!));
    } on Object catch (e) {
      errors.add(('$H', e));
    }
    throw ArgumentError(_oneOfError(json, errors));
  }

  /// The wrapped value.
  final Object? value;

  /// Serializes to JSON. Primitives pass through; lists/maps are
  /// serialized element-wise; objects use `toJson()`.
  Object? toJson() => _oneOfValueToJson(value);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneOf8<A, B, C, D, E, F, G, H> && value == other.value;

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => 'OneOf8($value)';
}

// ─── OneOf9 ──────────────────────────────────────────────────────

/// Typed union of 9 variants.
@immutable
final class OneOf9<A, B, C, D, E, F, G, H, I> {
  const OneOf9._(this.value);

  /// Wraps a value of variant A.
  const OneOf9.a(A value) : this._(value);
  /// Wraps a value of variant B.
  const OneOf9.b(B value) : this._(value);
  /// Wraps a value of variant C.
  const OneOf9.c(C value) : this._(value);
  /// Wraps a value of variant D.
  const OneOf9.d(D value) : this._(value);
  /// Wraps a value of variant E.
  const OneOf9.e(E value) : this._(value);
  /// Wraps a value of variant F.
  const OneOf9.f(F value) : this._(value);
  /// Wraps a value of variant G.
  const OneOf9.g(G value) : this._(value);
  /// Wraps a value of variant H.
  const OneOf9.h(H value) : this._(value);
  /// Wraps a value of variant I.
  const OneOf9.i(I value) : this._(value);

  /// Wraps a typed value, matching by runtime type.
  factory OneOf9.from(Object? value) {
    if (value is A) return OneOf9._(value);
    if (value is B) return OneOf9._(value);
    if (value is C) return OneOf9._(value);
    if (value is D) return OneOf9._(value);
    if (value is E) return OneOf9._(value);
    if (value is F) return OneOf9._(value);
    if (value is G) return OneOf9._(value);
    if (value is H) return OneOf9._(value);
    if (value is I) return OneOf9._(value);
    throw ArgumentError(
      'Value $value is not A or B or C or D or E or F or G or H or I',
    );
  }

  /// Deserializes from JSON using typed parsers.
  static OneOf9<A, B, C, D, E, F, G, H, I> parse<A, B, C, D, E, F, G, H, I>(
    Object? json, {
    required A Function(Object) fromA,
    required B Function(Object) fromB,
    required C Function(Object) fromC,
    required D Function(Object) fromD,
    required E Function(Object) fromE,
    required F Function(Object) fromF,
    required G Function(Object) fromG,
    required H Function(Object) fromH,
    required I Function(Object) fromI,
  }) {
    if (json is A) return OneOf9._(json);
    if (json is B) return OneOf9._(json);
    if (json is C) return OneOf9._(json);
    if (json is D) return OneOf9._(json);
    if (json is E) return OneOf9._(json);
    if (json is F) return OneOf9._(json);
    if (json is G) return OneOf9._(json);
    if (json is H) return OneOf9._(json);
    if (json is I) return OneOf9._(json);
    final errors = <(String, Object)>[];
    try {
      return OneOf9._(fromA(json!));
    } on Object catch (e) {
      errors.add(('$A', e));
    }
    try {
      return OneOf9._(fromB(json!));
    } on Object catch (e) {
      errors.add(('$B', e));
    }
    try {
      return OneOf9._(fromC(json!));
    } on Object catch (e) {
      errors.add(('$C', e));
    }
    try {
      return OneOf9._(fromD(json!));
    } on Object catch (e) {
      errors.add(('$D', e));
    }
    try {
      return OneOf9._(fromE(json!));
    } on Object catch (e) {
      errors.add(('$E', e));
    }
    try {
      return OneOf9._(fromF(json!));
    } on Object catch (e) {
      errors.add(('$F', e));
    }
    try {
      return OneOf9._(fromG(json!));
    } on Object catch (e) {
      errors.add(('$G', e));
    }
    try {
      return OneOf9._(fromH(json!));
    } on Object catch (e) {
      errors.add(('$H', e));
    }
    try {
      return OneOf9._(fromI(json!));
    } on Object catch (e) {
      errors.add(('$I', e));
    }
    throw ArgumentError(_oneOfError(json, errors));
  }

  /// The wrapped value.
  final Object? value;

  /// Serializes to JSON. Primitives pass through; lists/maps are
  /// serialized element-wise; objects use `toJson()`.
  Object? toJson() => _oneOfValueToJson(value);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OneOf9<A, B, C, D, E, F, G, H, I> && value == other.value;

  @override
  int get hashCode => value.hashCode;

  @override
  String toString() => 'OneOf9($value)';
}
