/// Generates packages/degenerate_runtime/lib/src/one_of.dart
///
/// Run: dart run scripts/generate_one_of.dart
import 'dart:io';

const maxArity = 9;
const letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'];

void main() {
  final buf = StringBuffer();

  buf.writeln(
    '/// Typed union containers for OpenAPI `oneOf` / `anyOf` schemas.',
  );
  buf.writeln('///');
  buf.writeln(
    '/// Instead of generating a sealed class per union, specs emit a typedef:',
  );
  buf.writeln('/// ```dart');
  buf.writeln('/// typedef FilterValue = OneOf3<String, double, bool>;');
  buf.writeln('/// ```');
  buf.writeln('///');
  buf.writeln(
    '/// Construction: `OneOf3.a(\'hello\')` or `OneOf3.from(\'hello\')`',
  );
  buf.writeln('/// Reading: `switch (v.value) { case String s: ... }`');
  buf.writeln('library;');
  buf.writeln();
  buf.writeln(
    "// GENERATED by scripts/generate_one_of.dart — do not edit by hand.",
  );
  buf.writeln();
  buf.writeln("import 'package:meta/meta.dart';");
  buf.writeln();
  buf.writeln(
    'String _oneOfError(Object? json, List<(String, Object)> errors) {',
  );
  buf.writeln(
    "  final variants = errors.map((e) => '  \${e.\$1}: \${e.\$2}').join('\\n');",
  );
  buf.writeln(
    "  return 'No variant matched for value (\$json):\\n\$variants';",
  );
  buf.writeln('}');
  buf.writeln();
  buf.writeln(
    '/// Serializes a held union value to JSON. Primitives pass through;',
  );
  buf.writeln(
    '/// lists and maps are serialized element-wise (a held `List<T>` has',
  );
  buf.writeln(
    '/// no `toJson`, so recurse); everything else uses its `toJson()`.',
  );
  buf.writeln('Object? _oneOfValueToJson(Object? v) {');
  buf.writeln(
    '  if (v == null || v is String || v is num || v is bool) return v;',
  );
  buf.writeln('  if (v is List) return v.map(_oneOfValueToJson).toList();');
  buf.writeln('  if (v is Map) {');
  buf.writeln(
    '    return v.map((k, val) => MapEntry(k, _oneOfValueToJson(val)));',
  );
  buf.writeln('  }');
  buf.writeln('  return (v as dynamic).toJson();');
  buf.writeln('}');
  buf.writeln();
  buf.writeln('/// Scores how well a parsed variant [value] matches [json], to');
  buf.writeln('/// pick the best `oneOf` candidate. For an object payload: the');
  buf.writeln('/// number of input keys the variant reproduces (a looser variant');
  buf.writeln('/// that ignores keys scores lower). For a scalar/list payload: 1');
  buf.writeln('/// when the value matches without coercion, else 0 — so an exact');
  buf.writeln('/// `int` beats a variant that stringified it. Defensive: a value');
  buf.writeln('/// without `toJson` scores 0 rather than disqualifying the parse.');
  buf.writeln('int _oneOfMatchScore(Object? json, Object? value) {');
  buf.writeln('  if (json is Map) {');
  buf.writeln('    Object? encoded;');
  buf.writeln('    try {');
  buf.writeln('      encoded = _oneOfValueToJson(value);');
  buf.writeln('    } on Object {');
  buf.writeln('      return 0;');
  buf.writeln('    }');
  buf.writeln('    if (encoded is! Map) return 0;');
  buf.writeln('    var covered = 0;');
  buf.writeln('    for (final key in json.keys) {');
  buf.writeln('      if (encoded.containsKey(key)) covered++;');
  buf.writeln('    }');
  buf.writeln('    return covered;');
  buf.writeln('  }');
  buf.writeln('  return identical(value, json) || value == json ? 1 : 0;');
  buf.writeln('}');

  for (var n = 2; n <= maxArity; n++) {
    _writeOneOf(buf, n);
  }

  final outPath = 'packages/degenerate_runtime/lib/src/one_of.dart';
  File(outPath).writeAsStringSync(buf.toString());
  print('Wrote $outPath (${buf.length} chars)');
}

void _writeOneOf(StringBuffer buf, int n) {
  final typeParams = letters.sublist(0, n).join(', ');
  final cls = 'OneOf$n<$typeParams>';

  buf.writeln();
  buf.writeln('// ─── OneOf$n ${'─' * (60 - 'OneOf$n'.length)}');
  buf.writeln();
  buf.writeln('/// Typed union of $n variants.');
  buf.writeln('@immutable');
  buf.writeln('final class $cls {');

  // Private const constructor
  buf.writeln('  const OneOf$n._(this.value, this._index);');
  buf.writeln();

  // Named variant constructors
  for (var i = 0; i < n; i++) {
    final letter = letters[i].toLowerCase();
    final type = letters[i];
    buf.writeln('  /// Wraps a value of variant $type.');
    buf.writeln('  const OneOf$n.$letter($type value) : this._(value, $i);');
  }
  buf.writeln();

  // .from() factory
  buf.writeln('  /// Wraps a typed value, matching by runtime type.');
  buf.writeln('  factory OneOf$n.from(Object? value) {');
  for (var i = 0; i < n; i++) {
    buf.writeln('    if (value is ${letters[i]}) return OneOf$n._(value, $i);');
  }
  final throwMsg = "Value \$value is not ${letters.sublist(0, n).join(' or ')}";
  final throwLine = "    throw ArgumentError('$throwMsg');";
  if (throwLine.length > 80) {
    buf.writeln('    throw ArgumentError(');
    buf.writeln("      '$throwMsg',");
    buf.writeln('    );');
  } else {
    buf.writeln(throwLine);
  }
  buf.writeln('  }');
  buf.writeln();

  // parse() static method
  final parseTypeParams = letters.sublist(0, n).join(', ');
  buf.writeln('  /// Deserializes from JSON using typed parsers.');
  buf.writeln('  ///');
  buf.writeln(
    '  /// [greedy] marks variant indices that accept any payload (free-form',
  );
  buf.writeln(
    '  /// maps, `dynamic`, models capturing `additionalProperties`). They',
  );
  buf.writeln(
    '  /// only compete when no non-greedy variant parses — otherwise a',
  );
  buf.writeln(
    '  /// backward-compatible server change (a new field) would flip the',
  );
  buf.writeln(
    '  /// parsed variant to the greedy one by sheer key coverage.',
  );
  buf.writeln('  static $cls parse<$parseTypeParams>(');
  buf.writeln('    Object? json, {');
  for (var i = 0; i < n; i++) {
    buf.writeln(
      '    required ${letters[i]} Function(Object) from${letters[i]},',
    );
  }
  buf.writeln('    Set<int> greedy = const {},');
  buf.writeln('  }) {');
  // Best-match dispatch: try every variant, keep the one whose serialized form
  // covers the most of the input's keys. `oneOf` means exactly one schema
  // matches, but generated fromJson is lenient (ignores unknown keys), so a
  // looser variant (its required fields a subset of a richer sibling's) would
  // otherwise win under first-match and silently drop the extra data. Scoring
  // by key coverage picks the variant that actually accounts for the payload;
  // ties keep the earliest (most-specific — see orderUnionVariants) variant.
  buf.writeln('    final errors = <(String, Object)>[];');
  buf.writeln('    $cls? best;');
  buf.writeln('    var bestScore = -1;');
  buf.writeln('    $cls? bestGreedy;');
  buf.writeln('    var bestGreedyScore = -1;');
  for (var i = 0; i < n; i++) {
    buf.writeln('    try {');
    buf.writeln(
      '      final v = OneOf$n<$parseTypeParams>._(from${letters[i]}(json!), $i);',
    );
    buf.writeln('      final score = _oneOfMatchScore(json, v.value);');
    buf.writeln('      if (greedy.contains($i)) {');
    buf.writeln('        if (score > bestGreedyScore) {');
    buf.writeln('          bestGreedyScore = score;');
    buf.writeln('          bestGreedy = v;');
    buf.writeln('        }');
    buf.writeln('      } else if (score > bestScore) {');
    buf.writeln('        bestScore = score;');
    buf.writeln('        best = v;');
    buf.writeln('      }');
    // Catch Object, not just Exception: a variant's fromJson discriminates by
    // casting (e.g. `json['x'] as String`), which throws a TypeError — an
    // Error, not an Exception — when the payload is a different variant. An
    // `on Exception` guard lets that escape and aborts the whole parse instead
    // of trying the next variant.
    buf.writeln('    } on Object catch (e) {');
    buf.writeln("      errors.add(('\$${letters[i]}', e));");
    buf.writeln('    }');
  }
  buf.writeln('    if (best != null) return best;');
  buf.writeln('    if (bestGreedy != null) return bestGreedy;');
  buf.writeln('    throw ArgumentError(_oneOfError(json, errors));');
  buf.writeln('  }');
  buf.writeln();

  // value + index fields
  buf.writeln('  /// The wrapped value.');
  buf.writeln('  final Object? value;');
  buf.writeln();
  buf.writeln('  /// The variant index (0-based).');
  buf.writeln('  final int _index;');
  buf.writeln();

  // isX getters
  for (var i = 0; i < n; i++) {
    final letter = letters[i].toLowerCase();
    buf.writeln(
      '  /// Whether this holds variant ${letters[i]}.',
    );
    buf.writeln('  bool get is${letters[i]} => _index == $i;');
  }
  buf.writeln();

  // typed accessors
  for (var i = 0; i < n; i++) {
    final letter = letters[i].toLowerCase();
    buf.writeln(
      '  /// The value as ${letters[i]}, or `null` if this is a different variant.',
    );
    buf.writeln(
      '  ${letters[i]}? get ${letter}OrNull => _index == $i ? value as ${letters[i]} : null;',
    );
  }
  buf.writeln();

  // when() exhaustive callback
  buf.writeln('  /// Exhaustive pattern match on the variant.');
  buf.write('  R when<R>({');
  for (var i = 0; i < n; i++) {
    buf.write('required R Function(${letters[i]}) ${letters[i].toLowerCase()}, ');
  }
  buf.writeln('}) {');
  buf.writeln('    return switch (_index) {');
  for (var i = 0; i < n; i++) {
    buf.writeln(
      '      $i => ${letters[i].toLowerCase()}(value as ${letters[i]}),',
    );
  }
  buf.writeln("      _ => throw StateError('Invalid variant index: \$_index'),");
  buf.writeln('    };');
  buf.writeln('  }');
  buf.writeln();

  // toJson
  buf.writeln(
    '  /// Serializes to JSON. Primitives pass through; lists/maps are',
  );
  buf.writeln('  /// serialized element-wise; objects use `toJson()`.');
  buf.writeln('  Object? toJson() => _oneOfValueToJson(value);');
  buf.writeln();

  // ==, hashCode, toString
  buf.writeln('  @override');
  buf.writeln('  bool operator ==(Object other) =>');
  buf.writeln('      identical(this, other) ||');
  buf.writeln(
    '      other is $cls && _index == other._index && value == other.value;',
  );
  buf.writeln();
  buf.writeln('  @override');
  buf.writeln('  int get hashCode => Object.hash(_index, value);');
  buf.writeln();
  final toStringLetters = letters.sublist(0, n).map((l) => "'${l.toLowerCase()}'").join(', ');
  buf.writeln('  static const _labels = [$toStringLetters];');
  buf.writeln();
  buf.writeln('  @override');
  buf.writeln("  String toString() => 'OneOf$n.\${_labels[_index]}(\$value)';");

  buf.writeln('}');
}
