// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/AccessSchemasIdentityProviders

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_cloudflare/models/access_schemas_identity_provider.dart';typedef AccessSchemasIdentityProviders = OneOf8<AccessSchemasIdentityProvider,AccessSchemasIdentityProvider,AccessSchemasIdentityProvider,AccessSchemasIdentityProvider,AccessSchemasIdentityProvider,AccessSchemasIdentityProvider,AccessSchemasIdentityProvider,AccessSchemasIdentityProvider>;
