// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/DnssecDnssecMultiSigner

/// If true, multi-signer DNSSEC is enabled on the zone, allowing multiple
/// providers to serve a DNSSEC-signed zone at the same time.
/// This is required for DNSKEY records (except those automatically
/// generated by Cloudflare) to be added to the zone.
/// 
/// See [Multi-signer DNSSEC](https://developers.cloudflare.com/dns/dnssec/multi-signer-dnssec/) for details.
extension type const DnssecDnssecMultiSigner(bool value) {
factory DnssecDnssecMultiSigner.fromJson(bool json) => DnssecDnssecMultiSigner(json);

bool toJson() => value;

}
