// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/DnssecEditDnssecStatusRequest

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_cloudflare/models/dnssec_dnssec_multi_signer.dart';import 'package:pub_cloudflare/models/dnssec_dnssec_presigned.dart';import 'package:pub_cloudflare/models/dnssec_dnssec_use_nsec3.dart';/// Status of DNSSEC, based on user-desired state and presence of necessary records.
@immutable final class DnssecEditDnssecStatusRequestStatus {const DnssecEditDnssecStatusRequestStatus._(this.value);

factory DnssecEditDnssecStatusRequestStatus.fromJson(String json) { return switch (json) {
  'active' => active,
  'disabled' => disabled,
  _ => DnssecEditDnssecStatusRequestStatus._(json),
}; }

static const DnssecEditDnssecStatusRequestStatus active = DnssecEditDnssecStatusRequestStatus._('active');

static const DnssecEditDnssecStatusRequestStatus disabled = DnssecEditDnssecStatusRequestStatus._('disabled');

static const List<DnssecEditDnssecStatusRequestStatus> values = [active, disabled];

final String value;

String toJson() { return value; } 
/// The Dart identifier name for this value, or the raw value if unknown.
String get name { return switch (value) {
  'active' => 'active',
  'disabled' => 'disabled',
  _ => value,
}; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) => identical(this, other) ||
    other is DnssecEditDnssecStatusRequestStatus && other.value == value;

@override int get hashCode => value.hashCode;

@override String toString() => 'DnssecEditDnssecStatusRequestStatus($value)';

 }
@immutable final class DnssecEditDnssecStatusRequest {const DnssecEditDnssecStatusRequest({this.dnssecMultiSigner, this.dnssecPresigned, this.dnssecUseNsec3, this.status, });

factory DnssecEditDnssecStatusRequest.fromJson(Map<String, dynamic> json) { return DnssecEditDnssecStatusRequest(
  dnssecMultiSigner: json['dnssec_multi_signer'] != null ? DnssecDnssecMultiSigner.fromJson(json['dnssec_multi_signer'] as bool) : null,
  dnssecPresigned: json['dnssec_presigned'] != null ? DnssecDnssecPresigned.fromJson(json['dnssec_presigned'] as bool) : null,
  dnssecUseNsec3: json['dnssec_use_nsec3'] != null ? DnssecDnssecUseNsec3.fromJson(json['dnssec_use_nsec3'] as bool) : null,
  status: json['status'] != null ? DnssecEditDnssecStatusRequestStatus.fromJson(json['status'] as String) : null,
); }

/// If true, multi-signer DNSSEC is enabled on the zone, allowing multiple
/// providers to serve a DNSSEC-signed zone at the same time.
/// This is required for DNSKEY records (except those automatically
/// generated by Cloudflare) to be added to the zone.
/// 
/// See [Multi-signer DNSSEC](https://developers.cloudflare.com/dns/dnssec/multi-signer-dnssec/) for details.
final DnssecDnssecMultiSigner? dnssecMultiSigner;

/// If true, allows Cloudflare to transfer in a DNSSEC-signed zone
/// including signatures from an external provider, without requiring
/// Cloudflare to sign any records on the fly.
/// 
/// Note that this feature has some limitations.
/// See [Cloudflare as Secondary](https://developers.cloudflare.com/dns/zone-setups/zone-transfers/cloudflare-as-secondary/setup/#dnssec) for details.
final DnssecDnssecPresigned? dnssecPresigned;

/// If true, enables the use of NSEC3 together with DNSSEC on the zone.
/// Combined with setting dnssec_presigned to true, this enables the use of
/// NSEC3 records when transferring in from an external provider.
/// If dnssec_presigned is instead set to false (default), NSEC3 records will be
/// generated and signed at request time.
/// 
/// See [DNSSEC with NSEC3](https://developers.cloudflare.com/dns/dnssec/enable-nsec3/) for details.
final DnssecDnssecUseNsec3? dnssecUseNsec3;

/// Status of DNSSEC, based on user-desired state and presence of necessary records.
/// 
/// Example: `'active'`
final DnssecEditDnssecStatusRequestStatus? status;

Map<String, dynamic> toJson() { return {
  if (dnssecMultiSigner != null) 'dnssec_multi_signer': dnssecMultiSigner?.toJson(),
  if (dnssecPresigned != null) 'dnssec_presigned': dnssecPresigned?.toJson(),
  if (dnssecUseNsec3 != null) 'dnssec_use_nsec3': dnssecUseNsec3?.toJson(),
  if (status != null) 'status': status?.toJson(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'dnssec_multi_signer', 'dnssec_presigned', 'dnssec_use_nsec3', 'status'}.contains(key)); } 
DnssecEditDnssecStatusRequest copyWith({DnssecDnssecMultiSigner? Function()? dnssecMultiSigner, DnssecDnssecPresigned? Function()? dnssecPresigned, DnssecDnssecUseNsec3? Function()? dnssecUseNsec3, DnssecEditDnssecStatusRequestStatus? Function()? status, }) { return DnssecEditDnssecStatusRequest(
  dnssecMultiSigner: dnssecMultiSigner != null ? dnssecMultiSigner() : this.dnssecMultiSigner,
  dnssecPresigned: dnssecPresigned != null ? dnssecPresigned() : this.dnssecPresigned,
  dnssecUseNsec3: dnssecUseNsec3 != null ? dnssecUseNsec3() : this.dnssecUseNsec3,
  status: status != null ? status() : this.status,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is DnssecEditDnssecStatusRequest &&
          dnssecMultiSigner == other.dnssecMultiSigner &&
          dnssecPresigned == other.dnssecPresigned &&
          dnssecUseNsec3 == other.dnssecUseNsec3 &&
          status == other.status;

@override int get hashCode => Object.hash(dnssecMultiSigner, dnssecPresigned, dnssecUseNsec3, status);

@override String toString() => 'DnssecEditDnssecStatusRequest(dnssecMultiSigner: $dnssecMultiSigner, dnssecPresigned: $dnssecPresigned, dnssecUseNsec3: $dnssecUseNsec3, status: $status)';

 }
