// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/RealtimekitParticipant

import 'package:degenerate_runtime/degenerate_runtime.dart';/// Represents a participant.
@immutable final class RealtimekitParticipant {const RealtimekitParticipant({required this.createdAt, required this.customParticipantId, required this.id, required this.presetName, required this.updatedAt, this.name, this.picture, });

factory RealtimekitParticipant.fromJson(Map<String, dynamic> json) { return RealtimekitParticipant(
  createdAt: DateTime.parse(json['created_at'] as String),
  customParticipantId: json['custom_participant_id'] as String,
  id: json['id'] as String,
  name: json['name'] as String?,
  picture: json['picture'] != null ? Uri.parse(json['picture'] as String) : null,
  presetName: json['preset_name'] as String,
  updatedAt: DateTime.parse(json['updated_at'] as String),
); }

/// When this object was created. The time is returned in ISO format.
final DateTime createdAt;

/// A unique participant ID generated by the client.
final String customParticipantId;

/// ID of the participant.
final String id;

/// Name of the participant.
final String? name;

/// URL to a picture of the participant.
final Uri? picture;

/// Preset applied to the participant.
final String presetName;

/// When this object was updated. The time is returned in ISO format.
final DateTime updatedAt;

Map<String, dynamic> toJson() { return {
  'created_at': createdAt.toIso8601String(),
  'custom_participant_id': customParticipantId,
  'id': id,
  'name': ?name,
  if (picture != null) 'picture': picture?.toString(),
  'preset_name': presetName,
  'updated_at': updatedAt.toIso8601String(),
}; } 
static bool canParse(Map<String, dynamic> json) { return json.containsKey('created_at') && json['created_at'] is String &&
      json.containsKey('custom_participant_id') && json['custom_participant_id'] is String &&
      json.containsKey('id') && json['id'] is String &&
      json.containsKey('preset_name') && json['preset_name'] is String &&
      json.containsKey('updated_at') && json['updated_at'] is String; } 
RealtimekitParticipant copyWith({DateTime? createdAt, String? customParticipantId, String? id, String? Function()? name, Uri? Function()? picture, String? presetName, DateTime? updatedAt, }) { return RealtimekitParticipant(
  createdAt: createdAt ?? this.createdAt,
  customParticipantId: customParticipantId ?? this.customParticipantId,
  id: id ?? this.id,
  name: name != null ? name() : this.name,
  picture: picture != null ? picture() : this.picture,
  presetName: presetName ?? this.presetName,
  updatedAt: updatedAt ?? this.updatedAt,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is RealtimekitParticipant &&
          createdAt == other.createdAt &&
          customParticipantId == other.customParticipantId &&
          id == other.id &&
          name == other.name &&
          picture == other.picture &&
          presetName == other.presetName &&
          updatedAt == other.updatedAt;

@override int get hashCode => Object.hash(createdAt, customParticipantId, id, name, picture, presetName, updatedAt);

@override String toString() => 'RealtimekitParticipant(createdAt: $createdAt, customParticipantId: $customParticipantId, id: $id, name: $name, picture: $picture, presetName: $presetName, updatedAt: $updatedAt)';

 }
