// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_cloudflare/models/zones_zone_settings_single_request/zones_zone_settings_single_request_variant1.dart';import 'package:pub_cloudflare/models/zones_zone_settings_single_request/zones_zone_settings_single_request_variant2.dart';typedef ZonesZoneSettingsSingleRequest = OneOf2<ZonesZoneSettingsSingleRequestVariant1,ZonesZoneSettingsSingleRequestVariant2>;
