// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';import 'package:pub_stripe_spec3/models/post_invoices_invoice_request/post_invoices_invoice_request_custom_fields_variant1.dart';typedef PostInvoicesInvoiceRequestCustomFields = OneOf2<GetPaymentMethodConfigurationsApplicationVariant2,List<PostInvoicesInvoiceRequestCustomFieldsVariant1>>;
