// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/CompletionUsage (inline: CompletionTokensDetails)

import 'package:degenerate_runtime/degenerate_runtime.dart';/// Breakdown of tokens used in a completion.
@immutable final class CompletionTokensDetails {const CompletionTokensDetails({this.acceptedPredictionTokens = 0, this.audioTokens = 0, this.reasoningTokens = 0, this.rejectedPredictionTokens = 0, });

factory CompletionTokensDetails.fromJson(Map<String, dynamic> json) { return CompletionTokensDetails(
  acceptedPredictionTokens: json.containsKey('accepted_prediction_tokens') ? (json['accepted_prediction_tokens'] as num).toInt() : 0,
  audioTokens: json.containsKey('audio_tokens') ? (json['audio_tokens'] as num).toInt() : 0,
  reasoningTokens: json.containsKey('reasoning_tokens') ? (json['reasoning_tokens'] as num).toInt() : 0,
  rejectedPredictionTokens: json.containsKey('rejected_prediction_tokens') ? (json['rejected_prediction_tokens'] as num).toInt() : 0,
); }

/// When using Predicted Outputs, the number of tokens in the
/// prediction that appeared in the completion.
/// 
final int acceptedPredictionTokens;

/// Audio input tokens generated by the model.
final int audioTokens;

/// Tokens generated by the model for reasoning.
final int reasoningTokens;

/// When using Predicted Outputs, the number of tokens in the
/// prediction that did not appear in the completion. However, like
/// reasoning tokens, these tokens are still counted in the total
/// completion tokens for purposes of billing, output, and context window
/// limits.
/// 
final int rejectedPredictionTokens;

Map<String, dynamic> toJson() { return {
  'accepted_prediction_tokens': acceptedPredictionTokens,
  'audio_tokens': audioTokens,
  'reasoning_tokens': reasoningTokens,
  'rejected_prediction_tokens': rejectedPredictionTokens,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'accepted_prediction_tokens', 'audio_tokens', 'reasoning_tokens', 'rejected_prediction_tokens'}.contains(key)); } 
CompletionTokensDetails copyWith({int Function()? acceptedPredictionTokens, int Function()? audioTokens, int Function()? reasoningTokens, int Function()? rejectedPredictionTokens, }) { return CompletionTokensDetails(
  acceptedPredictionTokens: acceptedPredictionTokens != null ? acceptedPredictionTokens() : this.acceptedPredictionTokens,
  audioTokens: audioTokens != null ? audioTokens() : this.audioTokens,
  reasoningTokens: reasoningTokens != null ? reasoningTokens() : this.reasoningTokens,
  rejectedPredictionTokens: rejectedPredictionTokens != null ? rejectedPredictionTokens() : this.rejectedPredictionTokens,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is CompletionTokensDetails &&
          acceptedPredictionTokens == other.acceptedPredictionTokens &&
          audioTokens == other.audioTokens &&
          reasoningTokens == other.reasoningTokens &&
          rejectedPredictionTokens == other.rejectedPredictionTokens;

@override int get hashCode => Object.hash(acceptedPredictionTokens, audioTokens, reasoningTokens, rejectedPredictionTokens);

@override String toString() => 'CompletionTokensDetails(acceptedPredictionTokens: $acceptedPredictionTokens, audioTokens: $audioTokens, reasoningTokens: $reasoningTokens, rejectedPredictionTokens: $rejectedPredictionTokens)';

 }
