// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/get_payment_method_configurations_application/get_payment_method_configurations_application_variant2.dart';import 'package:pub_stripe_spec3/models/payment_method_options_param/payment_method_options_param_subscriptions_variant1.dart';typedef Payment_method_options_paramSubscriptions = OneOf2<List<Payment_method_options_paramSubscriptionsVariant1>,GetPaymentMethodConfigurationsApplicationVariant2>;
