// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_stripe_spec3/models/setup_intent_payment_method_options_amazon_pay.dart';import 'package:pub_stripe_spec3/models/setup_intent_type_specific_payment_method_options_client.dart';typedef SetupIntentPaymentMethodOptionsAmazonPay2 = OneOf2<SetupIntentPaymentMethodOptionsAmazonPay,SetupIntentTypeSpecificPaymentMethodOptionsClient>;
