// GENERATED CODE - DO NOT MODIFY BY HAND

import 'dart:convert';import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_cloudflare/models/response_common_failure4.dart';sealed class AccessApplicationsAddAnApplicationError {const AccessApplicationsAddAnApplicationError();

factory AccessApplicationsAddAnApplicationError.fromResponse(ApiResponse response) {     try {
      return switch (response.statusCode) {
        _ when response.statusCode >= 400 && response.statusCode <= 499 => AccessApplicationsAddAnApplicationError$4XX(ResponseCommonFailure4.fromJson(jsonDecode(response.body) as Map<String, dynamic>), response.statusCode),
        _ => AccessApplicationsAddAnApplicationError$Unknown(response.statusCode, response.body),
      };
    } on Object {
      return AccessApplicationsAddAnApplicationError$Unknown(response.statusCode, response.body);
    } }

int get statusCode;
Object? get typedError => null;

 }
final class AccessApplicationsAddAnApplicationError$4XX extends AccessApplicationsAddAnApplicationError {const AccessApplicationsAddAnApplicationError$4XX(this.error, this.statusCode, );

final ResponseCommonFailure4 error;

@override final int statusCode;

@override Object get typedError => error;

 }
final class AccessApplicationsAddAnApplicationError$Unknown extends AccessApplicationsAddAnApplicationError {const AccessApplicationsAddAnApplicationError$Unknown(this.statusCode, this.rawBody, );

@override final int statusCode;

final String? rawBody;

 }
typedef AccessApplicationsDeleteAnAccessApplicationError = AccessApplicationsAddAnApplicationError;
typedef AccessApplicationsGetAnAccessApplicationError = AccessApplicationsAddAnApplicationError;
typedef AccessApplicationsListAccessApplicationsError = AccessApplicationsAddAnApplicationError;
typedef AccessApplicationsPatchUpdateAccessApplicationSettingsError = AccessApplicationsAddAnApplicationError;
typedef AccessApplicationsPutUpdateAccessApplicationSettingsError = AccessApplicationsAddAnApplicationError;
typedef AccessApplicationsRevokeServiceTokensError = AccessApplicationsAddAnApplicationError;
typedef AccessApplicationsTestAccessPoliciesError = AccessApplicationsAddAnApplicationError;
typedef AccessApplicationsUpdateAnAccessApplicationError = AccessApplicationsAddAnApplicationError;
typedef AccessAuthenticationLogsGetAccessAuthenticationLogsError = AccessApplicationsAddAnApplicationError;
typedef AccessCustomPagesCreateACustomPageError = AccessApplicationsAddAnApplicationError;
typedef AccessCustomPagesDeleteACustomPageError = AccessApplicationsAddAnApplicationError;
typedef AccessCustomPagesGetACustomPageError = AccessApplicationsAddAnApplicationError;
typedef AccessCustomPagesListCustomPagesError = AccessApplicationsAddAnApplicationError;
typedef AccessCustomPagesUpdateACustomPageError = AccessApplicationsAddAnApplicationError;
typedef AccessGatewayCaAddAnSshCaError = AccessApplicationsAddAnApplicationError;
typedef AccessGatewayCaDeleteAnSshCaError = AccessApplicationsAddAnApplicationError;
typedef AccessGatewayCaListSshCaError = AccessApplicationsAddAnApplicationError;
typedef AccessGroupsCreateAnAccessGroupError = AccessApplicationsAddAnApplicationError;
typedef AccessGroupsDeleteAnAccessGroupError = AccessApplicationsAddAnApplicationError;
typedef AccessGroupsGetAnAccessGroupError = AccessApplicationsAddAnApplicationError;
typedef AccessGroupsListAccessGroupsError = AccessApplicationsAddAnApplicationError;
typedef AccessGroupsUpdateAnAccessGroupError = AccessApplicationsAddAnApplicationError;
typedef AccessIdentityProvidersAddAnAccessIdentityProviderError = AccessApplicationsAddAnApplicationError;
typedef AccessIdentityProvidersDeleteAnAccessIdentityProviderError = AccessApplicationsAddAnApplicationError;
typedef AccessIdentityProvidersGetAnAccessIdentityProviderError = AccessApplicationsAddAnApplicationError;
typedef AccessIdentityProvidersListAccessIdentityProvidersError = AccessApplicationsAddAnApplicationError;
typedef AccessIdentityProvidersListScimGroupResourcesError = AccessApplicationsAddAnApplicationError;
typedef AccessIdentityProvidersListScimUserResourcesError = AccessApplicationsAddAnApplicationError;
typedef AccessIdentityProvidersUpdateAnAccessIdentityProviderError = AccessApplicationsAddAnApplicationError;
typedef AccessKeyConfigurationGetTheAccessKeyConfigurationError = AccessApplicationsAddAnApplicationError;
typedef AccessKeyConfigurationRotateAccessKeysError = AccessApplicationsAddAnApplicationError;
typedef AccessKeyConfigurationUpdateTheAccessKeyConfigurationError = AccessApplicationsAddAnApplicationError;
typedef AccessMtlsAuthenticationAddAnMtlsCertificateError = AccessApplicationsAddAnApplicationError;
typedef AccessMtlsAuthenticationDeleteAnMtlsCertificateError = AccessApplicationsAddAnApplicationError;
typedef AccessMtlsAuthenticationGetAnMtlsCertificateError = AccessApplicationsAddAnApplicationError;
typedef AccessMtlsAuthenticationListMtlsCertificatesError = AccessApplicationsAddAnApplicationError;
typedef AccessMtlsAuthenticationListMtlsCertificatesHostnameSettingsError = AccessApplicationsAddAnApplicationError;
typedef AccessMtlsAuthenticationUpdateAnMtlsCertificateError = AccessApplicationsAddAnApplicationError;
typedef AccessMtlsAuthenticationUpdateAnMtlsCertificateSettingsError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesConvertReusableError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesCreateAnAccessPolicyError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesCreateAnAccessReusablePolicyError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesDeleteAnAccessPolicyError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesDeleteAnAccessReusablePolicyError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesGetAnAccessPolicyError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesGetAnAccessReusablePolicyError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesListAccessAppPoliciesError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesListAccessReusablePoliciesError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesUpdateAnAccessPolicyError = AccessApplicationsAddAnApplicationError;
typedef AccessPoliciesUpdateAnAccessReusablePolicyError = AccessApplicationsAddAnApplicationError;
typedef AccessScimUpdateLogsListAccessScimUpdateLogsError = AccessApplicationsAddAnApplicationError;
typedef AccessServiceTokensCreateAServiceTokenError = AccessApplicationsAddAnApplicationError;
typedef AccessServiceTokensDeleteAServiceTokenError = AccessApplicationsAddAnApplicationError;
typedef AccessServiceTokensGetAServiceTokenError = AccessApplicationsAddAnApplicationError;
typedef AccessServiceTokensListServiceTokensError = AccessApplicationsAddAnApplicationError;
typedef AccessServiceTokensRefreshAServiceTokenError = AccessApplicationsAddAnApplicationError;
typedef AccessServiceTokensRotateAServiceTokenError = AccessApplicationsAddAnApplicationError;
typedef AccessServiceTokensUpdateAServiceTokenError = AccessApplicationsAddAnApplicationError;
typedef AccessShortLivedCertificateCAsCreateAShortLivedCertificateCaError = AccessApplicationsAddAnApplicationError;
typedef AccessShortLivedCertificateCAsDeleteAShortLivedCertificateCaError = AccessApplicationsAddAnApplicationError;
typedef AccessShortLivedCertificateCAsGetAShortLivedCertificateCaError = AccessApplicationsAddAnApplicationError;
typedef AccessShortLivedCertificateCAsListShortLivedCertificateCAsError = AccessApplicationsAddAnApplicationError;
typedef AccessTagsCreateTagError = AccessApplicationsAddAnApplicationError;
typedef AccessTagsDeleteATagError = AccessApplicationsAddAnApplicationError;
typedef AccessTagsGetATagError = AccessApplicationsAddAnApplicationError;
typedef AccessTagsListTagsError = AccessApplicationsAddAnApplicationError;
typedef AccessTagsUpdateATagError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustOrganizationCreateYourZeroTrustOrganizationError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustOrganizationGetYourZeroTrustOrganizationError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustOrganizationGetYourZeroTrustOrganizationDohSettingsError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustOrganizationRevokeAllAccessTokensForAUserError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustOrganizationUpdateYourZeroTrustOrganizationError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustOrganizationUpdateYourZeroTrustOrganizationDohSettingsError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustSeatsUpdateAUserSeatError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustUsersCreateUserError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustUsersDeleteMfaAuthenticatorError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustUsersDeleteUserError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustUsersGetActiveSessionError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustUsersGetActiveSessionsError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustUsersGetFailedLoginsError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustUsersGetLastSeenIdentityError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustUsersGetUserError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustUsersGetUsersError = AccessApplicationsAddAnApplicationError;
typedef ZeroTrustUsersUpdateUserError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessApplicationsAddABookmarkApplicationError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessApplicationsDeleteAnAccessApplicationError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessApplicationsGetAnAccessApplicationError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessApplicationsListAccessApplicationsError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessApplicationsPatchUpdateAccessApplicationSettingsError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessApplicationsPutUpdateAccessApplicationSettingsError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessApplicationsRevokeServiceTokensError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessApplicationsTestAccessPoliciesError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessApplicationsUpdateABookmarkApplicationError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessGroupsCreateAnAccessGroupError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessGroupsDeleteAnAccessGroupError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessGroupsGetAnAccessGroupError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessGroupsListAccessGroupsError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessGroupsUpdateAnAccessGroupError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessIdentityProvidersAddAnAccessIdentityProviderError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessIdentityProvidersDeleteAnAccessIdentityProviderError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessIdentityProvidersGetAnAccessIdentityProviderError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessIdentityProvidersListAccessIdentityProvidersError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessIdentityProvidersUpdateAnAccessIdentityProviderError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessMtlsAuthenticationAddAnMtlsCertificateError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessMtlsAuthenticationDeleteAnMtlsCertificateError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessMtlsAuthenticationGetAnMtlsCertificateError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessMtlsAuthenticationListMtlsCertificatesError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessMtlsAuthenticationListMtlsCertificatesHostnameSettingsError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessMtlsAuthenticationUpdateAnMtlsCertificateError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessMtlsAuthenticationUpdateAnMtlsCertificateSettingsError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessPoliciesCreateAnAccessPolicyError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessPoliciesDeleteAnAccessPolicyError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessPoliciesGetAnAccessPolicyError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessPoliciesListAccessPoliciesError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessPoliciesUpdateAnAccessPolicyError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessServiceTokensCreateAServiceTokenError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessServiceTokensDeleteAServiceTokenError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessServiceTokensGetAServiceTokenError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessServiceTokensListServiceTokensError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessServiceTokensUpdateAServiceTokenError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessShortLivedCertificateCAsCreateAShortLivedCertificateCaError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessShortLivedCertificateCAsDeleteAShortLivedCertificateCaError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessShortLivedCertificateCAsGetAShortLivedCertificateCaError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelAccessShortLivedCertificateCAsListShortLivedCertificateCAsError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelZeroTrustOrganizationCreateYourZeroTrustOrganizationError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelZeroTrustOrganizationGetYourZeroTrustOrganizationError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelZeroTrustOrganizationRevokeAllAccessTokensForAUserError = AccessApplicationsAddAnApplicationError;
typedef ZoneLevelZeroTrustOrganizationUpdateYourZeroTrustOrganizationError = AccessApplicationsAddAnApplicationError;
