// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_github_rest_3_1/models/codespaces_create_for_authenticated_user_request/codespaces_create_for_authenticated_user_request_variant1.dart';import 'package:pub_github_rest_3_1/models/codespaces_create_for_authenticated_user_request/codespaces_create_for_authenticated_user_request_variant2.dart';typedef CodespacesCreateForAuthenticatedUserRequest = OneOf2<CodespacesCreateForAuthenticatedUserRequestVariant1,CodespacesCreateForAuthenticatedUserRequestVariant2>;
