// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_github_rest_3_1/models/interaction_limit_response.dart';import 'package:pub_github_rest_3_1/models/interactions_get_restrictions_for_authenticated_user_response/interactions_get_restrictions_for_authenticated_user_response_variant2.dart';typedef InteractionsGetRestrictionsForOrgResponse = OneOf2<InteractionLimitResponse,InteractionsGetRestrictionsForAuthenticatedUserResponseVariant2>;
