// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_twilio_api_v2010/models/account_call_call_notification_instance/request_method.dart';@immutable final class AccountNotification {const AccountNotification({this.accountSid, this.apiVersion, this.callSid, this.dateCreated, this.dateUpdated, this.errorCode, this.log, this.messageDate, this.messageText, this.moreInfo, this.requestMethod, this.requestUrl, this.sid, this.uri, });

factory AccountNotification.fromJson(Map<String, dynamic> json) { return AccountNotification(
  accountSid: json['account_sid'] as String?,
  apiVersion: json['api_version'] as String?,
  callSid: json['call_sid'] as String?,
  dateCreated: json['date_created'] as String?,
  dateUpdated: json['date_updated'] as String?,
  errorCode: json['error_code'] as String?,
  log: json['log'] as String?,
  messageDate: json['message_date'] as String?,
  messageText: json['message_text'] as String?,
  moreInfo: json['more_info'] != null ? Uri.parse(json['more_info'] as String) : null,
  requestMethod: json['request_method'] != null ? RequestMethod.fromJson(json['request_method'] as String) : null,
  requestUrl: json['request_url'] != null ? Uri.parse(json['request_url'] as String) : null,
  sid: json['sid'] as String?,
  uri: json['uri'] as String?,
); }

/// The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Notification resource.
final String? accountSid;

/// The API version used to generate the notification. Can be empty for events that don't have a specific API version, such as incoming phone calls.
final String? apiVersion;

/// The SID of the [Call](https://www.twilio.com/docs/voice/api/call-resource) the Notification resource is associated with.
final String? callSid;

/// The date and time in GMT that the resource was created specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
final String? dateCreated;

/// The date and time in GMT that the resource was last updated specified in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format.
final String? dateUpdated;

/// A unique error code for the error condition that is described in our [Error Dictionary](https://www.twilio.com/docs/api/errors).
final String? errorCode;

/// An integer log level that corresponds to the type of notification: `0` is ERROR, `1` is WARNING.
final String? log;

/// The date the notification was actually generated in [RFC 2822](https://www.ietf.org/rfc/rfc2822.txt) format. Message buffering can cause this value to differ from `date_created`.
final String? messageDate;

/// The text of the notification.
final String? messageText;

/// The URL for more information about the error condition. This value is a page in our [Error Dictionary](https://www.twilio.com/docs/api/errors).
final Uri? moreInfo;

/// The HTTP method used to generate the notification. If the notification was generated during a phone call, this is the HTTP Method used to request the resource on your server. If the notification was generated by your use of our REST API, this is the HTTP method used to call the resource on our servers.
final RequestMethod? requestMethod;

/// The URL of the resource that generated the notification. If the notification was generated during a phone call, this is the URL of the resource on your server that caused the notification. If the notification was generated by your use of our REST API, this is the URL of the resource you called.
final Uri? requestUrl;

/// The unique string that that we created to identify the Notification resource.
final String? sid;

/// The URI of the resource, relative to `https://api.twilio.com`.
final String? uri;

Map<String, dynamic> toJson() { return {
  'account_sid': ?accountSid,
  'api_version': ?apiVersion,
  'call_sid': ?callSid,
  'date_created': ?dateCreated,
  'date_updated': ?dateUpdated,
  'error_code': ?errorCode,
  'log': ?log,
  'message_date': ?messageDate,
  'message_text': ?messageText,
  if (moreInfo != null) 'more_info': moreInfo?.toString(),
  if (requestMethod != null) 'request_method': requestMethod?.toJson(),
  if (requestUrl != null) 'request_url': requestUrl?.toString(),
  'sid': ?sid,
  'uri': ?uri,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'account_sid', 'api_version', 'call_sid', 'date_created', 'date_updated', 'error_code', 'log', 'message_date', 'message_text', 'more_info', 'request_method', 'request_url', 'sid', 'uri'}.contains(key)); } 
/// Constraint violations for this value (empty when valid).
List<String> validate() { final errors = <String>[];
final accountSid$ = accountSid;
if (accountSid$ != null) {
  if (accountSid$.length < 34) errors.add('accountSid: length must be >= 34');
  if (accountSid$.length > 34) errors.add('accountSid: length must be <= 34');
  if (!RegExp(r'^AC[0-9a-fA-F]{32}$').hasMatch(accountSid$)) errors.add(r'accountSid: must match pattern ^AC[0-9a-fA-F]{32}$');
}
final callSid$ = callSid;
if (callSid$ != null) {
  if (callSid$.length < 34) errors.add('callSid: length must be >= 34');
  if (callSid$.length > 34) errors.add('callSid: length must be <= 34');
  if (!RegExp(r'^CA[0-9a-fA-F]{32}$').hasMatch(callSid$)) errors.add(r'callSid: must match pattern ^CA[0-9a-fA-F]{32}$');
}
final sid$ = sid;
if (sid$ != null) {
  if (sid$.length < 34) errors.add('sid: length must be >= 34');
  if (sid$.length > 34) errors.add('sid: length must be <= 34');
  if (!RegExp(r'^NO[0-9a-fA-F]{32}$').hasMatch(sid$)) errors.add(r'sid: must match pattern ^NO[0-9a-fA-F]{32}$');
}
return errors; } 
AccountNotification copyWith({String? Function()? accountSid, String? Function()? apiVersion, String? Function()? callSid, String? Function()? dateCreated, String? Function()? dateUpdated, String? Function()? errorCode, String? Function()? log, String? Function()? messageDate, String? Function()? messageText, Uri? Function()? moreInfo, RequestMethod? Function()? requestMethod, Uri? Function()? requestUrl, String? Function()? sid, String? Function()? uri, }) { return AccountNotification(
  accountSid: accountSid != null ? accountSid() : this.accountSid,
  apiVersion: apiVersion != null ? apiVersion() : this.apiVersion,
  callSid: callSid != null ? callSid() : this.callSid,
  dateCreated: dateCreated != null ? dateCreated() : this.dateCreated,
  dateUpdated: dateUpdated != null ? dateUpdated() : this.dateUpdated,
  errorCode: errorCode != null ? errorCode() : this.errorCode,
  log: log != null ? log() : this.log,
  messageDate: messageDate != null ? messageDate() : this.messageDate,
  messageText: messageText != null ? messageText() : this.messageText,
  moreInfo: moreInfo != null ? moreInfo() : this.moreInfo,
  requestMethod: requestMethod != null ? requestMethod() : this.requestMethod,
  requestUrl: requestUrl != null ? requestUrl() : this.requestUrl,
  sid: sid != null ? sid() : this.sid,
  uri: uri != null ? uri() : this.uri,
); } 
@override bool operator ==(Object other) => identical(this, other) ||
      other is AccountNotification &&
          accountSid == other.accountSid &&
          apiVersion == other.apiVersion &&
          callSid == other.callSid &&
          dateCreated == other.dateCreated &&
          dateUpdated == other.dateUpdated &&
          errorCode == other.errorCode &&
          log == other.log &&
          messageDate == other.messageDate &&
          messageText == other.messageText &&
          moreInfo == other.moreInfo &&
          requestMethod == other.requestMethod &&
          requestUrl == other.requestUrl &&
          sid == other.sid &&
          uri == other.uri;

@override int get hashCode => Object.hash(accountSid, apiVersion, callSid, dateCreated, dateUpdated, errorCode, log, messageDate, messageText, moreInfo, requestMethod, requestUrl, sid, uri);

@override String toString() => 'AccountNotification(\n  accountSid: $accountSid,\n  apiVersion: $apiVersion,\n  callSid: $callSid,\n  dateCreated: $dateCreated,\n  dateUpdated: $dateUpdated,\n  errorCode: $errorCode,\n  log: $log,\n  messageDate: $messageDate,\n  messageText: $messageText,\n  moreInfo: $moreInfo,\n  requestMethod: $requestMethod,\n  requestUrl: $requestUrl,\n  sid: $sid,\n  uri: $uri,\n)';

 }
