// GENERATED CODE - DO NOT MODIFY BY HAND

import 'package:degenerate_runtime/degenerate_runtime.dart';import 'package:pub_twilio_api_v2010/models/create_call_recording_request/recording_status_callback_method.dart';@immutable final class CreateCallRecordingRequest {const CreateCallRecordingRequest({this.recordingStatusCallbackEvent, this.recordingStatusCallback, this.recordingStatusCallbackMethod, this.trim, this.recordingChannels, this.recordingTrack, });

factory CreateCallRecordingRequest.fromJson(Map<String, dynamic> json) { return CreateCallRecordingRequest(
  recordingStatusCallbackEvent: (json['RecordingStatusCallbackEvent'] as List<dynamic>?)?.map((e) => e as String).toList(),
  recordingStatusCallback: json['RecordingStatusCallback'] != null ? Uri.parse(json['RecordingStatusCallback'] as String) : null,
  recordingStatusCallbackMethod: json['RecordingStatusCallbackMethod'] != null ? RecordingStatusCallbackMethod.fromJson(json['RecordingStatusCallbackMethod'] as String) : null,
  trim: json['Trim'] as String?,
  recordingChannels: json['RecordingChannels'] as String?,
  recordingTrack: json['RecordingTrack'] as String?,
); }

/// The recording status events on which we should call the `recording_status_callback` URL. Can be: `in-progress`, `completed` and `absent` and the default is `completed`. Separate multiple event values with a space.
final List<String>? recordingStatusCallbackEvent;

/// The URL we should call using the `recording_status_callback_method` on each recording event specified in  `recording_status_callback_event`. For more information, see [RecordingStatusCallback parameters](https://www.twilio.com/docs/voice/api/recording#recordingstatuscallback).
final Uri? recordingStatusCallback;

/// The HTTP method we should use to call `recording_status_callback`. Can be: `GET` or `POST` and the default is `POST`.
final RecordingStatusCallbackMethod? recordingStatusCallbackMethod;

/// Whether to trim any leading and trailing silence in the recording. Can be: `trim-silence` or `do-not-trim` and the default is `do-not-trim`. `trim-silence` trims the silence from the beginning and end of the recording and `do-not-trim` does not.
final String? trim;

/// The number of channels used in the recording. Can be: `mono` or `dual` and the default is `mono`. `mono` records all parties of the call into one channel. `dual` records each party of a 2-party call into separate channels.
final String? recordingChannels;

/// The audio track to record for the call. Can be: `inbound`, `outbound` or `both`. The default is `both`. `inbound` records the audio that is received by Twilio. `outbound` records the audio that is generated from Twilio. `both` records the audio that is received and generated by Twilio.
final String? recordingTrack;

Map<String, dynamic> toJson() { return {
  'RecordingStatusCallbackEvent': ?recordingStatusCallbackEvent,
  if (recordingStatusCallback != null) 'RecordingStatusCallback': recordingStatusCallback?.toString(),
  if (recordingStatusCallbackMethod != null) 'RecordingStatusCallbackMethod': recordingStatusCallbackMethod?.toJson(),
  'Trim': ?trim,
  'RecordingChannels': ?recordingChannels,
  'RecordingTrack': ?recordingTrack,
}; } 
static bool canParse(Map<String, dynamic> json) { return json.keys.any((key) => const {'RecordingStatusCallbackEvent', 'RecordingStatusCallback', 'RecordingStatusCallbackMethod', 'Trim', 'RecordingChannels', 'RecordingTrack'}.contains(key)); } 
CreateCallRecordingRequest copyWith({List<String> Function()? recordingStatusCallbackEvent, Uri Function()? recordingStatusCallback, RecordingStatusCallbackMethod Function()? recordingStatusCallbackMethod, String Function()? trim, String Function()? recordingChannels, String Function()? recordingTrack, }) { return CreateCallRecordingRequest(
  recordingStatusCallbackEvent: recordingStatusCallbackEvent != null ? recordingStatusCallbackEvent() : this.recordingStatusCallbackEvent,
  recordingStatusCallback: recordingStatusCallback != null ? recordingStatusCallback() : this.recordingStatusCallback,
  recordingStatusCallbackMethod: recordingStatusCallbackMethod != null ? recordingStatusCallbackMethod() : this.recordingStatusCallbackMethod,
  trim: trim != null ? trim() : this.trim,
  recordingChannels: recordingChannels != null ? recordingChannels() : this.recordingChannels,
  recordingTrack: recordingTrack != null ? recordingTrack() : this.recordingTrack,
); } 
@override bool operator ==(Object other) { return identical(this, other) ||
      other is CreateCallRecordingRequest &&
          listEquals(recordingStatusCallbackEvent, other.recordingStatusCallbackEvent) &&
          recordingStatusCallback == other.recordingStatusCallback &&
          recordingStatusCallbackMethod == other.recordingStatusCallbackMethod &&
          trim == other.trim &&
          recordingChannels == other.recordingChannels &&
          recordingTrack == other.recordingTrack; } 
@override int get hashCode { return Object.hash(Object.hashAll(recordingStatusCallbackEvent ?? const []), recordingStatusCallback, recordingStatusCallbackMethod, trim, recordingChannels, recordingTrack); } 
@override String toString() { return 'CreateCallRecordingRequest(recordingStatusCallbackEvent: $recordingStatusCallbackEvent, recordingStatusCallback: $recordingStatusCallback, recordingStatusCallbackMethod: $recordingStatusCallbackMethod, trim: $trim, recordingChannels: $recordingChannels, recordingTrack: $recordingTrack)'; } 
 }
