// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/CreateImageRequest (inline: Moderation)

import 'package:degenerate_runtime/degenerate_runtime.dart';/// Control the content-moderation level for images generated by the GPT image models. Must be either `low` for less restrictive filtering or `auto` (default value).
@immutable final class CreateImageRequestModeration {const CreateImageRequestModeration._(this.value);

factory CreateImageRequestModeration.fromJson(String json) { return switch (json) {
  'low' => low,
  'auto' => auto,
  _ => CreateImageRequestModeration._(json),
}; }

static const CreateImageRequestModeration low = CreateImageRequestModeration._('low');

static const CreateImageRequestModeration auto = CreateImageRequestModeration._('auto');

static const List<CreateImageRequestModeration> values = [low, auto];

final String value;

String toJson() { return value; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return !values.contains(this); } 
@override bool operator ==(Object other) => identical(this, other) ||
    other is CreateImageRequestModeration && other.value == value;

@override int get hashCode => value.hashCode;

@override String toString() => 'CreateImageRequestModeration($value)';

 }
