// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: #/components/schemas/CreateImageRequest (inline: Moderation)

import 'package:degenerate_runtime/degenerate_runtime.dart';/// Control the content-moderation level for images generated by the GPT image models. Must be either `low` for less restrictive filtering or `auto` (default value).
sealed class CreateImageRequestModeration {const CreateImageRequestModeration();

factory CreateImageRequestModeration.fromJson(String json) { return switch (json) {
  'low' => low,
  'auto' => auto,
  _ => CreateImageRequestModeration$Unknown(json),
}; }

static const CreateImageRequestModeration low = CreateImageRequestModeration$low._();

static const CreateImageRequestModeration auto = CreateImageRequestModeration$auto._();

static const List<CreateImageRequestModeration> values = [low, auto];

String get value;
String toJson() { return value; } 
/// The Dart identifier name for this value, or the raw value if unknown.
String get name { return switch (value) {
  'low' => 'low',
  'auto' => 'auto',
  _ => value,
}; } 
/// Whether this value is unknown (not defined in the OpenAPI spec).
bool get isUnknown { return this is CreateImageRequestModeration$Unknown; } 
@override String toString() => 'CreateImageRequestModeration($value)';

 }
@immutable final class CreateImageRequestModeration$low extends CreateImageRequestModeration {const CreateImageRequestModeration$low._();

@override String get value => 'low';

@override bool operator ==(Object other) => identical(this, other) || other is CreateImageRequestModeration$low;

@override int get hashCode => 'low'.hashCode;

 }
@immutable final class CreateImageRequestModeration$auto extends CreateImageRequestModeration {const CreateImageRequestModeration$auto._();

@override String get value => 'auto';

@override bool operator ==(Object other) => identical(this, other) || other is CreateImageRequestModeration$auto;

@override int get hashCode => 'auto'.hashCode;

 }
@immutable final class CreateImageRequestModeration$Unknown extends CreateImageRequestModeration {const CreateImageRequestModeration$Unknown(this.value);

@override final String value;

@override bool operator ==(Object other) => identical(this, other) ||
    other is CreateImageRequestModeration$Unknown && other.value == value;

@override int get hashCode => value.hashCode;

 }
